### ISSUE TITLE
Fix the Sum method.

### ISSUE THREAD

**Issue by BlakeGuilloud** [BlakeGuilloud/ganon#1]
There is currently a method called `Sum` that lives in `/lib/sum.js`.
It is incomplete and needs to be fixed!

### Acceptance Criteria:
1. Running `yarn test sum` results in tests passing.

#### Please include the skeleton of a new method + an accompanying test for someone else to work on at the time of creating a pull request!

**Comment by dudmacedo** [comment]
I'm working on it

**Comment by BlakeGuilloud** [comment]
Great- Thanks @dudmacedo !

**Comment by brycereynolds** [comment]
Haha so I PR'd all the open tickets, and in that five minutes it looks like they've all been claimed :)

**Comment by brycereynolds** [comment]
Anyhow this is out there.. 
https://github.com/BlakeGuilloud/ganon/pull/6

**Comment by dudmacedo** [comment]
Solved, PR #17
