### ISSUE TITLE
Updates to Travis CI

### ISSUE THREAD

**Issue by BlakeGuilloud** [BlakeGuilloud/ganon#103]
So I merged in a travis CI config and realized it may be counter intuitive in this project. The objective of this project is to have broken tests for someone else to fix. So the build should always fail.

Does anyone know if there are ways to configure travis to run our linter instead of run tests?

cc. @shawnhwei

**Comment by BlakeGuilloud** [comment]
I actually figured it out! For reference you can put something like this in the .travis.yml file

script:
  - "npm run lint"

**Comment by shawnhwei** [comment]
I guess you have a point haha. I just imagined one day it would be cool to see the icon turn green.

In regards to your question, Travis can be setup to run an arbitrary build script and deploy a release to Github.

**Comment by BlakeGuilloud** [comment]
I know. I <3 icons

**Comment by BlakeGuilloud** [comment]
Whoops @shawnhwei ! I accidentally merged in the wrong icon. It was pointed at your fork 😂 "https://travis-ci.org/shawnhwei/ganon.svg?branch=master"

**Comment by shawnhwei** [comment]
Oh that would be my mistake...

**Comment by BlakeGuilloud** [comment]
No worries! Got it fixed and that green icon!

**Comment by BlakeGuilloud** [comment]
One day we need to get that "prettier" icon in there too.
