### ISSUE TITLE
Fix SwapCase method

### ISSUE THREAD

**Issue by BlakeGuilloud** [BlakeGuilloud/ganon#110]
There is currently a method called `swapCase` that lives in `/lib/swapCase.js`.
It is incomplete and needs to be fixed!

### Acceptance Criteria:
1. Running `yarn test swapCase` results in tests passing.

#### Please include the skeleton of a new method + an accompanying test for someone else to work on at the time of creating a pull request!

**Comment by ksjc1995** [comment]
@BlakeGuilloud I would like to work on this.

**Comment by andreasgruenh** [comment]
Thank your for contributing! Awesome work with #130
