### ISSUE TITLE
Fix UpperCase method

### ISSUE THREAD

**Issue by BlakeGuilloud** [BlakeGuilloud/ganon#111]
There is currently a method called `upperCase` that lives in `/lib/upperCase.js`.
It is incomplete and needs to be fixed!

### Acceptance Criteria:
1. Running `yarn test upperCase` results in tests passing.

#### Please include the skeleton of a new method + an accompanying test for someone else to work on at the time of creating a pull request!

**Comment by abhigyank** [comment]
I'd like to be assigned on this issue.

**Comment by BlakeGuilloud** [comment]
It's yours @abhigyank !! I will apply the "in progress" label for the next 24 hours. If you need more time, feel free to reach out! Thanks!

**Comment by abhigyank** [comment]
@BlakeGuilloud while running 'yarn test upperCase' I am getting this error as test fails -> ' TypeError: uppercase is not a function'.
What could be the possible reason?

**Comment by BlakeGuilloud** [comment]
That is most likely being caused by the function not being properly exported from “lib/index.js” fake a look in that file and confirm the method you are working on is there

**Comment by BlakeGuilloud** [comment]
Thank you @abhigyank
