### ISSUE TITLE
Fix isEven method

### ISSUE THREAD

**Issue by BlakeGuilloud** [BlakeGuilloud/ganon#117]
There is currently a method called `isEven` that lives in `/lib/isEven.js`.
It is incomplete and needs to be fixed!

### Acceptance Criteria:
1. Running `yarn test isEven` results in tests passing.
2. You have written a skeleton method for someone else to work on.
3. You have written tests surrounding your skeleton method.
4. Running `yarn lint` does not print any errors to the console!

### Please include the skeleton of a new method + an accompanying test for someone else to work on at the time of creating a pull request! A pull request will most likely be denied if it does not contain a skeleton method for someone else to work on! For more information, please read the [Contributing Guide](https://github.com/BlakeGuilloud/ganon/blob/master/CONTRIBUTING.md).

Thank you so much for your contribution!

**Comment by nidhihooda** [comment]
I would like to be assigned this.

**Comment by andreasgruenh** [comment]
Sure, @nidhihooda give it a try :)

**Comment by nidhihooda** [comment]
@BlakeGuilloud / @andreasgruenh Could you please provide a reference to a similar issue which has been fixed as per the acceptance criteria?

**Comment by ktilcu** [comment]
@nidhihooda Here is the most recently accepted Pull Request: https://github.com/BlakeGuilloud/ganon/pull/207/files

**Comment by BlakeGuilloud** [comment]
I am going to open this one back up for someone else to work on since it's been over 24 hours.
