### ISSUE TITLE
Create our logo!!

### ISSUE THREAD

**Issue by BlakeGuilloud** [BlakeGuilloud/ganon#119]
It's a silly request, but I thought I would throw it out there! It would be awesome if we had some sort of logo to represent the project. I know absolutely nothing about designing or shipping a logo, so this is completely up to the contributor! Feel free to take it however you would like.

**Comment by csleong98** [comment]
What are the requirements for the logo

**Comment by BlakeGuilloud** [comment]
I have no clue. The name Ganon is inspired from The Legend of Zelda franchise. I know absolutely nothing about designing or shipping a logo, so this is completely up to the contributor! Feel free to take it however you would like.

**Comment by csleong98** [comment]
ikr XD alright since it is inspire Zelda i'll create 1 base on the Ganon's face a simple icon

**Comment by BlakeGuilloud** [comment]
You're awesome @csleong98 !!!!! I'll make sure and give you a nice shoutout in the readme!

**Comment by csleong98** [comment]
alright thx

**Comment by csleong98** [comment]
Work in Progress. What do u think?
![ganon](https://user-images.githubusercontent.com/6150058/31778140-76e82af6-b522-11e7-8eea-9a9e0b4037e5.png)

**Comment by BlakeGuilloud** [comment]
@csleong98 !! wow!! This is freaking awesome. Thank you so much for the work on this. I am REALLY impressed!

**Comment by BlakeGuilloud** [comment]
@csleong98 Whenever you feel comfortable with me putting this logo in our README. Just let me know. The .png that is in our project already looks awesome!! Thanks again for doing this.

**Comment by csleong98** [comment]
I have created a version 2 of the logo with a new pull request.

**Comment by BlakeGuilloud** [comment]
Thank you so much!
