### ISSUE TITLE
Fix the Xor method

### ISSUE THREAD

**Issue by BlakeGuilloud** [BlakeGuilloud/ganon#12]
There is currently a method called `xor` that lives in `/lib/xor.js`.
It is incomplete and needs to be fixed!

### Acceptance Criteria:
1. Running `yarn test xor` results in tests passing.

#### Please include the skeleton of a new method + an accompanying test for someone else to work on at the time of creating a pull request!

**Comment by hugoduraes** [comment]
Dibs :)
