### ISSUE TITLE
Fix the Exponent method

### ISSUE THREAD

**Issue by BlakeGuilloud** [BlakeGuilloud/ganon#13]
There is currently a method called `exponent` that lives in `/lib/exponent.js`.
It is incomplete and needs to be fixed!

### Acceptance Criteria:
1. Running `yarn test exponent` results in tests passing.

#### Please include the skeleton of a new method + an accompanying test for someone else to work on at the time of creating a pull request!

**Comment by Wulingoh** [comment]
I will give this a go too.

**Comment by BlakeGuilloud** [comment]
Just please make sure to include a skeleton method + test for each method you fix! These can be anything useful!

**Comment by Wulingoh** [comment]
Hi, I have resolved this issue with skeleton method. Are you able to merge it?

**Comment by BlakeGuilloud** [comment]
Hey @Wulingoh ! I am seeing a merge conflict with your pull request: https://github.com/BlakeGuilloud/ganon/pull/56/files

Please pull in the latest master, push it up, and I will merge away! The merge conflict is most likely someone adding a new function to the `lib/index.js` file! 

Thanks for your contribution!
