### ISSUE TITLE
Fix "sign" method 

### ISSUE THREAD

**Issue by LSBOSS** [BlakeGuilloud/ganon#131]
There is currently a method called `sign` that lives in `/lib/sign.js`.
It is incomplete and needs to be fixed!

### Acceptance Criteria:
1. Running `yarn test sign` results in tests passing.
2. You have written a skeleton method for someone else to work on.
3. You have written tests surrounding your skeleton method.
4. Running `yarn lint` does not print any errors to the console!

### Please include the skeleton of a new method + an accompanying test for someone else to work on at the time of creating a pull request! A pull request will most likely be denied if it does not contain a skeleton method for someone else to work on! For more information, please read the [Contributing Guide](https://github.com/BlakeGuilloud/ganon/blob/master/CONTRIBUTING.md).

Thank you so much for your contribution!

**Comment by doubledare704** [comment]
I'd like to take this fix

**Comment by andreasgruenh** [comment]
:D Sure, go ahead @doubledare704

**Comment by doubledare704** [comment]
There is an issue in tests:
![image](https://user-images.githubusercontent.com/10940053/31774466-86b1e5b4-b4ee-11e7-8dd8-a1d4fbda7fcb.png)
NaN === NaN returns false
