### ISSUE TITLE
Fix the Abs method

### ISSUE THREAD

**Issue by BlakeGuilloud** [BlakeGuilloud/ganon#14]
There is currently a method called `Abs` that lives in `/lib/abs.js`.
It is incomplete and needs to be fixed!

### Acceptance Criteria:
1. Running `yarn test abs` results in tests passing.

#### Please include the skeleton of a new method + an accompanying test for someone else to work on at the time of creating a pull request!

**Comment by Wulingoh** [comment]
i will take a look at it.

**Comment by BlakeGuilloud** [comment]
Sounds good @Wulingoh !

**Comment by BlakeGuilloud** [comment]
@Wulingoh Sorry I just merged in someone else's fix for this! Feel free to improve what they did if you would like!

**Comment by Wulingoh** [comment]
Hi that's fine. I am now working on exponent method. I am very new to JavaScript and still learning. Hope I can finish the other issue.

**Comment by BlakeGuilloud** [comment]
I'll definitely wait on you to get that one in! Take your time
