### ISSUE TITLE
Fix dec2hex method

### ISSUE THREAD

**Issue by doubledare704** [BlakeGuilloud/ganon#146]
There is currently a method called `dec2hex` that lives in `/lib/dec2hex.js`.
It is incomplete and needs to be fixed!

### Acceptance Criteria:
1. Running `yarn test dec2hex` results in tests passing.
2. You have written a skeleton method for someone else to work on.
3. You have written tests surrounding your skeleton method.
4. Running `yarn lint` does not print any errors to the console!

### Please include the skeleton of a new method + an accompanying test for someone else to work on at the time of creating a pull request! A pull request will most likely be denied if it does not contain a skeleton method for someone else to work on! For more information, please read the [Contributing Guide](https://github.com/BlakeGuilloud/ganon/blob/master/CONTRIBUTING.md).

Thank you so much for your contribution!

**Comment by luisvillalba** [comment]
I can do this

**Comment by ktilcu** [comment]
@luisvillalba still working on this?

**Comment by BlakeGuilloud** [comment]
Hey @luisvillalba ! I know we were chatting in a different issue earlier today. Are you still interested in this? If not, I want to open it up for someone else to work on.

**Comment by BlakeGuilloud** [comment]
Opening this back up

**Comment by keawade** [comment]
@BlakeGuilloud I would like to work on this
