### ISSUE TITLE
Fix "dec2oct" method

### ISSUE THREAD

**Issue by doubledare704** [BlakeGuilloud/ganon#147]
There is currently a method called `dec2oct` that lives in `/lib/dec2oct.js`.
It is incomplete and needs to be fixed!

### Acceptance Criteria:
1. Running `yarn test dec2oct` results in tests passing.
2. You have written a skeleton method for someone else to work on.
3. You have written tests surrounding your skeleton method.
4. Running `yarn lint` does not print any errors to the console!

### Please include the skeleton of a new method + an accompanying test for someone else to work on at the time of creating a pull request! A pull request will most likely be denied if it does not contain a skeleton method for someone else to work on! For more information, please read the [Contributing Guide](https://github.com/BlakeGuilloud/ganon/blob/master/CONTRIBUTING.md).

Thank you so much for your contribution!

**Comment by v-chmykov** [comment]
I can do this

**Comment by BlakeGuilloud** [comment]
Awesome @v-chmykov !! I have applied the 'in progress' label. This buys you 24 hours. Feel free to reach out if you need more time! THanks for contributing!
