### ISSUE TITLE
Fix functional composition methods!

### ISSUE THREAD

**Issue by andreasgruenh** [BlakeGuilloud/ganon#155]
There are currently methods called `compose`, `flow` and `pipe`, that live in `/lib/<methodName>.js`.
They are incomplete and needs to be fixed!

### Acceptance Criteria:
1. Running `yarn test flow compose pipe` results in tests passing.
2. You have written **at least two** skeleton method for someone else to work on.
3. You have written tests surrounding your skeleton methods.
4. Running `yarn lint` does not print any errors to the console!

### Please include the skeleton of a new method + an accompanying test for someone else to work on at the time of creating a pull request! A pull request will be denied if it does not contain a skeleton method for someone else to work on! For more information, please read the [Contributing Guide](https://github.com/BlakeGuilloud/ganon/blob/master/CONTRIBUTING.md).

Thank you so much for your contribution!

**Comment by kosciak9** [comment]
I've started working on this :)

**Comment by kosciak9** [comment]
I've created first implementation of `flow` function and skeleton function `hex2string`. As it's my first *serious* work on OSS project, I would be grateful if someone could just take a look and tell me if I'm doing something wrong. :)

[Link to `flow.js`](https://github.com/kosciak9/ganon/blob/1ef3bbed1ec62e4cdeda7119cece3bbec9392c4e/lib/flow.js)

[Link to `hex2string.js`](https://github.com/kosciak9/ganon/blob/master/lib/hex2string.js)

**Comment by andreasgruenh** [comment]
I'm only on mobile right now, but your flow implement looks fine. If you want any suggestions, I'd recommend trying to replace the forEach loop with outside variable with a reduce call. If you're interested, you could add this change to this pull request, if not, we will merge this later.

**Comment by kosciak9** [comment]
If it's a better way of doing it, I surely want to. But I'm not entirely sure what do you mean by outside variable here - copying arguments list to another variable? 

On October 19, 2017 9:08:11 PM GMT+02:00, Andreas <notifications@github.com> wrote:
>I'm only on mobile right now, but your flow implement looks fine. If
>you want any suggestions, I'd recommend trying to replace the forEach
>loop with outside variable with a reduce call. If you're interested,
>you could add this change to this pull request, if not, we will merge
>this later. 
>
>-- 
>You are receiving this because you commented.
>Reply to this email directly or view it on GitHub:
>https://github.com/BlakeGuilloud/ganon/issues/155#issuecomment-338007113

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by andreasgruenh** [comment]
Right now you are placing intermediate values in a variable. By doing it with a reduce call you can omit this variable.

**Comment by kosciak9** [comment]
I get it know. Will look into it tomorrow. 

On October 19, 2017 10:25:55 PM GMT+02:00, Andreas <notifications@github.com> wrote:
>Right now you are placing intermediate values in a variable. By doing
>it with a reduce call you can omit this variable. 
>
>-- 
>You are receiving this because you commented.
>Reply to this email directly or view it on GitHub:
>https://github.com/BlakeGuilloud/ganon/issues/155#issuecomment-338027626

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by ktilcu** [comment]
@kosciak9 If you submit a PR then it will be easier to review!

**Comment by kosciak9** [comment]
I will submit it in the minute. :)

**Comment by josephmcasey** [comment]
🙁  Forgotten, not lost. I'll pick this up and clean it off.

**Comment by kosciak9** [comment]
Sorry guys, got caught on college duties. Looks like the only t-shirt I'm getting is the one from the dryer. :D take it and go for it my friend 

On October 24, 2017 5:48:16 PM GMT+02:00, Joseph Michael Casey <notifications@github.com> wrote:
>🙁  Forgotten, not lost. I'll pick this up and clean it off.
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/BlakeGuilloud/ganon/issues/155#issuecomment-339036938

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by josephmcasey** [comment]
I've submitted a pull request that addresses the issues brought up during the #210 pull request.
