### ISSUE TITLE
Fix lint errors

### ISSUE THREAD

**Issue by luisvillalba** [BlakeGuilloud/ganon#156]
Noticed there's 24 lint issues again, it might be because people are preventing pre-commit hook to do its job by executing `git commit --no-verify` which should be forbidden.

**Comment by luisvillalba** [comment]
I'll do this

**Comment by andreasgruenh** [comment]
I don't have any linting errors on the current master branch and the travis build (uses the linter) is also working? Could you post the result of your lint command?

**Comment by luisvillalba** [comment]
Hmm weird, I see this

```
/ganon/lib/compose.js
  8:21  error  'funcs' is defined but never used  no-unused-vars

/ganon/lib/countSpaces.js
  3:22  error  'str' is defined but never used  no-unused-vars

/ganon/lib/dec2hex.js
  3:18  error  'a' is defined but never used  no-unused-vars

/ganon/lib/dec2oct.js
  3:18  error  'a' is defined but never used  no-unused-vars

/ganon/lib/floor.js
  7:2  error  Mixed spaces and tabs  no-mixed-spaces-and-tabs

/ganon/lib/flow.js
  8:18  error  'funcs' is defined but never used  no-unused-vars

/ganon/lib/invert.js
  8:17  error  'obj' is defined but never used  no-unused-vars

/ganon/lib/isPalindrome.js
  6:23  error  'value' is defined but never used  no-unused-vars

/ganon/lib/isPythagoreanTriple.js
  8:36  error  'c' is defined but never used  no-unused-vars

/ganon/lib/lowercase.js
  3:20  error  's' is defined but never used  no-unused-vars

/ganon/lib/mean.js
  3:18  error  'b' is defined but never used  no-unused-vars

/ganon/lib/mode.js
  5:15  error  'list' is defined but never used  no-unused-vars

/ganon/lib/pipe.js
  10:15  error  'initialValue' is defined but never used  no-unused-vars

/ganon/lib/reverse.js
   7:5  error  Unreachable code  no-unreachable
  10:5  error  Unreachable code  no-unreachable

/ganon/lib/round.js
  3:16  error  'n' is defined but never used  no-unused-vars

/ganon/lib/startsWith.js
  8:35  error  'substring' is defined but never used  no-unused-vars

/ganon/lib/swapCase.js
  14:2  error  Mixed spaces and tabs  no-mixed-spaces-and-tabs
  18:2  error  Mixed spaces and tabs  no-mixed-spaces-and-tabs
  22:2  error  Mixed spaces and tabs  no-mixed-spaces-and-tabs
  23:2  error  Mixed spaces and tabs  no-mixed-spaces-and-tabs
  25:2  error  Mixed spaces and tabs  no-mixed-spaces-and-tabs

/ganon/lib/take.js
  6:22  error  'n' is defined but never used  no-unused-vars

/ganon/test/fibonacci.test.js
  12:107  error  Unnecessary escape character: \'  no-useless-escape

✖ 24 problems (24 errors, 0 warnings)

error Command failed with exit code 1.
```

**Comment by andreasgruenh** [comment]
Mh, did you use yarn to install dependencies? Could be that you or me are on a different version of eslint that has different results?

**Comment by luisvillalba** [comment]
Used yarn to install all the dependencies

I'm running eslint 4.9.0 using the .eslintrc in the project

**Comment by BlakeGuilloud** [comment]
Really strange @luisvillalba . I am not having any linting errors either. I think it may have something to do with your local env somehow- I looked into the Unnecessary escape character specifically in fibonacci.test.js and see that there is in fact a useless escape: "Hundredth Fibonacci number (index 99) produces error - solution is 218922995834555169026, but JS can\'t represent it precisely"; however, we do not have any rules configured for that. When I add "no-useless-escape": "error" to our .eslintrc, and then run yarn lint, it throws the error in fibonacci test. What this tells me is that there is some config overwriting our .eslintrc for you.

**Comment by luisvillalba** [comment]
Hmm interesting, it might be a global config then, what do you think of this, changing:
```
 "lint": "eslint ./lib ./test",
```
for this
```
 "lint": "eslint -c .eslintrc ./lib ./test",
```
So we make sure everyone is using the same eslintrc?

Also should we extend eslint:recommended?

**Comment by BlakeGuilloud** [comment]
Is the -c tag like a 'config' kind of tag? I've never used it but just tested it locally and it seems to be working fine on my end. Does using that resolve the errors you mentioned?

**Comment by BlakeGuilloud** [comment]
I would be open to using eslint:recommended with the exception of the "no-unused-vars" rule. Considering the scope of this project is to build "shells" of functions, there are going to be plenty of unused variables while this is in it's early stages.

**Comment by luisvillalba** [comment]
Actually `eslint --no-eslintrc -c .eslintrc ./lib ./test` works fine.

setting -c only don't

**Comment by BlakeGuilloud** [comment]
Thanks for this @luisvillalba !!
