### ISSUE TITLE
Fix first method

### ISSUE THREAD

**Issue by BlakeGuilloud** [BlakeGuilloud/ganon#166]
There is currently a method called `first` that lives in `/lib/first.js`.
It is incomplete and needs to be fixed!

### Acceptance Criteria:
1. Running `yarn test first` results in tests passing.
2. You have written a skeleton method for someone else to work on.
3. You have written tests surrounding your skeleton method.
4. Running `yarn lint` does not print any errors to the console!

### Please include the skeleton of a new method + an accompanying test for someone else to work on at the time of creating a pull request! A pull request will most likely be denied if it does not contain a skeleton method for someone else to work on! For more information, please read the [Contributing Guide](https://github.com/BlakeGuilloud/ganon/blob/master/CONTRIBUTING.md).

Thank you so much for your contribution!

**Comment by pbateman828** [comment]
@BlakeGuilloud I would like to work on this

**Comment by BlakeGuilloud** [comment]
All yours @pbateman828 !

**Comment by BlakeGuilloud** [comment]
Hey @pbateman828 ! Are you still interested in this issue?

**Comment by pbateman828** [comment]
I'm cutting it real close, my bad @BlakeGuilloud

**Comment by BlakeGuilloud** [comment]
Great work @pbateman828 !! Don't worry about it haha
