### ISSUE TITLE
Fix Zip test

### ISSUE THREAD

**Issue by BlakeGuilloud** [BlakeGuilloud/ganon#167]
There is currently a method called `zip` that lives in `/lib/zip.js`.
It is incomplete and needs to be fixed!

### Acceptance Criteria:
1. Running `yarn test zip` results in tests passing.
2. You have written a skeleton method for someone else to work on.
3. You have written tests surrounding your skeleton method.
4. Running `yarn lint` does not print any errors to the console!

### Please include the skeleton of a new method + an accompanying test for someone else to work on at the time of creating a pull request! A pull request will most likely be denied if it does not contain a skeleton method for someone else to work on! For more information, please read the [Contributing Guide](https://github.com/BlakeGuilloud/ganon/blob/master/CONTRIBUTING.md).

Thank you so much for your contribution!

**Comment by stillNovice** [comment]
i am on it

**Comment by BlakeGuilloud** [comment]
sounds good @stillNovice !

**Comment by stillNovice** [comment]
@BlakeGuilloud In the zip.test.js file, there is strict equality testing for returned array, which is not letting me pass the tests. I think it should be expect().toEqual() instead of expect().toBe() in the zip.test.js. Please look into it.

**Comment by stillNovice** [comment]
@BlakeGuilloud did you get a chance to look into it?

**Comment by BlakeGuilloud** [comment]
Hey sorry for the delayed response. Yes- you are most likely correct in your assumption that it should be .toEqual()! Nice catch. For future reference, don't be afraid to adjust tests for skeleton methods if you feel they are incorrect. Thanks @stillNovice !

**Comment by stillNovice** [comment]
okay. Thanks for confirming @BlakeGuilloud .

**Comment by ktilcu** [comment]
Whoops I made that one. Sorry :(
