### ISSUE TITLE
Fix dec2binary function

### ISSUE THREAD

**Issue by BlakeGuilloud** [BlakeGuilloud/ganon#168]
There is currently a method called `dec2binary` that lives in `/lib/dec2binary.js`.
It is incomplete and needs to be fixed!

### Acceptance Criteria:
1. Running `yarn test dec2binary` results in tests passing.
2. You have written a skeleton method for someone else to work on.
3. You have written tests surrounding your skeleton method.
4. Running `yarn lint` does not print any errors to the console!

### Please include the skeleton of a new method + an accompanying test for someone else to work on at the time of creating a pull request! A pull request will most likely be denied if it does not contain a skeleton method for someone else to work on! For more information, please read the [Contributing Guide](https://github.com/BlakeGuilloud/ganon/blob/master/CONTRIBUTING.md).

Thank you so much for your contribution!

**Comment by emanuelcasco** [comment]
@BlakeGuilloud I would like to work on this!

**Comment by BlakeGuilloud** [comment]
Cool deal @emanuelcasco ! I'll apply the in progress label. Just keep in mind, that for each method you fix, you need to include a Skeleton Method for someone else to work on! Thanks for your contributions.

**Comment by josephmcasey** [comment]
It looks like this one has a little dust one it. I'm on it!

**Comment by josephmcasey** [comment]
Awesome! I've submitted a pull request #402 ! An important behavior which was not defined by the original issue involves very large integers, like 128-bit. Without a behavior defined by the issue, I expanded the behavior to throw and error when the binary conversion can't be guaranteed.

**Comment by newbazz** [comment]
I would like to work on this.

**Comment by BlakeGuilloud** [comment]
Hey @newbazz ! Looks like this already got merged in. If you feel you can improve it, go for it!
