### ISSUE TITLE
Fix startsWith method

### ISSUE THREAD

**Issue by BlakeGuilloud** [BlakeGuilloud/ganon#170]
There is currently a method called `startsWith` that lives in `/lib/startsWith.js`.
It is incomplete and needs to be fixed!

### Acceptance Criteria:
1. Running `yarn test startsWith` results in tests passing.
2. You have written a skeleton method for someone else to work on.
3. You have written tests surrounding your skeleton method.
4. Running `yarn lint` does not print any errors to the console!

### Please include the skeleton of a new method + an accompanying test for someone else to work on at the time of creating a pull request! A pull request will most likely be denied if it does not contain a skeleton method for someone else to work on! For more information, please read the [Contributing Guide](https://github.com/BlakeGuilloud/ganon/blob/master/CONTRIBUTING.md).

Thank you so much for your contribution!

**Comment by erinesco** [comment]
Will grab this one! @BlakeGuilloud

**Comment by BlakeGuilloud** [comment]
Awesome @erinesco !!

**Comment by erinesco** [comment]
@BlakeGuilloud are you able to get `yarn test startsWith` to run? no matter how many ways I've tried/configurations I've checked, I get `
    TypeError: startsWith is not a function

      at Object.<anonymous> (test/startsWith.test.js:11:12)`

**Comment by BlakeGuilloud** [comment]
Hey @erinesco !! So sorry about this- it looks like the `startsWith` function was not properly exported from `lib/index.js`. You will need to add the following to that file:

```
startsWith: require("./startsWith"),
```

This is how we export the project as an npm package! But sorry about that!!

**Comment by erinesco** [comment]
no worries--can't believe I didn't see that!

**Comment by BlakeGuilloud** [comment]
🎉 🎉 🎉 🎉  Thanks!
