### ISSUE TITLE
Fix Round function

### ISSUE THREAD

**Issue by BlakeGuilloud** [BlakeGuilloud/ganon#171]
There is currently a method called `round` that lives in `/lib/round.js`.
It is incomplete and needs to be fixed!

### Acceptance Criteria:
1. Running `yarn test round` results in tests passing.
2. You have written a skeleton method for someone else to work on.
3. You have written tests surrounding your skeleton method.
4. Running `yarn lint` does not print any errors to the console!

### Please include the skeleton of a new method + an accompanying test for someone else to work on at the time of creating a pull request! A pull request will most likely be denied if it does not contain a skeleton method for someone else to work on! For more information, please read the [Contributing Guide](https://github.com/BlakeGuilloud/ganon/blob/master/CONTRIBUTING.md).

Thank you so much for your contribution!

**Comment by tomasswood** [comment]
@BlakeGuilloud likewise, I can work on this one as well if you would like, or you can save it for someone else?

**Comment by BlakeGuilloud** [comment]
Go for it @tomasswood !! If you get a few minutes, I'm trying to encourage people to open new Issues for the skeleton methods they create. There is a ISSUE_TEMPLATE already laid out, but if you don't mind filling it out for your new methods after your pull requests go through, it helps me out a ton!

**Comment by tomasswood** [comment]
Too easy, will do it now for the other two!

**Comment by BlakeGuilloud** [comment]
Thanks!!

**Comment by BlakeGuilloud** [comment]
Donezo. Nice work
