### ISSUE TITLE
Something is wrong with our GCD method || test

### ISSUE THREAD

**Issue by BlakeGuilloud** [BlakeGuilloud/ganon#173]
Something is wrong with the GCD function! Not all of the tests are passing. Could use someone to take a look into it and see if it is the test itself that is broken, or if the function could use a refactor.

### Acceptance Criteria:
1. Running `yarn test gcd` results in tests passing.
2. You have written a skeleton method for someone else to work on.
3. You have written tests surrounding your skeleton method.
4. Running `yarn lint` does not print any errors to the console!

### Please include the skeleton of a new method + an accompanying test for someone else to work on at the time of creating a pull request! A pull request will most likely be denied if it does not contain a skeleton method for someone else to work on! For more information, please read the [Contributing Guide](https://github.com/BlakeGuilloud/ganon/blob/master/CONTRIBUTING.md).

Thank you so much for your contribution!

**Comment by hariaakash** [comment]
@BlakeGuilloud I am taking this up

**Comment by BlakeGuilloud** [comment]
Thanks @hariaakash !!

**Comment by BlakeGuilloud** [comment]
Closed! Thanks @hariaakash !!
