### ISSUE TITLE
Fix arrayDifference method

### ISSUE THREAD

**Issue by BlakeGuilloud** [BlakeGuilloud/ganon#178]
There is currently a method called `arrayDifference` that lives in `/lib/arrayDifference.js`.
It is incomplete and needs to be fixed!

### Acceptance Criteria:
1. Running `yarn test arrayDifference` results in tests passing.
2. You have written a skeleton method for someone else to work on.
3. You have written tests surrounding your skeleton method.
4. Running `yarn lint` does not print any errors to the console!

### Please include the skeleton of a new method + an accompanying test for someone else to work on at the time of creating a pull request! A pull request will most likely be denied if it does not contain a skeleton method for someone else to work on! For more information, please read the [Contributing Guide](https://github.com/BlakeGuilloud/ganon/blob/master/CONTRIBUTING.md).

Thank you so much for your contribution!

**Comment by tomasswood** [comment]
@BlakeGuilloud I would like to work on this

**Comment by BlakeGuilloud** [comment]
Hey @tomasswood !! Thanks- I will apply the 'in progress' label. Just remember, for each method you fix, you need to supply a skeleton method for someone else to work on! This is what keeps the project going. Thanks!!

**Comment by tomasswood** [comment]
Will do :)

**Comment by BlakeGuilloud** [comment]
THanks @
