### ISSUE TITLE
Fix Remainder method

### ISSUE THREAD

**Issue by BlakeGuilloud** [BlakeGuilloud/ganon#18]
There is currently a method called `remainder` that lives in `/lib/remainder.js`.
It is incomplete and needs to be fixed!

### Acceptance Criteria:
1. Running `yarn test remainder` results in tests passing.

#### Please include the skeleton of a new method + an accompanying test for someone else to work on at the time of creating a pull request!

**Comment by BlakeGuilloud** [comment]
@maribelduran - Want to take this one on?

**Comment by maribelduran** [comment]
@BlakeGuilloud Yes I'll take it! Thank you!

**Comment by BlakeGuilloud** [comment]
Nice work @maribelduran ! Closing this out.
