### ISSUE TITLE
Fix lowercase method

### ISSUE THREAD

**Issue by BlakeGuilloud** [BlakeGuilloud/ganon#180]
There is currently a method called `lowercase` that lives in `/lib/lowercase.js`.
It is incomplete and needs to be fixed!

### Acceptance Criteria:
1. Running `yarn test lowercase` results in tests passing.
2. You have written a skeleton method for someone else to work on.
3. You have written tests surrounding your skeleton method.
4. Running `yarn lint` does not print any errors to the console!

### Please include the skeleton of a new method + an accompanying test for someone else to work on at the time of creating a pull request! A pull request will most likely be denied if it does not contain a skeleton method for someone else to work on! For more information, please read the [Contributing Guide](https://github.com/BlakeGuilloud/ganon/blob/master/CONTRIBUTING.md).

Thank you so much for your contribution!

**Comment by Wulingoh** [comment]
HI @BlakeGuilloud, 

Happy to tackle this issue. Will add on skeleton method too.

**Comment by BlakeGuilloud** [comment]
You got it @Wulingoh ! Thanks a ton.
