### ISSUE TITLE
Fix mean method

### ISSUE THREAD

**Issue by BlakeGuilloud** [BlakeGuilloud/ganon#181]
There is currently a method called `mean` that lives in `/lib/mean.js`.
It is incomplete and needs to be fixed!

### Acceptance Criteria:
1. Running `yarn test mean` results in tests passing.
2. You have written a skeleton method for someone else to work on.
3. You have written tests surrounding your skeleton method.
4. Running `yarn lint` does not print any errors to the console!

### Please include the skeleton of a new method + an accompanying test for someone else to work on at the time of creating a pull request! A pull request will most likely be denied if it does not contain a skeleton method for someone else to work on! For more information, please read the [Contributing Guide](https://github.com/BlakeGuilloud/ganon/blob/master/CONTRIBUTING.md).

Thank you so much for your contribution!

**Comment by Akin909** [comment]
Hi @BlakeGuilloud, love the idea of this project and would like to contribute since this is open I'd like to work on this if that alright

**Comment by BlakeGuilloud** [comment]
Go for it @Akin909 !! I will apply the in progress label.

**Comment by BlakeGuilloud** [comment]
Hey @Akin909 !! Sorry to do this to you, but 24 hours has passed, and we are going to allow another contributor to resolve this. If you see any available issues you are interested in, please let me know!! Thanks
