### ISSUE TITLE
Fix flattenArray method

### ISSUE THREAD

**Issue by tomasswood** [BlakeGuilloud/ganon#184]
There is currently a method called `flattenArray ` that lives in `/lib/flattenArray.js`.
It is incomplete and needs to be fixed!

### Acceptance Criteria:
1. Running `yarn test flattenArray ` results in tests passing.
2. You have written a skeleton method for someone else to work on.
3. You have written tests surrounding your skeleton method.
4. Running `yarn lint` does not print any errors to the console!

### Please include the skeleton of a new method + an accompanying test for someone else to work on at the time of creating a pull request! A pull request will most likely be denied if it does not contain a skeleton method for someone else to work on! For more information, please read the [Contributing Guide](https://github.com/BlakeGuilloud/ganon/blob/master/CONTRIBUTING.md).

Thank you so much for your contribution!

**Comment by BtheGit** [comment]
I'll take a crack at this.

**Comment by BlakeGuilloud** [comment]
Awesome @BtheGit ! I'll apply the 'in progress' label. This will buy you 24 hours. If you need more time, feel free to reach out and I'll happily oblige! Thanks for your contribution and @BlakeGuilloud me if you have any question.

**Comment by BtheGit** [comment]
Flatten a 2d or a deep nested array? :) I always say go deep or go home.

**Comment by BlakeGuilloud** [comment]
Hah- whatever you think!! If you go deep, you should adjust the tests to make sure and check for any edge cases!

**Comment by BtheGit** [comment]
Then I will write that as a skeleton I suppose instead. Let some other poor fella decide between tail call optimized recursion or uncool loops. ;)

**Comment by BtheGit** [comment]
https://github.com/BlakeGuilloud/ganon/pull/194

**Comment by BtheGit** [comment]
#194 Still learning how to link issues and PRs.

**Comment by BlakeGuilloud** [comment]
No worries @BtheGit !! Thanks for the contrib. If you get a chance, we are trying to encourage our contributors to open up the Issue for their skeleton method. Thanks!

**Comment by BtheGit** [comment]
Yes sir. Good point.
