### ISSUE TITLE
Fix regexReplace method

### ISSUE THREAD

**Issue by tomasswood** [BlakeGuilloud/ganon#185]
There is currently a method called `regexReplace ` that lives in `/lib/regexReplace.js`.
It is incomplete and needs to be fixed!

### Acceptance Criteria:
1. Running `yarn test regexReplace ` results in tests passing.
2. You have written a skeleton method for someone else to work on.
3. You have written tests surrounding your skeleton method.
4. Running `yarn lint` does not print any errors to the console!

### Please include the skeleton of a new method + an accompanying test for someone else to work on at the time of creating a pull request! A pull request will most likely be denied if it does not contain a skeleton method for someone else to work on! For more information, please read the [Contributing Guide](https://github.com/BlakeGuilloud/ganon/blob/master/CONTRIBUTING.md).

Thank you so much for your contribution!

**Comment by buoyantair** [comment]
I will take this!

**Comment by buoyantair** [comment]
I will take this!
