### ISSUE TITLE
Fix arraySum method

### ISSUE THREAD

**Issue by tomasswood** [BlakeGuilloud/ganon#187]
There is currently a method called `arraySum` that lives in `/lib/arraySum.js`.
It is incomplete and needs to be fixed!

### Acceptance Criteria:
1. Running `yarn test arraySum` results in tests passing.
2. You have written a skeleton method for someone else to work on.
3. You have written tests surrounding your skeleton method.
4. Running `yarn lint` does not print any errors to the console!

### Please include the skeleton of a new method + an accompanying test for someone else to work on at the time of creating a pull request! A pull request will most likely be denied if it does not contain a skeleton method for someone else to work on! For more information, please read the [Contributing Guide](https://github.com/BlakeGuilloud/ganon/blob/master/CONTRIBUTING.md).

Thank you so much for your contribution!

**Comment by kyliedale** [comment]
@BlakeGuilloud I would like to work on this!

**Comment by BlakeGuilloud** [comment]
Go for it @kyliedale !! I will apply the 'in progress' label. That buys you 24 hours. If you need more time, feel free to reach out and I'll be happy to oblige! Thanks for contributing!

**Comment by BlakeGuilloud** [comment]
Sorry @kyliedale ! We were trying to clean up some pull requests and someone snuck in an arraySum function. Feel free to look over their implementation and provide improvements or be on the lookout for a new method to work on! Thanks!!
