### ISSUE TITLE
Fix concatenateArray method

### ISSUE THREAD

**Issue by tomasswood** [BlakeGuilloud/ganon#189]
There is currently a method called `concatenateArray` that lives in `/lib/concatenateArray.js`.
It is incomplete and needs to be fixed!

### Acceptance Criteria:
1. Running `yarn test concatenateArray` results in tests passing.
2. You have written a skeleton method for someone else to work on.
3. You have written tests surrounding your skeleton method.
4. Running `yarn lint` does not print any errors to the console!

### Please include the skeleton of a new method + an accompanying test for someone else to work on at the time of creating a pull request! A pull request will most likely be denied if it does not contain a skeleton method for someone else to work on! For more information, please read the [Contributing Guide](https://github.com/BlakeGuilloud/ganon/blob/master/CONTRIBUTING.md).

Thank you so much for your contribution!

**Comment by Y-Selim** [comment]
I will swing a bat at this :bat:

**Comment by BlakeGuilloud** [comment]
:bat: Sounds good @Y-Selim !! I'll put the 'in progress' label on it. This buys you 24 hours. If you feel you need me time, feel free to reach out to me in this thread and we won't remove the In Progress label!! Thanks for contributing.

**Comment by BlakeGuilloud** [comment]
Nice work!
