### ISSUE TITLE
Fix countUpperCase method

### ISSUE THREAD

**Issue by theyselim** [BlakeGuilloud/ganon#193]
There is currently a method called `countUpperCase` that lives in `/lib/countUpperCase.js`.
It is incomplete and needs to be fixed!

### Acceptance Criteria:
1. Running `yarn test countUpperCase` results in tests passing.
2. You have written a skeleton method for someone else to work on.
3. You have written tests surrounding your skeleton method.
4. Running `yarn lint` does not print any errors to the console!

### Please include the skeleton of a new method + an accompanying test for someone else to work on at the time of creating a pull request! A pull request will most likely be denied if it does not contain a skeleton method for someone else to work on! For more information, please read the [Contributing Guide](https://github.com/BlakeGuilloud/ganon/blob/master/CONTRIBUTING.md).

Thank you so much for your contribution!

**Comment by max80713** [comment]
@BlakeGuilloud Can I take this one?

**Comment by BlakeGuilloud** [comment]
Hey @max80713 ! Absolutely. I'll apply the 'in progress' label. That buys you 24 hours- if you need more time feel free to reach out and I'll happily oblige. Thanks for contributing!

**Comment by hyades** [comment]
On it

**Comment by ktilcu** [comment]
@hyades you got it. Same rules as before.
