### ISSUE TITLE
Fix flattenDeepArray method 

### ISSUE THREAD

**Issue by BtheGit** [BlakeGuilloud/ganon#195]
There is currently a method called `flattenDeepArray` that lives in `/lib/flattenDeepArray.js`.
It is incomplete and needs to be fixed!

### Acceptance Criteria:
1. Running `yarn test <methodName>` results in tests passing.
2. You have written a skeleton method for someone else to work on.
3. You have written tests surrounding your skeleton method.
4. Running `yarn lint` does not print any errors to the console!

### Please include the skeleton of a new method + an accompanying test for someone else to work on at the time of creating a pull request! A pull request will most likely be denied if it does not contain a skeleton method for someone else to work on! For more information, please read the [Contributing Guide](https://github.com/BlakeGuilloud/ganon/blob/master/CONTRIBUTING.md).

Thank you so much for your contribution!

**Comment by sherlyc** [comment]
May I?

**Comment by BlakeGuilloud** [comment]
All you @sherlyc !! I will apply this 'in progress' label. This buys you 24 hours! If you need more time, feel free to reach out and I will happily oblige. Thanks for your contribution!!

**Comment by hvarday** [comment]
@BlakeGuilloud 
Is it possible for me to contribute to this issue now?
I might have a solution in mind

**Comment by hvarday** [comment]
I am happy to help, and I have create a new issue wrt to the skeleton I created.

**Comment by sherlyc** [comment]
Argh :(

**Comment by BlakeGuilloud** [comment]
Hey @sherlyc !! So sorry I merged this in! I've been trying my best to keep up with who claims what, but it can be overwhelming sometimes. The net issue that comes up in the project, I will @ mention you and apply the in progress label. I will make sure it doesn't get jumped! Thanks!!
