### ISSUE TITLE
Fix sortByWordLength method

### ISSUE THREAD

**Issue by erinesco** [BlakeGuilloud/ganon#197]
There is currently a method called `sortByWordLength` that lives in `/lib/sortByWordLength.js`.
It is incomplete and needs to be fixed!

### Acceptance Criteria:
1. Running `yarn test sortByWordLength` results in tests passing.
2. You have written a skeleton method for someone else to work on.
3. You have written tests surrounding your skeleton method.
4. Running `yarn lint` does not print any errors to the console!

### Please include the skeleton of a new method + an accompanying test for someone else to work on at the time of creating a pull request! A pull request will most likely be denied if it does not contain a skeleton method for someone else to work on! For more information, please read the [Contributing Guide](https://github.com/BlakeGuilloud/ganon/blob/master/CONTRIBUTING.md).

Thank you so much for your contribution!

**Comment by emanuelcasco** [comment]
@BlakeGuilloud I would like to work on this!

**Comment by BlakeGuilloud** [comment]
Thanks @emanuelcasco !! It's yours. I'll apply the "In Progress" label. This buys you 24 hours. If you need more time, feel free to reach out to me and I will happily oblige. Thanks for your contribution!

**Comment by BlakeGuilloud** [comment]
Thanks !!
