### ISSUE TITLE
Fix the Difference method.

### ISSUE THREAD

**Issue by BlakeGuilloud** [BlakeGuilloud/ganon#2]
There is currently a method called `difference` that lives in `/lib/difference.js`.
It is incomplete and needs to be fixed!

### Acceptance Criteria:
1. Running `yarn test difference` results in tests passing.

#### Please include the skeleton of a new method + an accompanying test for someone else to work on at the time of creating a pull request!

**Comment by hugoduraes** [comment]
Working on this one.

**Comment by BlakeGuilloud** [comment]
Thanks @hugoduraes !
