### ISSUE TITLE
Fix SquareRoot method

### ISSUE THREAD

**Issue by BlakeGuilloud** [BlakeGuilloud/ganon#20]
There is currently a method called `squareRoot` that lives in `/lib/squareRoot.js`.
It is incomplete and needs to be fixed!

### Acceptance Criteria:
1. Running `yarn test squareRoot` results in tests passing.

#### Please include the skeleton of a new method + an accompanying test for someone else to work on at the time of creating a pull request!

**Comment by hugoduraes** [comment]
Dibs

**Comment by smoholkar** [comment]
can I take a look at this ?

**Comment by hugoduraes** [comment]
@smoholkar I've already submitted a PR for this one. But you can pick the new method I've added on this PR! 👍

**Comment by BlakeGuilloud** [comment]
@smoholkar Will you take on https://github.com/BlakeGuilloud/ganon/issues/22 please?
