### ISSUE TITLE
Fix sortAlphabetically function

### ISSUE THREAD

**Issue by emanuelcasco** [BlakeGuilloud/ganon#200]
There is currently a method called `sortAlphabetically` that lives in `/lib/sortAlphabetically.js`.
It is incomplete and needs to be fixed!

### Acceptance Criteria:
1. Running `yarn test sortAlphabetically` results in tests passing.
2. You have written a skeleton method for someone else to work on.
3. You have written tests surrounding your skeleton method.
4. Running `yarn lint` does not print any errors to the console!

### Please include the skeleton of a new method + an accompanying test for someone else to work on at the time of creating a pull request! A pull request will most likely be denied if it does not contain a skeleton method for someone else to work on! For more information, please read the [Contributing Guide](https://github.com/BlakeGuilloud/ganon/blob/master/CONTRIBUTING.md).

Thank you so much for your contribution!

**Comment by micahduron** [comment]
I'd like to give this one a go.

**Comment by BlakeGuilloud** [comment]
Awesome @micahduron !! I will apply the 'in progress' label. This buys you 24 hours. If you feel like you need more time, feel free to reach out and I will happily oblige. Thanks for contributing!

**Comment by ktilcu** [comment]
Thanks @micahduron
