### ISSUE TITLE
Fix countSetBits function

### ISSUE THREAD

**Issue by stillNovice** [BlakeGuilloud/ganon#201]
There is currently a method called `countSetBits` that lives in `/lib/countSetBits.js`.
It is incomplete and needs to be fixed!

### Acceptance Criteria:
1. Running `yarn test countSetBits` results in tests passing.
2. You have written a skeleton method for someone else to work on.
3. You have written tests surrounding your skeleton method.
4. Running `yarn lint` does not print any errors to the console!

### Please include the skeleton of a new method + an accompanying test for someone else to work on at the time of creating a pull request! A pull request will most likely be denied if it does not contain a skeleton method for someone else to work on! For more information, please read the [Contributing Guide](https://github.com/BlakeGuilloud/ganon/blob/master/CONTRIBUTING.md).

Thank you so much for your contribution!

**Comment by dna113p** [comment]
I'll take it!

**Comment by BlakeGuilloud** [comment]
Awesome @dna113p ! I will apply the 'in progress' label. This buys you 24 hours- if you need more time, feel free to reach out and I will happily oblige! Thanks for contributing!

**Comment by buoyantair** [comment]
Can I try this too?

**Comment by BlakeGuilloud** [comment]
@buoyantair ! Let's give @dna113p an opportunity to resolve the requested changes in his pull request.

This goes for all methods that currently exist in the project, but feel free to push up improvements, more documentation, or a more inclusive test suite after his pull request is merged in! Issue #69 requests this :)

**Comment by ktilcu** [comment]
@buoyantair you may like tackling the composition functions. I know `flow` is taken but `compose` and `pipe` are probably still available.

**Comment by buoyantair** [comment]
@ktilcu @BlakeGuilloud Instead I'll add a few functions :P
