### ISSUE TITLE
Fix vowelCount method

### ISSUE THREAD

**Issue by cjhaviland** [BlakeGuilloud/ganon#216]
There is currently a method called `vowelCount` that lives in `/lib/vowelCount.js`.
It is incomplete and needs to be fixed!

### Acceptance Criteria:
1. Running `yarn test vowelCount` results in tests passing.
2. You have written a skeleton method for someone else to work on.
3. You have written tests surrounding your skeleton method.
4. Running `yarn lint` does not print any errors to the console!

### Please include the skeleton of a new method + an accompanying test for someone else to work on at the time of creating a pull request! A pull request will most likely be denied if it does not contain a skeleton method for someone else to work on! For more information, please read the [Contributing Guide](https://github.com/BlakeGuilloud/ganon/blob/master/CONTRIBUTING.md).

Thank you so much for your contribution!

**Comment by WilliamStephens** [comment]
Hey is it okay if I take this one?

**Comment by BlakeGuilloud** [comment]
It's yours @WilliamStephens ! Thanks for your contribution.

**Comment by BlakeGuilloud** [comment]
oh no @WilliamStephens !! Sorry to tell you but someone got to it before you, maybe @ruskakimov will make a new Issue describing the Skeleton method he introduced for you ;)

**Comment by ktilcu** [comment]
@WilliamStephens sorry about that. I missed that you had claimed this one. We did make #220 if you wanna tackle that though!

**Comment by WilliamStephens** [comment]
Yea it's no big deal!

**Comment by MahendraTennakoon** [comment]
@WilliamStephens I started working on #220 without coming here first. You can take it if you want.

**Comment by WilliamStephens** [comment]
@MahendraTennakoon you can go ahead

**Comment by ktilcu** [comment]
@WilliamStephens I will make few more issues here soon. We really want you to hit the hacktoberfest 4 PRs and contribute to some open source projects so hang around and we'll get you a good one!
