### ISSUE TITLE
Fix Increment method

### ISSUE THREAD

**Issue by BlakeGuilloud** [BlakeGuilloud/ganon#22]
There is currently a method called `increment` that lives in `/lib/increment.js`.
It is incomplete and needs to be fixed!

### Acceptance Criteria:
1. Running `yarn test increment` results in tests passing.

#### Please include the skeleton of a new method + an accompanying test for someone else to work on at the time of creating a pull request!

**Comment by BlakeGuilloud** [comment]
@smoholkar Feel free to claim this one if you like!

**Comment by smoholkar** [comment]
sure I'll take it @BlakeGuilloud

**Comment by BlakeGuilloud** [comment]
Great, thanks!!
