### ISSUE TITLE
Fix areaOfCircle function

### ISSUE THREAD

**Issue by stillNovice** [BlakeGuilloud/ganon#221]
There is currently a method called `areaOfCircle` that lives in `/lib/areaOfCircle.js`.
It is incomplete and needs to be fixed!

### Acceptance Criteria:
1. Running `yarn test areaOfCircle` results in tests passing.
2. You have written a skeleton method for someone else to work on.
3. You have written tests surrounding your skeleton method.
4. Running `yarn lint` does not print any errors to the console!

### Please include the skeleton of a new method + an accompanying test for someone else to work on at the time of creating a pull request! A pull request will most likely be denied if it does not contain a skeleton method for someone else to work on! For more information, please read the [Contributing Guide](https://github.com/BlakeGuilloud/ganon/blob/master/CONTRIBUTING.md).

Thank you so much for your contribution!

**Comment by buoyantair** [comment]
I'll take this!

**Comment by BlakeGuilloud** [comment]
@buoyantair I got an email saying you were interested in this but your comment isn't showing up for me in the thread.

**Comment by buoyantair** [comment]
@BlakeGuilloud Yeah I will do this.

**Comment by BlakeGuilloud** [comment]
Cool deal @buoyantair ! I've applied the 'in progress' label. Also- you snuck one by me in your last PR, but if you could, please try to include at least one new Skeleton Method for someone else to work on. This helps the project continue to grow! Thanks for your contributions!!

**Comment by buoyantair** [comment]
What do you mean "snuck one by you?"

**Comment by BlakeGuilloud** [comment]
Hah sorry I didn't mean to sound rude! We just ask that for each solution a contributor provides, that they also create a new method for someone else to work on.

**Comment by BlakeGuilloud** [comment]
Oh whoops.. I see that may have been my fault per the convo in #209 ! I should have caught that. My bad!!

**Comment by buoyantair** [comment]
@BlakeGuilloud I see! I should have read the Contributing Guides 😅 😆 Let me add in some new methods I'd like to see implemented in this project!

**Comment by buoyantair** [comment]
@BlakeGuilloud @ktilcu I have a weird situation here.
I get this weird error when I run "yarn test areaOfCircle"

```
/home/ubuntu/workspace/.c9/metadata/workspace/test/areaOfCircle.test.js: Unexpected token, expected ; (1:9)
      > 1 | {"filter":false,"title":"areaOfCircle.test.js","tooltip":"/test/areaOfCircle.test.js","undoManager":{"mark":22,"position":22,"stack":[[{"start":{"row":0,"column":42},"end":{"row":0,"column":43},"action":"remove","lines":[";"],"id":2}],[{"start":{"row":0,"column":42},"end":{"row":0,"column":43},"action":"insert","lines":[";"],"id":3}],[{"start":{"row":0,"column":0},"end":{"row":0,"column":43},"action":"remove","lines":["const { areaOfCircle } = require(\"../lib\");"],"id":7},{"start":{"row":0,"column":0},"end":{"row":0,"column":34},"action":"insert","lines":["const { and } = require(\"../lib\");"]}],[{"start":{"row":0,"column":8},"end":{"row":0,"column":11},"action":"remove","lines":["and"],"id":8},{"start":{"row":0,"column":8},"end":{"row":0,"column":9},"action":"insert","lines":["a"]}],[{"start":{"row":0,"column":9},"end":{"row":0,"column":10},"action":"insert","lines":["c"],"id":9}],[{"start":{"row":0,"column":10},"end":{"row":0,"column":11},"action":"insert","lines":["r"],"id":10}],[{"start":{"row":0,"column":11},"end":{"row":0,"column":12},"action":"insert","lines":["e"],"id":11}],[{"start":{"row":0,"column":12},"end":{"row":0,"column":13},"action":"insert","lines":["a"],"id":12}],[{"start":{"row":0,"column":12},"end":{"row":0,"column":13},"action":"remove","lines":["a"],"id":13}],[{"start":{"row":0,"column":11},"end":{"row":0,"column":12},"action":"remove","lines":["e"],"id":14}],[{"start":{"row":0,"column":10},"end":{"row":0,"column":11},"action":"remove","lines":["r"],"id":15}],[{"start":{"row":0,"column":9},"end":{"row":0,"column":10},"action":"remove","lines":["c"],"id":16}],[{"start":{"row":0,"column":9},"end":{"row":0,"column":10},"action":"insert","lines":["r"],"id":17}],[{"start":{"row":0,"column":10},"end":{"row":0,"column":11},"action":"insert","lines":["e"],"id":18}],[{"start":{"row":0,"column":11},"end":{"row":0,"column":12},"action":"insert","lines":["a"],"id":19}],[{"start":{"row":0,"column":12},"end":{"row":0,"column":13},"action":"insert","lines":["O"],"id":20}],[{"start":{"row":0,"column":13},"end":{"row":0,"column":14},"action":"insert","lines":["f"],"id":21}],[{"start":{"row":0,"column":14},"end":{"row":0,"column":15},"action":"insert","lines":["C"],"id":22}],[{"start":{"row":0,"column":15},"end":{"row":0,"column":16},"action":"insert","lines":["i"],"id":23}],[{"start":{"row":0,"column":16},"end":{"row":0,"column":17},"action":"insert","lines":["r"],"id":24}],[{"start":{"row":0,"column":17},"end":{"row":0,"column":18},"action":"insert","lines":["c"],"id":25}],[{"start":{"row":0,"column":18},"end":{"row":0,"column":19},"action":"insert","lines":["l"],"id":26}],[{"start":{"row":0,"column":19},"end":{"row":0,"column":20},"action":"insert","lines":["e"],"id":27}],[{"start":{"row":0,"column":42},"end":{"row":0,"column":43},"action":"insert","lines":[";"],"id":29}],[{"start":{"row":0,"column":42},"end":{"row":0,"column":43},"action":"remove","lines":[";"],"id":28}]]},"ace":{"folds":[],"scrolltop":0,"scrollleft":0,"selection":{"start":{"row":0,"column":42},"end":{"row":0,"column":43},"isBackwards":false},"options":{"guessTabSize":true,"useWrapMode":false,"wrapToView":true},"firstLineState":0},"timestamp":1508562752837,"hash":"8bb7acb2296d868e77a156b12be5f20a5661228b"}
```

This is the source

areaOfCircle.js
```
/**
 * Write a function that return a floating value representing the area of a circle with the given radius as input. 
 * The returned value must be equal to the expected value with a precision of 4 decimal digits. Don't worry about the measuring unit.
 * @param {Number} radius
 * @return {Number} possibly a floating point value.
**/
function areaOfCircle (radius){
  return Math.PI * radius * radius;
}
module.exports = areaOfCircle;
```

areaOfCircle.test.js
```
const { areaOfCircle } = require("../lib");

describe("areaOfCircle", () => {
  test("area of circle with radius 7 is 153.9380400", () => {
    expect(areaOfCircle(7)).toBeCloseTo(153.9380400, 4);
  });

  test("area of circle with radius 125 is 49087.3852123", () => {
    expect(areaOfCircle(125)).toBeCloseTo(49087.38521230, 4);
  });

  test("area of circle with radius 0.789 is 1.95570740", () => {
    expect(areaOfCircle(0.789)).toBeCloseTo(1.95570740, 4);
  });

  test("area of circle with radius 0 is 0.000000", () => {
    expect(areaOfCircle(0)).toBeCloseTo(0.000000, 4);
  });

  test("area of circle with radius 5827 is 106669413.906909", () => {
    expect(areaOfCircle(5827)).toBeCloseTo(106669413.906909, 4);
  });
});
```

**Comment by BlakeGuilloud** [comment]
Hey @buoyantair ! I copy and pasted exactly what you have and ran `yarn test areaOfCircle` and received the following output:

![image](https://user-images.githubusercontent.com/14660993/31848369-4a8efede-b5ff-11e7-9eb2-5387d021fcd9.png)

Can you try running a different test and confirm that you issue is isolated to this method?

**Comment by buoyantair** [comment]
@BlakeGuilloud Sure! 1 sec

**Comment by buoyantair** [comment]
@BlakeGuilloud Yes I'm getting the same kind of error with different test files... :/

**Comment by buoyantair** [comment]
@BlakeGuilloud Wait, it passes with some other files. Only a couple of files are effected.

**Comment by BlakeGuilloud** [comment]
Hmmm. I know this sounds silly, but try deleting your `node_modules` and running a fresh `yarn` to install all of our dependencies. It **shouldn't** affect anything, but worth a shot :)

I'd love to help you resolve this, but I cannot reproduce this error locally, nor in my Travis CI config. It sounds like it is isolated to your environment. The `and` method is passing fine for me as well.

**Comment by BlakeGuilloud** [comment]
@buoyantair (sorry forgot to tag you)

**Comment by BlakeGuilloud** [comment]
Out of curiosity- what version of NodeJS are you running?

**Comment by buoyantair** [comment]
@BlakeGuilloud 8.7... 
npm - 5.4.2

**Comment by buoyantair** [comment]
@BlakeGuilloud You can give me your c9.io username and I'll invite you to my workspace.

**Comment by BlakeGuilloud** [comment]
Hey @buoyantair ! Did you get your issue resolved? I'm curious what you found out.

**Comment by buoyantair** [comment]
@BlakeGuilloud I referenced it... #286. AS for the issue, I'm not aware of it, It worked after a few hours of recloning, adjusting and testing etc...
