### ISSUE TITLE
Implement `log` - Natural logarithm

### ISSUE THREAD

**Issue by hariaakash** [BlakeGuilloud/ganon#223]
There is currently a method called `log` that lives in `/lib/log.js`.
It is incomplete and needs to be fixed!

### Acceptance Criteria:
1. Running `yarn test log` results in tests passing.
2. You have written a skeleton method for someone else to work on.
3. You have written tests surrounding your skeleton method.
4. Running `yarn lint` does not print any errors to the console!

### Please include the skeleton of a new method + an accompanying test for someone else to work on at the time of creating a pull request! A pull request will most likely be denied if it does not contain a skeleton method for someone else to work on! For more information, please read the [Contributing Guide](https://github.com/BlakeGuilloud/ganon/blob/master/CONTRIBUTING.md).

Thank you so much for your contribution!

**Comment by stillNovice** [comment]
I am taking this one

**Comment by BlakeGuilloud** [comment]
Cool deal @stillNovice ! Marking as 'in progress' - you know you drill ⚡️

**Comment by BlakeGuilloud** [comment]
Donezo

**Comment by hariaakash** [comment]
@BlakeGuilloud can you change the label?
