### ISSUE TITLE
Fix convertCelsiusToKelvin method

### ISSUE THREAD

**Issue by damjanh** [BlakeGuilloud/ganon#234]
There is currently a method called `convertCelsiusToKelvin` that lives in `/lib/convertCelsiusToKelvin.js`.
It is incomplete and needs to be fixed!

### Acceptance Criteria:
1. Running `yarn test convertCelsiusToKelvin` results in tests passing.
2. You have written a skeleton method for someone else to work on.
3. You have written tests surrounding your skeleton method.
4. Running `yarn lint` does not print any errors to the console!

### Please include the skeleton of a new method + an accompanying test for someone else to work on at the time of creating a pull request! A pull request will most likely be denied if it does not contain a skeleton method for someone else to work on! For more information, please read the [Contributing Guide](https://github.com/BlakeGuilloud/ganon/blob/master/CONTRIBUTING.md).

Thank you so much for your contribution!

**Comment by itsresool** [comment]
@BlakeGuilloud I would like to work on this

**Comment by ktilcu** [comment]
You got it! This gives you 24 hours to get in a PR.

**Comment by kuldeepkeshwar** [comment]
@itsresool @damjanh @ktilcu let me know if i can start

**Comment by BlakeGuilloud** [comment]
Hey @kuldeepkeshwar ! Thanks for your interest! We try to give all of our contributors a 24 hour window to complete an issue. If this issue becomes available again, I'll @ mention you! Keep an eye out for new Issues or old ones that do not have an 'in progress' label applied to them.

Thanks!!
