### ISSUE TITLE
Fix convertMileToKilometer function

### ISSUE THREAD

**Issue by itsresool** [BlakeGuilloud/ganon#239]
There is currently a method called `convertMileToKilometer` that lives in `/lib/convertMileToKilometer.js`.
It is incomplete and needs to be fixed!

### Acceptance Criteria:
1. Running `yarn test convertMileToKilometer` results in tests passing.
2. You have written a skeleton method for someone else to work on.
3. You have written tests surrounding your skeleton method.
4. Running `yarn lint` does not print any errors to the console!
5. Additional AC- expand the test suite of `convertMileToKilometer.test.js` to account for potential edge cases.

### Please include the skeleton of a new method + an accompanying test for someone else to work on at the time of creating a pull request! A pull request will most likely be denied if it does not contain a skeleton method for someone else to work on! For more information, please read the [Contributing Guide](https://github.com/BlakeGuilloud/ganon/blob/master/CONTRIBUTING.md).

Thank you so much for your contribution!

**Comment by JEpifanio90** [comment]
@BlakeGuilloud I would like to work on this!

**Comment by BlakeGuilloud** [comment]
Awesome @JEpifanio90 ! I'll mark it as 'in progress'. This buys you 24 hours. If you need additional time, feel free to reach out! Thanks for your contribution!!

**Comment by JEpifanio90** [comment]
Annnd it's done!

**Comment by BlakeGuilloud** [comment]
hey @JEpifanio90 ! I requested a few minor updates to your PR. Awesome job though!

**Comment by JEpifanio90** [comment]
Sure thing! Thanks 👍

**Comment by BlakeGuilloud** [comment]
Great work :)
