### ISSUE TITLE
Fix arrayMin 

### ISSUE THREAD

**Issue by BlakeGuilloud** [BlakeGuilloud/ganon#241]
There is currently a method called `arrayMin` that lives in `/lib/arrayMin.js`.
It is incomplete and needs to be fixed!

### Acceptance Criteria:
1. Running `yarn test arrayMin` results in tests passing.
2. You have written a skeleton method for someone else to work on.
3. You have written tests surrounding your skeleton method.
4. Running `yarn lint` does not print any errors to the console!
5. Optional: write one or two more tests surrounding the method you are solving to account for potential edge cases.

### Please include the skeleton of a new method + an accompanying test for someone else to work on at the time of creating a pull request! A pull request will most likely be denied if it does not contain a skeleton method for someone else to work on! For more information, please read the [Contributing Guide](https://github.com/BlakeGuilloud/ganon/blob/master/CONTRIBUTING.md).

Thank you so much for your contribution!

**Comment by NamanArora** [comment]
I would like to work upon this!

**Comment by BlakeGuilloud** [comment]
Great @NamanArora ! It's yours. I'll apply the 'in progress' label. That buys you 24 hours. Feel free to reach out if you need more time. Thanks!

**Comment by BlakeGuilloud** [comment]
Boom. Nice work
