### ISSUE TITLE
Fix deleteProp

### ISSUE THREAD

**Issue by BlakeGuilloud** [BlakeGuilloud/ganon#242]
There is currently a method called `deleteProp` that lives in `/lib/deleteProp.js`.
It is incomplete and needs to be fixed!

### Acceptance Criteria:
1. Running `yarn test deleteProp` results in tests passing.
2. You have written a skeleton method for someone else to work on.
3. You have written tests surrounding your skeleton method.
4. Running `yarn lint` does not print any errors to the console!
5. Optional: write one or two more tests surrounding the method you are solving to account for potential edge cases.

### Please include the skeleton of a new method + an accompanying test for someone else to work on at the time of creating a pull request! A pull request will most likely be denied if it does not contain a skeleton method for someone else to work on! For more information, please read the [Contributing Guide](https://github.com/BlakeGuilloud/ganon/blob/master/CONTRIBUTING.md).

Thank you so much for your contribution!

**Comment by ShoulderKarlsson** [comment]
I would like to work on this one if possible.

**Comment by ktilcu** [comment]
You got it @shoulderkarlsson

**Comment by ShoulderKarlsson** [comment]
Question regarding method skeleton. Should I come up with a method to write skeleton code for or should this be taken from the issues?

**Comment by BlakeGuilloud** [comment]
You come up with a method and write tests for it, but leave the business logic for someone else. It should be something that does not exist in the project yet, nor in the issues. After your PR goes through, we are encouraging our contributors to create a new Issue for their skeleton method so someone else can work on it.

**Comment by BlakeGuilloud** [comment]
Noice!
