### ISSUE TITLE
Refactor flattenNestedObject method.

### ISSUE THREAD

**Issue by BlakeGuilloud** [BlakeGuilloud/ganon#250]
There is currently a method called `flattenNestedObject ` that lives in `/lib/flattenNestedObject.js`.

While this method is very well written, it creates several methods that could be broken out utilized elsewhere in the project! In a similar manner that the `lib/flattenNestedObject.js` file requires 'flattenArray', it should also:

1. require("hasNestedProperties")
2. require("getKeyValuePairs")
3. require("isObject")

While the naming convention of these functions makes sense to the isolated scope of the `flattenNestedObject` method, feel free to take liberty in renaming them where you see fit.

Since we are creating 3 new free-standing methods, there should also be 3 new test suites surrounding them.

### Acceptance Criteria:
1. There are at least 6 new files introduced - one for each method, and a test to accompany each method.
2. Running `yarn test <methodName>` results in tests passing for flattenNestedObject, hasNestedProperties, getKeyValuePairs, and isObject.
3. You have written tests for `hasNestedProperties`, `getKeyValuePairs`, and `isObject`
4. Running `yarn lint` does not print any errors to the console!
5. Optional: write a new skeleton method for someone else to work on.

**Comment by indirap** [comment]
Hey, I'd love to take this on!

**Comment by BlakeGuilloud** [comment]
Cool @indirap !! Go for it. I'll apply the 'in progress' label. This buys you 24 hours. If you need more time, feel free to reach out and I'll happily oblige! Good luck and thanks for your contribution!!

**Comment by indirap** [comment]
All done now! 🙂

**Comment by BlakeGuilloud** [comment]
Boom. Freakin' awesome job! Thanks
