### ISSUE TITLE
Fix rotateArray function

### ISSUE THREAD

**Issue by micahduron** [BlakeGuilloud/ganon#257]
There is currently a method called `rotateArray` that lives in `/lib/rotateArray.js`.
It is incomplete and needs to be fixed!

### Acceptance Criteria:
1. Running `yarn test rotateArray` results in tests passing.
2. You have written a skeleton method for someone else to work on.
3. You have written tests surrounding your skeleton method.
4. Running `yarn lint` does not print any errors to the console!
5. Optional: write one or two more tests surrounding the method you are solving to account for potential edge cases.

### Please include the skeleton of a new method + an accompanying test for someone else to work on at the time of creating a pull request! A pull request will most likely be denied if it does not contain a skeleton method for someone else to work on! For more information, please read the [Contributing Guide](https://github.com/BlakeGuilloud/ganon/blob/master/CONTRIBUTING.md).

Thank you so much for your contribution!

**Comment by domosapien** [comment]
Sorry for doing this slightly out of order, but
@BlakeGuilloud I would like to work on this :)

**Comment by ktilcu** [comment]
you got it! I'll review.

**Comment by BlakeGuilloud** [comment]
Hey @domosapien ! Looks like your pull requests are missing Skeleton Methods for other people to work on. If you don't mind following the CONTRIBUTING.md, we require all pull requests to contain a problem for someone else to work on. This ensures the project continues to grow!  Thanks for your contributions- looking forward to getting your work in!

**Comment by domosapien** [comment]
Ok, I misunderstood what that meant. I'll add them now.

**Comment by BlakeGuilloud** [comment]
Nice work! Thanks
