### ISSUE TITLE
Fix Contain method

### ISSUE THREAD

**Issue by BlakeGuilloud** [BlakeGuilloud/ganon#26]
There is currently a method called `contain` that lives in `/lib/contain.js`.
It is incomplete and needs to be fixed!

### Acceptance Criteria:
1. Running `yarn test contain` results in tests passing.

#### Please include the skeleton of a new method + an accompanying test for someone else to work on at the time of creating a pull request!

**Comment by ncaron** [comment]
I'll take a shot at this.

**Comment by BlakeGuilloud** [comment]
All yours @ncaron ! Thanks. Just be sure to write something for someone else to take on when you finish the contain issue!!

**Comment by BlakeGuilloud** [comment]
Resolved.
