### ISSUE TITLE
Fix asciiToString method

### ISSUE THREAD

**Issue by N0V0S** [BlakeGuilloud/ganon#261]
There is currently a method called `asciiToString` that lives in `/lib/asciiToString.js`.
It is incomplete and needs to be fixed!

### Acceptance Criteria:
1. Running `yarn test asciiToString` results in tests passing.
2. You have written a skeleton method for someone else to work on.
3. You have written tests surrounding your skeleton method.
4. Running `yarn lint` does not print any errors to the console!
5. Optional: write one or two more tests surrounding the method you are solving to account for potential edge cases.

### Please include the skeleton of a new method + an accompanying test for someone else to work on at the time of creating a pull request! A pull request will most likely be denied if it does not contain a skeleton method for someone else to work on! For more information, please read the [Contributing Guide](https://github.com/BlakeGuilloud/ganon/blob/master/CONTRIBUTING.md).

Thank you so much for your contribution!

**Comment by domosapien** [comment]
@BlakeGuilloud I would like to work on this

**Comment by BlakeGuilloud** [comment]
Hey @domosapien. Do you mind resolving the requested changes in your existing PRs first? Thanks!

**Comment by pthomas931** [comment]
@BlakeGuilloud Perhaps I can attempt in the mean while?

**Comment by BlakeGuilloud** [comment]
Hey @pthomas931 ! I'm going to let @domosapien take this one, but if you want to look into: https://github.com/BlakeGuilloud/ganon/issues/264 I have already applied the 'in progress' label for you. If you feel up to it, just let me know and i'll leave it applied! Thanks!!
