### ISSUE TITLE
Fix asciiCompression function

### ISSUE THREAD

**Issue by domosapien** [BlakeGuilloud/ganon#265]
There is currently a method called `asciiCompression` that lives in `/lib/asciiCompression.js`.
It is incomplete and needs to be fixed!

### Acceptance Criteria:
1. Running `yarn test asciiCompression` results in tests passing.
2. You have written a skeleton method for someone else to work on.
3. You have written tests surrounding your skeleton method.
4. Running `yarn lint` does not print any errors to the console!
5. Optional: write one or two more tests surrounding the method you are solving to account for potential edge cases.

### Please include the skeleton of a new method + an accompanying test for someone else to work on at the time of creating a pull request! A pull request will most likely be denied if it does not contain a skeleton method for someone else to work on! For more information, please read the [Contributing Guide](https://github.com/BlakeGuilloud/ganon/blob/master/CONTRIBUTING.md).

Thank you so much for your contribution!

**Comment by BlakeGuilloud** [comment]
@sherlyc Are you interested in this method? I'm going to apply the 'in progress' label for now. If you will please @ mention me in this thread, I will leave it applied for 24 hours, otherwise I'll put it up for grabs. Thanks !! Sorry about the other issue

**Comment by sherlyc** [comment]
@BlakeGuilloud 
ok i will work on this, thanks man!

**Comment by BlakeGuilloud** [comment]
NP- it's yours. You've got 24 hours! Let me know if you need more time and I will happily oblige.
