### ISSUE TITLE
Fix Factorial method

### ISSUE THREAD

**Issue by BlakeGuilloud** [BlakeGuilloud/ganon#27]
There is currently a method called `factorial` that lives in `/lib/factorial.js`.
It is incomplete and needs to be fixed!

### Acceptance Criteria:
1. Running `yarn test factorial` results in tests passing.

#### Please include the skeleton of a new method + an accompanying test for someone else to work on at the time of creating a pull request!

**Comment by iamnapo** [comment]
I'll work on it 😃

**Comment by BlakeGuilloud** [comment]
Great thanks @iamnapo ! It's all yours. Just be sure to create a new skeleton method for someone else to work on!
