### ISSUE TITLE
Fix arrayFill function

### ISSUE THREAD

**Issue by amoradi** [BlakeGuilloud/ganon#274]
There is currently a method called `arrayFill` that lives in `/lib/arrayFill.js`.
It is incomplete and needs to be fixed!

### Acceptance Criteria:
1. Running `yarn test arrayFill` results in tests passing.
2. You have written a skeleton method for someone else to work on.
3. You have written tests surrounding your skeleton method.
4. Running `yarn lint` does not print any errors to the console!
5. Optional: write one or two more tests surrounding the method you are solving to account for potential edge cases.

### Please include the skeleton of a new method + an accompanying test for someone else to work on at the time of creating a pull request! A pull request will most likely be denied if it does not contain a skeleton method for someone else to work on! For more information, please read the [Contributing Guide](https://github.com/BlakeGuilloud/ganon/blob/master/CONTRIBUTING.md).

Thank you so much for your contribution!

**Comment by Galleria** [comment]
I'll do this issue :)

**Comment by BlakeGuilloud** [comment]
Awesome @Galleria ! It is yours. I will apply the 'in progress' label to it- that buys you 24 hours! If you feel like you need more time, feel free to reach out and I will happily oblige. Please make sure to include a "Skeleton Method" when you make a pull request to resolve this issue. Thanks and good luck!!

**Comment by BlakeGuilloud** [comment]
Thanks!
