### ISSUE TITLE
Beef up documentation for our Sum and Difference methods

### ISSUE THREAD

**Issue by BlakeGuilloud** [BlakeGuilloud/ganon#279]
There are currently two methods: `sum` and `difference` that are lacking in proper documentation. We are trying to move towards following the standard laid out in [jsdoc](http://usejsdoc.org/); however, these methods (along with many others) are lacking in this convention. For a good example of what documentation should look like, take a look at `lib/startsWith.js` or `lib/zip.js`.

Feel free to beef up the methods themselves, introduce a new method, and / or introduce a new Skeleton Method for someone else to resolve.

Thanks for your contribution!

**Comment by amoradi** [comment]
@BlakeGuilloud I'll give it a shot.

Any word on `props` we want from jsdoc`?

**Comment by BlakeGuilloud** [comment]
Hey thanks man! I know it's not the most exciting of tasks, so feel free to add some new methods in there if you would like! Thanks
