### ISSUE TITLE
Implement a linter to enforce code style

### ISSUE THREAD

**Issue by BlakeGuilloud** [BlakeGuilloud/ganon#28]
We need to bring in a tool like [eslint](https://eslint.org/) to make sure we maintain a certain style for this codebase. I'd like the initial implementation to be very basic and discussions surrounding rules can take place in this issue.

### Acceptance Criteria:
1. Running `yarn lint` should lint the codebase and print errors where they are found.

**Comment by ncaron** [comment]
I created a PR for basic linting, forgot to mention here I was working on it 😅

**Comment by BlakeGuilloud** [comment]
cool deal @ncaron I'll take a look at it now!
