### ISSUE TITLE
Commutative & Associative functions should be left variadic

### ISSUE THREAD

**Issue by babhishek21** [BlakeGuilloud/ganon#283]
Case in point: there is currently a method called `sum` that lives in `/lib/sum.js`.

Summation is commutative and associative. Thus the result of this operation on two operands can be extended to multiple operands. Hence, the `sum` method should accept variadic arguments. 

Same goes for `product`, `and` and `xor` methods.

Let's put this up for discussion. I'd like to work on this.

### Acceptance Criteria:
1. Running `yarn test <methodName>` results in tests passing.
2. You have written a skeleton method for someone else to work on.
3. You have written tests surrounding your skeleton method.
4. Running `yarn lint` does not print any errors to the console!
5. Optional: write one or two more tests surrounding the method you are solving to account for potential edge cases.

### Please include the skeleton of a new method + an accompanying test for someone else to work on at the time of creating a pull request! A pull request will most likely be denied if it does not contain a skeleton method for someone else to work on! For more information, please read the [Contributing Guide](https://github.com/BlakeGuilloud/ganon/blob/master/CONTRIBUTING.md).

Thank you so much for your contribution!

**Comment by mcmilo** [comment]
@BlakeGuilloud I would like to work on this

**Comment by ktilcu** [comment]
I feel like they would work best by passing in a list. @BlakeGuilloud @andreasgruenh What do you guys think?

**Comment by amoradi** [comment]
@ktilcu It looks like lodash [does just that](https://lodash.com/docs/4.17.4#sum) .

**Comment by ktilcu** [comment]
@amoradi Please implement this if you'd like. Thanks for bringing it up! You can take one or more of those methods. If you leave some then I think we have another interested party. I'll mark this as in progress for now.

**Comment by BlakeGuilloud** [comment]
I agree. Thanks @babhishek21 !! Take it and run ⚡️

**Comment by babhishek21** [comment]
Passing in a list might be not be the best idea. We don't have documentation of the methods yet, so it might get confusing. I feel that a variadic method would come more easily:

```
sum(3, 5); // This works!
>> 8
sum(3, 5, 7); //This works too!
>> 15
sum(3.0, 1.5, -2.5, 0, 0, 1); // This works too!
>> 3
```

Additionally for a list, that method would be more aptly named `sumOfArray`. I already see a few "array" oriented methods implemented. Maybe mixing these isn't a good idea.

It is also entirely possible that `sum()` accepts lists or numeric types or a mix of both. Say:

```
sum(3, 5); // This works!
>> 8
sum([3, 5]); //This works too!
>> 8
sum([3, 5], 7); // This works too!
>> 15
sum([3, 5], 7, [9]); // This works too!
>> 24
sum(3, 5, [7, 9]); // This works too!
>> 24

sum([3, 5, 7, 9]); // This works too!
>> 24
sum([3]); // This works too!
>> 3

sum(3); // This doesn't!
```
Too complex? Let me know.

**Comment by babhishek21** [comment]
@ktilcu I'm sorry I don't understand. Perhaps an example? 😅

**Comment by airondumael** [comment]
@babhishek21 
I'll try to give an example `const add5 = curry(sum)(5)` won't work if it's variadic because [curry](https://github.com/BlakeGuilloud/ganon/blob/master/lib/curry.js#L17) by checking the functions length which is how many arguments it have when we define it. 
if we define sum like this `const sum = (...args) => {}` then `sum.length === 0`.

**Comment by babhishek21** [comment]
@ktilcu I see your point. But we can always use [partials](https://stackoverflow.com/questions/42164000/how-to-reconcile-javascript-with-currying-and-function-composition/42164779#42164779).

**Comment by ktilcu** [comment]
I won't block any changes to these functions. Variadic add is better than what we have ;)

**Comment by babhishek21** [comment]
PR #365 is ready. I raised issues #366 and #367 to make sure some other qualifying functions are also made variadic. Cheers 🍺

**Comment by ktilcu** [comment]
Looks like those issues are closed @babhishek21 . Should we close this up now?

**Comment by babhishek21** [comment]
Hmm, I think a few more eligible methods might be left. I guess, we can close this for now and refer this as and when we cook up new issues that are similar.
