### ISSUE TITLE
Fix Uniq function

### ISSUE THREAD

**Issue by frankrobert** [BlakeGuilloud/ganon#297]
There is currently a method called `uniq` that lives in `/lib/uniq.js`.
It is incomplete and needs to be fixed!

### Acceptance Criteria:
1. Running `yarn test uniq` results in tests passing.
2. You have written a skeleton method for someone else to work on.
3. You have written tests surrounding your skeleton method.
4. Running `yarn lint` does not print any errors to the console!
5. Optional: write one or two more tests surrounding the method you are solving to account for potential edge cases.

### Please include the skeleton of a new method + an accompanying test for someone else to work on at the time of creating a pull request! A pull request will most likely be denied if it does not contain a skeleton method for someone else to work on! For more information, please read the [Contributing Guide](https://github.com/BlakeGuilloud/ganon/blob/master/CONTRIBUTING.md).

Thank you so much for your contribution!

**Comment by Ampretuzo** [comment]
I'll do it

**Comment by BlakeGuilloud** [comment]
Thanks @Ampretuzo !

**Comment by yoavmmn** [comment]
@BlakeGuilloud should I open a PR if @Ampretuzo is working on it?
I have fixed the broken tests and wrote the code for `uniq` function.

**Comment by Ampretuzo** [comment]
@yoavmmn its ok open PR. I'll do another one.

**Comment by yoavmmn** [comment]
@Ampretuzo Thanks 👍

**Comment by BlakeGuilloud** [comment]
Sounds like it @yoavmmn ! Just please make sure to include a new skeleton method in your pull request.
