### ISSUE TITLE
Fix the Quotient method

### ISSUE THREAD

**Issue by BlakeGuilloud** [BlakeGuilloud/ganon#3]
There is currently a method called `Quotient` that lives in `/lib/quotient.js`.
It is incomplete and needs to be fixed!

### Acceptance Criteria:
1. Running `yarn test quotient` results in tests passing.

#### Please include the skeleton of a new method + an accompanying test for someone else to work on at the time of creating a pull request!

**Comment by brycereynolds** [comment]
Just added a PR for this ticket https://github.com/BlakeGuilloud/ganon/pull/6

**Comment by BlakeGuilloud** [comment]
Cool @brycereynolds ! If you still want to work on this, the quotient is all yours! Just make sure you push up something for someone else!

**Comment by brycereynolds** [comment]
K will push momentarily...

**Comment by brycereynolds** [comment]
Ok added xor method...

https://github.com/BlakeGuilloud/ganon/pull/11
