### ISSUE TITLE
Use CI for testing and validating PRs

### ISSUE THREAD

**Issue by akram-rameez** [BlakeGuilloud/ganon#304]
I'd like to set up a CI environment for the repo, to automatically test for eslint, as well as test case running for the attempted problem

**Comment by BlakeGuilloud** [comment]
Hey @akram-rameez - we opted on using Travis CI. Do you think you could work within the confines of that? It already runs our eslint; however, I have been unable to figure out a way to test the test case for the attempted methods. I would be open to you working on this though!

**Comment by BlakeGuilloud** [comment]
Also- it seems like you are already aware of this, but the whole objective behind this repository is to have "failing tests". As with each new Pull Request, will come tests that should be failing on the new Skeleton Method.

**Comment by akram-rameez** [comment]
I was thinking along the lines of checking the diff of the current branch and master. from the list of files changed, we get the test file, and run that.

**Comment by BlakeGuilloud** [comment]
Yeah that sounds awesome. I don't have much experience with CI stuff, but let me know if you have any questions.

**Comment by ktilcu** [comment]
@akram-rameez I'm going to mark this in progress.
