### ISSUE TITLE
perfectNumber test takes 53 seconds to run.

### ISSUE THREAD

**Issue by BlakeGuilloud** [BlakeGuilloud/ganon#308]
There is a block of code in our perfectNumber test that looks like this:
```javascript
  test("Number 8589869056 is perfect", () => {
    expect(perfectNumber(8589869056)).toBe(true);
  });
```

Because the number under test is so large, it takes up to 53 seconds to run this block by itself. I'm hoping someone could take a look at the `perfectNumber.js` code and see if there is a better implementation we could be using to beef up performance. If this is the best possible solution, then maybe we should remove the test that takes 53 seconds for now? Feel free to express you opinion on this subject.

Without the test block:
![image](https://user-images.githubusercontent.com/14660993/31855852-90ecd108-b681-11e7-835a-1dd6857f5e7d.png)

With the test block:
![image](https://user-images.githubusercontent.com/14660993/31855857-9dca5f4e-b681-11e7-8204-dc859e370218.png)

Acceptance criteria:
1. `yarn test perfectNumber` results in all tests passing.
2. `yarn test perfectNumber` does not take 53 seconds :)

**Comment by Kansattica** [comment]
Hey, I just submitted a request for this. Hope it helped!

**Comment by BlakeGuilloud** [comment]
Thanks!!
