### ISSUE TITLE
Fix rgb2hsv method

### ISSUE THREAD

**Issue by z2oh** [BlakeGuilloud/ganon#315]
There is currently a method called `rgb2hsv` that lives in `/lib/rgb2hsv.js`.
It is incomplete and needs to be fixed!

For this method, you will need to round decimal values to 3 digits. Check out the `toFixed` method to see how to do this. This issue may be a bit harder than some of the others on this repo!

### Acceptance Criteria:
1. Running `yarn test rgb2hsv` results in tests passing.
2. You have written a skeleton method for someone else to work on.
3. You have written tests surrounding your skeleton method.
4. Running `yarn lint` does not print any errors to the console!
5. Optional: write one or two more tests surrounding the method you are solving to account for potential edge cases.

### Please include the skeleton of a new method + an accompanying test for someone else to work on at the time of creating a pull request! A pull request will most likely be denied if it does not contain a skeleton method for someone else to work on! For more information, please read the [Contributing Guide](https://github.com/BlakeGuilloud/ganon/blob/master/CONTRIBUTING.md).

Thank you so much for your contribution!

**Comment by xxDOOMbox** [comment]
ill take this.

**Comment by BlakeGuilloud** [comment]
Cool deal @xxDOOMbox ! Thanks!!
