### ISSUE TITLE
Fix anonymize method

### ISSUE THREAD

**Issue by developerDemetri** [BlakeGuilloud/ganon#324]
There is currently a method called `anonymize` that lives in `/lib/anonymize.js`.
It is incomplete and needs to be fixed!

Returns the users name anonymized such that only the first letter of each name is exposed
 * The remaining characters are each replaced with '*'
 * Ex. `anonymize("John Smith Doe")` returns `"J*** S**** D**"`

### Acceptance Criteria:
1. Running `yarn test anonymize` results in tests passing.
2. You have written a skeleton method for someone else to work on.
3. You have written tests surrounding your skeleton method.
4. Running `yarn lint` does not print any errors to the console!
5. Optional: write one or two more tests surrounding the method you are solving to account for potential edge cases.

### Please include the skeleton of a new method + an accompanying test for someone else to work on at the time of creating a pull request! A pull request will most likely be denied if it does not contain a skeleton method for someone else to work on! For more information, please read the [Contributing Guide](https://github.com/BlakeGuilloud/ganon/blob/master/CONTRIBUTING.md).

Thank you so much for your contribution!

**Comment by ChrisPlease** [comment]
I'll take this one

**Comment by BlakeGuilloud** [comment]
Cool @ChrisPlease - it's yours

**Comment by ChrisPlease** [comment]
@BlakeGuilloud in, created a new ticket for the method I added here: #331
