### ISSUE TITLE
Fix countAlphabets function

### ISSUE THREAD

**Issue by sherlyc** [BlakeGuilloud/ganon#326]
There is currently a method called `countAlphabets` that lives in `/lib/countAlphabets.js`.
It is incomplete and needs to be fixed!

When given a string like "apple" it should returns a count of alphabets like "a:1,p:2,l:1,e:1".

### Acceptance Criteria:
1. Running `yarn test countAlphabets` results in tests passing.
2. You have written a skeleton method for someone else to work on.
3. You have written tests surrounding your skeleton method.
4. Running `yarn lint` does not print any errors to the console!
5. Optional: write one or two more tests surrounding the method you are solving to account for potential edge cases.

### Please include the skeleton of a new method + an accompanying test for someone else to work on at the time of creating a pull request! A pull request will most likely be denied if it does not contain a skeleton method for someone else to work on! For more information, please read the [Contributing Guide](https://github.com/BlakeGuilloud/ganon/blob/master/CONTRIBUTING.md).

Thank you so much for your contribution!

**Comment by MahendraTennakoon** [comment]
@BlakeGuilloud I would like to work on this.

**Comment by BlakeGuilloud** [comment]
Cool @MahendraTennakoon - go for it!

**Comment by BlakeGuilloud** [comment]
Opening this back up.

**Comment by kylevv** [comment]
@BlakeGuilloud I'll work on this if that's alright.

**Comment by BlakeGuilloud** [comment]
@kylevv ! It's yours. Thanks!
