### ISSUE TITLE
Fix areaOfTriangle method

### ISSUE THREAD

**Issue by Blasphemouse** [BlakeGuilloud/ganon#334]
There is currently a method called `areaOfTriangle` that lives in `/lib/areaOfTriangle.js`.
It is incomplete and needs to be fixed!

### Acceptance Criteria:
1. Running `yarn test areaOfTriangle` results in tests passing.
2. You have written a skeleton method for someone else to work on.
3. You have written tests surrounding your skeleton method.
4. Running `yarn lint` does not print any errors to the console!
5. Optional: write one or two more tests surrounding the method you are solving to account for potential edge cases.

### Please include the skeleton of a new method + an accompanying test for someone else to work on at the time of creating a pull request! A pull request will most likely be denied if it does not contain a skeleton method for someone else to work on! For more information, please read the [Contributing Guide](https://github.com/BlakeGuilloud/ganon/blob/master/CONTRIBUTING.md).

Thank you so much for your contribution!

**Comment by stillNovice** [comment]
I'll take this one.

**Comment by kurnifamili** [comment]
Sorry didn't realize someone already took it, go ahead.

**Comment by stillNovice** [comment]
thanks @kurnifamili , i'll start working on it.
