### ISSUE TITLE
fix symmetricDifference method

### ISSUE THREAD

**Issue by binkpitch** [BlakeGuilloud/ganon#335]
There is currently a method called `symmetricDifference` that lives in `/lib/symmetricDifference.js`.
It is incomplete and needs to be fixed!

This method accepts two arrays and return the symmetric difference as an array. The symmetric different is a set consists of elements presented in the first and the second array but not in both.

### Acceptance Criteria:
1. Running `yarn test symmetricDifference` results in tests passing.
2. You have written a skeleton method for someone else to work on.
3. You have written tests surrounding your skeleton method.
4. Running `yarn lint` does not print any errors to the console!
5. Optional: write one or two more tests surrounding the method you are solving to account for potential edge cases.

### Please include the skeleton of a new method + an accompanying test for someone else to work on at the time of creating a pull request! A pull request will most likely be denied if it does not contain a skeleton method for someone else to work on! For more information, please read the [Contributing Guide](https://github.com/BlakeGuilloud/ganon/blob/master/CONTRIBUTING.md).

Thank you so much for your contribution!

**Comment by Manny1995** [comment]
I'll take this.

**Comment by Manny1995** [comment]
How do I get added as a collaborator?
