### ISSUE TITLE
Fix checkPrime

### ISSUE THREAD

**Issue by kurnifamili** [BlakeGuilloud/ganon#343]
There is currently a method called `<checkPrime>` that lives in `/lib/<checkPrime>.js`.
It is incomplete and needs to be fixed!

This method checks whether the integer parameter passed is a prime number or not. 

### Acceptance Criteria:
1. Running `yarn test <methodName>` results in tests passing.
2. You have written a skeleton method for someone else to work on.
3. You have written tests surrounding your skeleton method.
4. Running `yarn lint` does not print any errors to the console!
5. Optional: write one or two more tests surrounding the method you are solving to account for potential edge cases.

### Please include the skeleton of a new method + an accompanying test for someone else to work on at the time of creating a pull request! A pull request will most likely be denied if it does not contain a skeleton method for someone else to work on! For more information, please read the [Contributing Guide](https://github.com/BlakeGuilloud/ganon/blob/master/CONTRIBUTING.md).

Thank you so much for your contribution!

**Comment by ab-decoded** [comment]
I would like to do this

**Comment by thisHemit** [comment]
due to some mysterious reasons, i cant find checkPrime.js in the lib folder. Could you help me out?

**Comment by kurnifamili** [comment]
Hi @thisHemit. Unfortunately, my PR containing the files has not been merged yet. That is why you cannot find it in the lib folder yet.

Here is my commit link https://github.com/kurnifamili/ganon/commit/3c9774f6af8993781b3029bb3ece01ea7f404698 .

You can retrieve the files from there first to get a headstart. I will update you when my PR is merged.

**Comment by thisHemit** [comment]
Thanks @kurnifamili . As I am new to github, i would like to know how to add a "in progress" label to this issue as i am working on it.

**Comment by kurnifamili** [comment]
Sure, glad to have you here. It's a bit complicated because the commit is located at my repo, not this one. So to avoid confusing you, you can just download the files at the commit link I give you and put it in their respective folder (lib or test).

**Comment by thisHemit** [comment]
Thanks @kurnifamili . I had already done that. I was just requesting you to add a in progress label to this issue.

**Comment by thisHemit** [comment]
@kurnifamili I am facing a problem with the second test

the error it gives is:

`yarn test v0.15.1
$ jest ./test/checkPrime.test.js
 FAIL  test/checkPrime.test.js
  checkPrime
    ✓ returns true if the argument is a prime number (6ms)
    ✕ does not mutate the input number (3ms)
    ✓ throws an error if the argument is not an integer (1ms)

  ● checkPrime › does not mutate the input number

    expect(received).toEqual(expected)
    
    Expected value to equal:
      false
    Received:
      true
      
      at Object.<anonymous> (test/checkPrime.test.js:11:29)
      at process._tickCallback (node.js:385:9)

Test Suites: 1 failed, 1 total
Tests:       1 failed, 2 passed, 3 total
Snapshots:   0 total
Time:        2.191s
Ran all test suites matching /.\/test\/checkPrime.test.js/i.
`
and this is my code:

`function checkPrime(number) {
  var n = number;
  if(!Number.isInteger(n)) throw new Error("Input is not a number");
  if(n === 2 || n === 3) return true;

  if(n <= 2) return false;

  for(var i = 5; i*i < n; i = i + 6){
    if(n % i === 0 || n % (i + 2) === 0){
      return false;
    }
  }
  return true;
}

module.exports = checkPrime;
`
It seems that there is some problem with the test. Could you please help me out?

**Comment by thisHemit** [comment]
Sorry for the trouble. I resolved my silly mistake.

**Comment by kurnifamili** [comment]
Oops sorry for my misunderstanding.

I think only the repo admin can add labels, so I cannot help you for that.

**Comment by ktilcu** [comment]
@kurnifamili Thanks again!
