### ISSUE TITLE
Fix once method

### ISSUE THREAD

**Issue by mtso** [BlakeGuilloud/ganon#349]
There is currently a method called `once` that lives in `/lib/once.js`.
It is incomplete and needs to be fixed!

`once` takes a function and returns a function that executes the given function once. The first time the returned function is called, its return value is saved. Subsequent calls to the returned function returns the saved value.

### Acceptance Criteria:
1. Running `yarn test once` results in tests passing.
2. You have written a skeleton method for someone else to work on.
3. You have written tests surrounding your skeleton method.
4. Running `yarn lint` does not print any errors to the console!
5. Optional: write one or two more tests surrounding the method you are solving to account for potential edge cases.

### Please include the skeleton of a new method + an accompanying test for someone else to work on at the time of creating a pull request! A pull request will most likely be denied if it does not contain a skeleton method for someone else to work on! For more information, please read the [Contributing Guide](https://github.com/BlakeGuilloud/ganon/blob/master/CONTRIBUTING.md).

Thank you so much for your contribution!

**Comment by stillNovice** [comment]
i'll take this one

**Comment by stillNovice** [comment]
I can't see once.js in lib folder. @mtso please look into this.

**Comment by BlakeGuilloud** [comment]
Hey @stillNovice - his PR was just merged in a few minutes ago. It should contain the once.js file.
