### ISSUE TITLE
Fix isArray method

### ISSUE THREAD

**Issue by mtso** [BlakeGuilloud/ganon#350]
There is currently a method called `isArray` that lives in `/lib/isArray.js`.
It is incomplete and needs to be fixed!

`isArray` returns true if the value is an array and false if the value is not.

### Acceptance Criteria:
1. Running `yarn test isArray` results in tests passing.
2. You have written a skeleton method for someone else to work on.
3. You have written tests surrounding your skeleton method.
4. Running `yarn lint` does not print any errors to the console!
5. Optional: write one or two more tests surrounding the method you are solving to account for potential edge cases.

### Please include the skeleton of a new method + an accompanying test for someone else to work on at the time of creating a pull request! A pull request will most likely be denied if it does not contain a skeleton method for someone else to work on! For more information, please read the [Contributing Guide](https://github.com/BlakeGuilloud/ganon/blob/master/CONTRIBUTING.md).

Thank you so much for your contribution!

**Comment by jsjain007** [comment]
Hi @mtso  this is my first time contributing to open source and i would like to start contributing with this issue. Could you please tell me if I have to create this file `isArray.js` as I cannot find it in lib folder. Thanks
