### ISSUE TITLE
Fix convertDegreesToRadians method

### ISSUE THREAD

**Issue by damjanh** [BlakeGuilloud/ganon#353]
There is currently a method called `convertDegreesToRadians` that lives in `/lib/convertDegreesToRadians.js`.
It is incomplete and needs to be fixed!

`convertDegreesToRadians ` should convert degrees to radians. If the parameter is not a number the method should throw an error.

### Acceptance Criteria:
1. Running `yarn test convertDegreesToRadians ` results in tests passing.
2. You have written a skeleton method for someone else to work on.
3. You have written tests surrounding your skeleton method.
4. Running `yarn lint` does not print any errors to the console!
5. Optional: write one or two more tests surrounding the method you are solving to account for potential edge cases.

### Please include the skeleton of a new method + an accompanying test for someone else to work on at the time of creating a pull request! A pull request will most likely be denied if it does not contain a skeleton method for someone else to work on! For more information, please read the [Contributing Guide](https://github.com/BlakeGuilloud/ganon/blob/master/CONTRIBUTING.md).

Thank you so much for your contribution!

**Comment by jsjain007** [comment]
@damjanh Hello, I would like to take this issue. Thanks

**Comment by ktilcu** [comment]
@jsjain007 All yours. You have appx 24 hours before we release it. Thanks for jumping on board!

**Comment by BlakeGuilloud** [comment]
Opening this back up.

**Comment by fionn-mac** [comment]
Hello!
I've added a pull request for this issue :)

**Comment by ktilcu** [comment]
I merged it.
