### ISSUE TITLE
Fix Alphabetize function

### ISSUE THREAD

**Issue by BlakeGuilloud** [BlakeGuilloud/ganon#36]
There is currently a method called `alphabetize` that lives in `/lib/alphabetize.js`.
It is incomplete and needs to be fixed!

### Acceptance Criteria:
1. Running `yarn test alphabetize` results in tests passing.

#### Please include the skeleton of a new method + an accompanying test for someone else to work on at the time of creating a pull request!

**Comment by h93xV2** [comment]
I am going to start working on this.

**Comment by smehta11** [comment]
I'd be happy to take this on.

**Comment by BlakeGuilloud** [comment]
Go for it @smehta11 !

**Comment by smehta11** [comment]
Resolved by #48.

**Comment by BlakeGuilloud** [comment]
Thanks!
