### ISSUE TITLE
Fix topoSort method

### ISSUE THREAD

**Issue by conradreuter** [BlakeGuilloud/ganon#361]
There is currently a method called `topoSort` that lives in `/lib/topoSort.js`.
It is incomplete and needs to be fixed!

It [topologically sorts](https://en.wikipedia.org/wiki/Topological_sorting) a directed graph represented by its adjacency list.

### Acceptance Criteria:
1. Running `yarn test topoSort` results in tests passing.
2. You have written a skeleton method for someone else to work on.
3. You have written tests surrounding your skeleton method.
4. Running `yarn lint` does not print any errors to the console!
5. Optional: write one or two more tests surrounding the method you are solving to account for potential edge cases.

### Please include the skeleton of a new method + an accompanying test for someone else to work on at the time of creating a pull request! A pull request will most likely be denied if it does not contain a skeleton method for someone else to work on! For more information, please read the [Contributing Guide](https://github.com/BlakeGuilloud/ganon/blob/master/CONTRIBUTING.md).

Thank you so much for your contribution!

**Comment by Ampretuzo** [comment]
Looks interesting. I'll do it.

**Comment by conradreuter** [comment]
Please be aware that #360 needs to be merged, or else you will not have the skeleton and tests at hand.

**Comment by Ampretuzo** [comment]
@conradreuter thanks, I'll copy skeleton manually
