### ISSUE TITLE
Fix the product method to be left variadic

### ISSUE THREAD

**Issue by babhishek21** [BlakeGuilloud/ganon#366]
There is currently a method called `product` that lives in `/lib/product.js`.
It is incomplete and needs to be fixed!

Take a look at #283. The `product` method qualifies for variadic treatment. It should be able to take variable number of arguments, both numeric types and castable to numeric types or a mix of both. It may even take arrays of such types.

For hint on how to achieve that, take a look at #365. 

### Acceptance Criteria:
1. Running `yarn test product` results in tests passing.
2. You have written a skeleton method for someone else to work on.
3. You have written tests surrounding your skeleton method.
4. Running `yarn lint` does not print any errors to the console!
5. Optional: write one or two more tests surrounding the method you are solving to account for potential edge cases.

### Please include the skeleton of a new method + an accompanying test for someone else to work on at the time of creating a pull request! A pull request will most likely be denied if it does not contain a skeleton method for someone else to work on! For more information, please read the [Contributing Guide](https://github.com/BlakeGuilloud/ganon/blob/master/CONTRIBUTING.md).

Thank you so much for your contribution!

**Comment by JJEEGG2211** [comment]
Can I try this one?
Thanks!
