### ISSUE TITLE
Implement the or method to be left variadic

### ISSUE THREAD

**Issue by babhishek21** [BlakeGuilloud/ganon#367]
There is currently a method called `or` that lives in `/lib/or.js`. ~~post #365 is merged.~~
It is incomplete and needs to be fixed!

Take a look at #283. The `or` method qualifies for variadic treatment. It should be able to take variable number of arguments, both numeric types and castable to numeric types or a mix of both. It may even take arrays of such types.

For hint on how to achieve that, take a look at #365. ~~Wait for #365 to be merged before you start implementing it (so that~~ you can make use of the brilliant test suite written for it 😎 ~~).~~

### Acceptance Criteria:
1. Running `yarn test or` results in tests passing.
2. You have written a skeleton method for someone else to work on.
3. You have written tests surrounding your skeleton method.
4. Running `yarn lint` does not print any errors to the console!
5. Optional: write one or two more tests surrounding the method you are solving to account for potential edge cases.

### Please include the skeleton of a new method + an accompanying test for someone else to work on at the time of creating a pull request! A pull request will most likely be denied if it does not contain a skeleton method for someone else to work on! For more information, please read the [Contributing Guide](https://github.com/BlakeGuilloud/ganon/blob/master/CONTRIBUTING.md).

Thank you so much for your contribution!

**Comment by babhishek21** [comment]
#365 is now merged. Get to work, folks!

**Comment by ktilcu** [comment]
haha

**Comment by FranceJ** [comment]
@BlakeGuilloud I'll have a look at this

**Comment by FranceJ** [comment]
This is almost done I think. I will probably need another day though

**Comment by BlakeGuilloud** [comment]
Take your time @FranceJ ! Thanks for the update.
