### ISSUE TITLE
Fix Reverse function

### ISSUE THREAD

**Issue by BlakeGuilloud** [BlakeGuilloud/ganon#37]
There is currently a method called `reverse` that lives in `/lib/reverse.js`.
It is incomplete and needs to be fixed!

### Acceptance Criteria:
1. Running `yarn test reverse` results in tests passing.

#### Please include the skeleton of a new method + an accompanying test for someone else to work on at the time of creating a pull request!

**Comment by grigori-gru** [comment]
I'll try it
