### ISSUE TITLE
convex polygon area calculation

### ISSUE THREAD

**Issue by Ampretuzo** [BlakeGuilloud/ganon#370]
There is currently a method called `areaOfConvexPolygon` that lives in `/lib/areaOfConvexPolygon.js`.
It is incomplete and needs to be fixed!

What it does is self explanatory, please make sure to use home grown `areaOfTriangle` function!

### Acceptance Criteria:
1. Running `yarn test areaOfConvexPolygon` results in tests passing.
2. You have written a skeleton method for someone else to work on.
3. You have written tests surrounding your skeleton method.
4. Running `yarn lint` does not print any errors to the console!
5. Optional: write one or two more tests surrounding the method you are solving to account for potential edge cases.

### Please include the skeleton of a new method + an accompanying test for someone else to work on at the time of creating a pull request! A pull request will most likely be denied if it does not contain a skeleton method for someone else to work on! For more information, please read the [Contributing Guide](https://github.com/BlakeGuilloud/ganon/blob/master/CONTRIBUTING.md).

Thank you so much for your contribution!

NOTE: wait for #369 merge, or copy method skeleton in advance from my fork to start progress early.

**Comment by devanp92** [comment]
I can take this

**Comment by devanp92** [comment]
I can take this

**Comment by ktilcu** [comment]
@devanp92 Thanks. Looking forward to reviewing this!
