### ISSUE TITLE
Fix bug in GCD method

### ISSUE THREAD

**Issue by hasib71** [BlakeGuilloud/ganon#371]
There is currently a method called `gcd` that lives in `/lib/gcd.js`.
It has bugs and needs to be fixed!

GCD(0, n) should be equal to n. The current method is throwing exception.

### Acceptance Criteria:
1. Running `yarn test <methodName>` results in tests passing.
2. Running `yarn lint` does not print any errors to the console!
3. Optional: write one or two more tests surrounding the method you are solving to account for potential edge cases.

Thank you so much for your contribution!

**Comment by hasib71** [comment]
@BlakeGuilloud I would like to work on this

**Comment by BlakeGuilloud** [comment]
Cool deal @hasib71 ! Thanks
