### ISSUE TITLE
Fix countAlphabets method

### ISSUE THREAD

**Issue by showmeyourhits** [BlakeGuilloud/ganon#372]
There is currently a method called `countAlphabets` that lives in `/lib/countAlphabets.js`.
It is incomplete and needs to be fixed!

This method count occurences of letters in string, and returns new string in format `[letter1]:count`

### Acceptance Criteria:
1. Running `yarn test countAlphabets` results in tests passing.
2. You have written a skeleton method for someone else to work on.
3. You have written tests surrounding your skeleton method.
4. Running `yarn lint` does not print any errors to the console!
5. Optional: write one or two more tests surrounding the method you are solving to account for potential edge cases.

### Please include the skeleton of a new method + an accompanying test for someone else to work on at the time of creating a pull request! A pull request will most likely be denied if it does not contain a skeleton method for someone else to work on! For more information, please read the [Contributing Guide](https://github.com/BlakeGuilloud/ganon/blob/master/CONTRIBUTING.md).

Thank you so much for your contribution!

**Comment by showmeyourhits** [comment]
@BlakeGuilloud i would like to work on dis

**Comment by BlakeGuilloud** [comment]
No worries @showmeyourhits ! I'm going to close this issue out.
