### ISSUE TITLE
Fix convertFeetToMeters method

### ISSUE THREAD

**Issue by jsjain007** [BlakeGuilloud/ganon#374]
There is currently a method called `convertFeetToMeters` that lives in `/lib/convertFeetToMeters.js`.
It is incomplete and needs to be fixed!

### Acceptance Criteria:
1. Running `yarn test <methodName>` results in tests passing.
2. You have written a skeleton method for someone else to work on.
3. You have written tests surrounding your skeleton method.
4. Running `yarn lint` does not print any errors to the console!
5. Optional: write one or two more tests surrounding the method you are solving to account for potential edge cases.

### Please include the skeleton of a new method + an accompanying test for someone else to work on at the time of creating a pull request! A pull request will most likely be denied if it does not contain a skeleton method for someone else to work on! For more information, please read the [Contributing Guide](https://github.com/BlakeGuilloud/ganon/blob/master/CONTRIBUTING.md).

Thank you so much for your contribution!

**Comment by showmeyourhits** [comment]
@BlakeGuilloud i sooooo would like to work on this method, please, could you let me?

**Comment by Aonepathan** [comment]
I'd like to tackle this issue.

**Comment by BlakeGuilloud** [comment]
Thanks @Aonepathan ! You've got 24 hours. Good luck!~

**Comment by Aonepathan** [comment]
@BlakeGuilloud  I guess @Yogendra0Sharma decided to take care of this issue before me...?

**Comment by Aonepathan** [comment]
@BlakeGuilloud @Yogendra0Sharma Well I did this last night as well, was waiting to add a Acceleration.js skeleton, I've submitted my PR, please review that as I followed the steps for claiming this issue.

**Comment by Yogendra0Sharma** [comment]
@Aonepathan No Problem:1st_place_medal:  @BlakeGuilloud You can merge @Aonepathan PR.

**Comment by Aonepathan** [comment]
Thanks @Yogendra0Sharma, I'm sorry for sounding rude on this, I just was working on it also and had no idea you did it also! Thanks again
