### ISSUE TITLE
Fix compact method

### ISSUE THREAD

**Issue by showmeyourhits** [BlakeGuilloud/ganon#376]
There is currently a method called `compact` that lives in `/lib/compact.js`.
It is incomplete and needs to be fixed!

This method returns a copy of the array with all falsy values removed. For example if passed [1, 2, 0,  4], it will return [1, 2, 4].

### Acceptance Criteria:
1. Running `yarn test compact` results in tests passing.
2. You have written a skeleton method for someone else to work on.
3. You have written tests surrounding your skeleton method.
4. Running `yarn lint` does not print any errors to the console!
5. Optional: write one or two more tests surrounding the method you are solving to account for potential edge cases.

### Please include the skeleton of a new method + an accompanying test for someone else to work on at the time of creating a pull request! A pull request will most likely be denied if it does not contain a skeleton method for someone else to work on! For more information, please read the [Contributing Guide](https://github.com/BlakeGuilloud/ganon/blob/master/CONTRIBUTING.md).

Thank you so much for your contribution!

**Comment by Manny1995** [comment]
@showmeyourhits I would like to work on this!  Can you assign me to it?

**Comment by ktilcu** [comment]
@Manny1995 Thanks for stepping in! We will leave this in progress for 24 hours and then release it back to the wild. Looking forward to your contributions..

**Comment by ktilcu** [comment]
Thanks again @Manny1995
