### ISSUE TITLE
Fix union method

### ISSUE THREAD

**Issue by mtso** [BlakeGuilloud/ganon#381]
There is currently a method called `union` that lives in `/lib/union.js`.
It is incomplete and needs to be fixed!

`union` combines multiple arrays into a single one with the unique values from each.

### Acceptance Criteria:
1. Running `yarn test union` results in tests passing.
2. You have written a skeleton method for someone else to work on.
3. You have written tests surrounding your skeleton method.
4. Running `yarn lint` does not print any errors to the console!
5. Optional: write one or two more tests surrounding the method you are solving to account for potential edge cases.

### Please include the skeleton of a new method + an accompanying test for someone else to work on at the time of creating a pull request! A pull request will most likely be denied if it does not contain a skeleton method for someone else to work on! For more information, please read the [Contributing Guide](https://github.com/BlakeGuilloud/ganon/blob/master/CONTRIBUTING.md).

Thank you so much for your contribution!

**Comment by juniorvid** [comment]
I will work on this!

**Comment by BlakeGuilloud** [comment]
Thanks @juniorvid ! You've got 24 hours. Good luck!

**Comment by BrainMaestro** [comment]
Is this still in progress? I would like to work on it

**Comment by BlakeGuilloud** [comment]
Hey @BrainMaestro ! Sorry for the late response. Yes it's still open. You still want to work on it?

**Comment by hyades** [comment]
Can I jump in?

**Comment by BlakeGuilloud** [comment]
Go for it @hyades !
