### ISSUE TITLE
Fix merge method

### ISSUE THREAD

**Issue by mtso** [BlakeGuilloud/ganon#383]
There is currently a method called `merge` that lives in `/lib/merge.js`.
It is incomplete and needs to be fixed!

`merge` combines multiple objects into a single one with all the keys of each object. When two objects have the same key, the value from the second object is used.

### Acceptance Criteria:
1. Running `yarn test merge` results in tests passing.
2. You have written a skeleton method for someone else to work on.
3. You have written tests surrounding your skeleton method.
4. Running `yarn lint` does not print any errors to the console!
5. Optional: write one or two more tests surrounding the method you are solving to account for potential edge cases.

### Please include the skeleton of a new method + an accompanying test for someone else to work on at the time of creating a pull request! A pull request will most likely be denied if it does not contain a skeleton method for someone else to work on! For more information, please read the [Contributing Guide](https://github.com/BlakeGuilloud/ganon/blob/master/CONTRIBUTING.md).

Thank you so much for your contribution!

**Comment by danswater** [comment]
i will take this.

**Comment by BlakeGuilloud** [comment]
Thanks @danswater ! You've got 24 hours. Good luck!
