### ISSUE TITLE
Fix select method

### ISSUE THREAD

**Issue by mtso** [BlakeGuilloud/ganon#385]
There is currently a method called `select` that lives in `/lib/select.js`.
It is incomplete and needs to be fixed!

### Acceptance Criteria:
1. Running `yarn test select` results in tests passing.
2. You have written a skeleton method for someone else to work on.
3. You have written tests surrounding your skeleton method.
4. Running `yarn lint` does not print any errors to the console!
5. Optional: write one or two more tests surrounding the method you are solving to account for potential edge cases.

### Please include the skeleton of a new method + an accompanying test for someone else to work on at the time of creating a pull request! A pull request will most likely be denied if it does not contain a skeleton method for someone else to work on! For more information, please read the [Contributing Guide](https://github.com/BlakeGuilloud/ganon/blob/master/CONTRIBUTING.md).

Thank you so much for your contribution!

**Comment by sanatankc** [comment]
I would like to work on this.

**Comment by ktilcu** [comment]
@sanatankc Great. This buys you 24 hours before we open it back up. Enjoy and thanks!

**Comment by BlakeGuilloud** [comment]
Opening this back up.

**Comment by csjiang** [comment]
Hi @BlakeGuilloud , is it all right if I work on this? Thanks!

**Comment by BlakeGuilloud** [comment]
Hey @csjiang - you got it. Marking as In Progress
