### ISSUE TITLE
Fix convertFeetToInches method

### ISSUE THREAD

**Issue by devanp92** [BlakeGuilloud/ganon#389]
There is currently a method called `convertFeetToInches` that lives in `/lib/convertFeetToInches.js`.
It is incomplete and needs to be fixed!

### Acceptance Criteria:
1. Running `yarn test convertFeetToInches` results in tests passing.
2. You have written a skeleton method for someone else to work on.
3. You have written tests surrounding your skeleton method.
4. Running `yarn lint` does not print any errors to the console!
5. Optional: write one or two more tests surrounding the method you are solving to account for potential edge cases.

### Please include the skeleton of a new method + an accompanying test for someone else to work on at the time of creating a pull request! A pull request will most likely be denied if it does not contain a skeleton method for someone else to work on! For more information, please read the [Contributing Guide](https://github.com/BlakeGuilloud/ganon/blob/master/CONTRIBUTING.md).

Thank you so much for your contribution!

**Comment by josephmcasey** [comment]
Sounds cool, I'll work on this!

**Comment by josephmcasey** [comment]
Pull request #394 introduces the convertFeetToInches functionality and introduces a convert function.

The scope was expanded beyond the issue in two manners:
1) I added .idea to the gitignore files for anyone who prefers developing with a Jet Brain product.
2) I removed a test which expected a throw on non-numeric types which utilizes a negative number for its argument.
