### ISSUE TITLE
convertInchesToFeet.js 

### ISSUE THREAD

**Issue by Manny1995** [BlakeGuilloud/ganon#390]
There is currently a method called `convertInchesToFeet` that lives in `/lib/convertInchesToFeet.js`.
It is incomplete and needs to be fixed!

convertInchesToFeet takes in a number of inches as the input and expects the number of feet as the output

### Acceptance Criteria:
1. Running `yarn test convertInchesToFeet` results in tests passing.
2. You have written a skeleton method for someone else to work on.
3. You have written tests surrounding your skeleton method.
4. Running `yarn lint` does not print any errors to the console!
5. Optional: write one or two more tests surrounding the method you are solving to account for potential edge cases.

### Please include the skeleton of a new method + an accompanying test for someone else to work on at the time of creating a pull request! A pull request will most likely be denied if it does not contain a skeleton method for someone else to work on! For more information, please read the [Contributing Guide](https://github.com/BlakeGuilloud/ganon/blob/master/CONTRIBUTING.md).

Thank you so much for your contribution!

**Comment by FranceJ** [comment]
@BlakeGuilloud I would like to work on this

**Comment by ktilcu** [comment]
@FranceJ We will lock this one for 24 hours. Let us know if you need more time.

**Comment by FranceJ** [comment]
There is a distinct possibility that I am being obtuse, but in the test file it looks like 1 test is failing because it is expecting an input of 2 inches to result in an output of 1.6667.

Based on the description it looks like the input is meant to be 14. Is the test potentially wrong?

See line 9 of convertInchesToFeet.test.js 
@ktilcu

**Comment by Manny1995** [comment]
@FranceJ  My bad, the test I wrote is wrong!  I could have sworn I put in 14, but looks like I put in 2 instead.  Please feel free to change the test case to reflect the correct value.

Sorry for the inconvenience!
