### ISSUE TITLE
Fix SnakeCase method

### ISSUE THREAD

**Issue by devanp92** [BlakeGuilloud/ganon#392]
There is currently a method called `snakeCase` that lives in `/lib/snakeCase.js`.
It is incomplete and needs to be fixed!

### Acceptance Criteria:
1. Running `yarn test snakeCase` results in tests passing.
2. You have written a skeleton method for someone else to work on.
3. You have written tests surrounding your skeleton method.
4. Running `yarn lint` does not print any errors to the console!
5. Optional: write one or two more tests surrounding the method you are solving to account for potential edge cases.

### Please include the skeleton of a new method + an accompanying test for someone else to work on at the time of creating a pull request! A pull request will most likely be denied if it does not contain a skeleton method for someone else to work on! For more information, please read the [Contributing Guide](https://github.com/BlakeGuilloud/ganon/blob/master/CONTRIBUTING.md).

Thank you so much for your contribution!

_Waiting on https://github.com/BlakeGuilloud/ganon/pull/391/files to be merged_

**Comment by devninja89** [comment]
I'll take it!

**Comment by ktilcu** [comment]
@devninja89 We'll mark this in progress for 24 hours. Let us know if you need more time.

**Comment by devninja89** [comment]
Done!
