### ISSUE TITLE
Implement convert

### ISSUE THREAD

**Issue by josephmcasey** [BlakeGuilloud/ganon#395]
There is currently a method called `convert` that lives in `/lib/convert.js`.
It is incomplete and needs to be fixed!

Convert is a functional dyadic method which returns a conversion function matching the two arguments or throws an Error when the provided arguments cannot be matched to an available conversion function.

### Acceptance Criteria:
1. Running `yarn test convert\.test\.js` results in tests passing.
2. You have written a skeleton method for someone else to work on.
3. You have written tests surrounding your skeleton method.
4. Running `yarn lint` does not print any errors to the console!
5. Optional: write one or two more tests surrounding the method you are solving to account for potential edge cases.

### Please include the skeleton of a new method + an accompanying test for someone else to work on at the time of creating a pull request! A pull request will most likely be denied if it does not contain a skeleton method for someone else to work on! For more information, please read the [Contributing Guide](https://github.com/BlakeGuilloud/ganon/blob/master/CONTRIBUTING.md).

Thank you so much for your contribution!

**Comment by freebird1195** [comment]
Hey! I just cloned this and added a convertKilogramsToPounds Function. I went through the acceptance criteria and I am not able to run yarn test convert. It gives me an error. I am new to this. Any help will be appreciated.

**Comment by josephmcasey** [comment]
Sorry @freebird1195 ! My description is wrong. The jest regex match is catching too many tests.

`yarn test convert\.test\.js`

will only run the tests under the convert.test.js file.

**Comment by ktilcu** [comment]
@freebird1195 If you are wokring on this I will mark it as in progress

**Comment by freebird1195** [comment]
@ktilcu Okay.
