### ISSUE TITLE
Fix Least Common Multiple method

### ISSUE THREAD

**Issue by arcticbarra** [BlakeGuilloud/ganon#399]
There is currently a method called `lcm` that lives in `/lib/lcm.js`.
It is incomplete and needs to be fixed!

### Acceptance Criteria:
1. Running `yarn test lcm` results in tests passing.
2. You have written a skeleton method for someone else to work on.
3. You have written tests surrounding your skeleton method.
4. Running `yarn lint` does not print any errors to the console!
5. Optional: write one or two more tests surrounding the method you are solving to account for potential edge cases.

### Please include the skeleton of a new method + an accompanying test for someone else to work on at the time of creating a pull request! A pull request will most likely be denied if it does not contain a skeleton method for someone else to work on! For more information, please read the [Contributing Guide](https://github.com/BlakeGuilloud/ganon/blob/master/CONTRIBUTING.md).

Thank you so much for your contribution!

**Comment by zuzanatoldyova** [comment]
Hi, can I work on this?

**Comment by ktilcu** [comment]
@zuzanatoldyova Yes please! I will keep this locked to you for 24 hours. If you need more time please just let us know. We are looking forward to your contribution.

**Comment by zuzanatoldyova** [comment]
Hi, I just saw that this was already solved by someone else in pr #410

**Comment by BlakeGuilloud** [comment]
Hey @zuzanatoldyova ! Sorry about that. We try to keep up with issues as best we can. Feel free to improve the existing implementation if you'd like. Or find a new issue :) Thanks!
