### ISSUE TITLE
Fix the Product method

### ISSUE THREAD

**Issue by BlakeGuilloud** [BlakeGuilloud/ganon#4]
There is currently a method called `product` that lives in `/lib/product.js`.
It is incomplete and needs to be fixed!

### Acceptance Criteria:
1. Running `yarn test product` results in tests passing.

#### Please include the skeleton of a new method + an accompanying test for someone else to work on at the time of creating a pull request!

**Comment by chromaticity** [comment]
would love to take a crack at it. I'll let you know what comes up

**Comment by BlakeGuilloud** [comment]
Thanks @chromaticity !
