### ISSUE TITLE
Fix Pythagorean method

### ISSUE THREAD

**Issue by BlakeGuilloud** [BlakeGuilloud/ganon#40]
There is currently a method called `pythagorean` that lives in `/lib/pythagorean.js`.
It is incomplete and needs to be fixed!

### Acceptance Criteria:
1. Running `yarn test pythagorean` results in tests passing.

#### Please include the skeleton of a new method + an accompanying test for someone else to work on at the time of creating a pull request!

**Comment by h93xV2** [comment]
I will start working on this.

**Comment by BlakeGuilloud** [comment]
Awesome- Thanks @h93xV2 !
