### ISSUE TITLE
Fix convertYardsToMeters

### ISSUE THREAD

**Issue by josephbhunt** [BlakeGuilloud/ganon#401]
There is currently a method called `convertYardsToMeters ` that lives in `/lib/convertYardsToMeters .js`.
It is incomplete and needs to be fixed!

Convert yards to meters where 1 yard equals 0.9144 meters

### Acceptance Criteria:
1. Running `yarn test convertYardsToMeters` results in tests passing.
2. You have written a skeleton method for someone else to work on.
3. You have written tests surrounding your skeleton method.
4. Running `yarn lint` does not print any errors to the console!
5. Optional: write one or two more tests surrounding the method you are solving to account for potential edge cases.

### Please include the skeleton of a new method + an accompanying test for someone else to work on at the time of creating a pull request! A pull request will most likely be denied if it does not contain a skeleton method for someone else to work on! For more information, please read the [Contributing Guide](https://github.com/BlakeGuilloud/ganon/blob/master/CONTRIBUTING.md).

Thank you so much for your contribution!

**Comment by gballesteros10** [comment]
Mine, please. My first!

**Comment by gballesteros10** [comment]
Side-note regarding my PR #412 : I know we're not supposed to alter test files, but the test says it expects a negative value but forgot to put "-" in the expected value. Included it in my changes. Cheers!

**Comment by ktilcu** [comment]
@gballesteros10 Thanks for the PR i will look over it. No worries about the test files. ;P
