### ISSUE TITLE
Implement `is`

### ISSUE THREAD

**Issue by josephmcasey** [BlakeGuilloud/ganon#403]
There is currently a method called `<methodName>` that lives in `/lib/<methodName>.js`.
It is incomplete and needs to be fixed!

is should be a functional monadic method which returns a function when a provided an argument of type string which corresponds with an existing boolean determinant. Invalid arguments throw Error.

### Acceptance Criteria:
1. Running `yarn test is\.test\.js` results in tests passing.
2. You have written a skeleton method for someone else to work on.
3. You have written tests surrounding your skeleton method.
4. Running `yarn lint` does not print any errors to the console!
5. Optional: write one or two more tests surrounding the method you are solving to account for potential edge cases.

### Please include the skeleton of a new method + an accompanying test for someone else to work on at the time of creating a pull request! A pull request will most likely be denied if it does not contain a skeleton method for someone else to work on! For more information, please read the [Contributing Guide](https://github.com/BlakeGuilloud/ganon/blob/master/CONTRIBUTING.md).

Thank you so much for your contribution!

**Comment by josephmcasey** [comment]
Awaiting pull request #168 . Consideration and review from public and project maintainers encouraged while waiting.

**Comment by josephmcasey** [comment]
Pull request #168 merged. Available for anyone interested.

**Comment by Peradon** [comment]
I'm interested, can I do this one?

**Comment by ktilcu** [comment]
@Peradon it's yours. I will lock it for 24 hours. Enjoy!

**Comment by Peradon** [comment]
This is my first pull request, if there is any problem please feel free to notify me.
