### ISSUE TITLE
fix isJSON function

### ISSUE THREAD

**Issue by asafofer** [BlakeGuilloud/ganon#418]
There is currently a method called `isJSON` that lives in `/lib/isJSON.js`.
It is incomplete and needs to be fixed!

a function that returns true if an argument is valid JSON and false if it isn't

### Acceptance Criteria:
1. Running `yarn test isJSON` results in tests passing.
2. You have written a skeleton method for someone else to work on.
3. You have written tests surrounding your skeleton method.
4. Running `yarn lint` does not print any errors to the console!
5. Optional: write one or two more tests surrounding the method you are solving to account for potential edge cases.

### Please include the skeleton of a new method + an accompanying test for someone else to work on at the time of creating a pull request! A pull request will most likely be denied if it does not contain a skeleton method for someone else to work on! For more information, please read the [Contributing Guide](https://github.com/BlakeGuilloud/ganon/blob/master/CONTRIBUTING.md).

Thank you so much for your contribution!

**Comment by andrey-semin** [comment]
i'lll take this one

**Comment by ktilcu** [comment]
@andrey-semin You got it! We will lock this one for 24 hours while you finish.
