### ISSUE TITLE
fix convertMeterstoFeet method

### ISSUE THREAD

**Issue by jsjain007** [BlakeGuilloud/ganon#420]
There is currently a method called `convertMeterstoFeet` that lives in `/lib/convertMeterstoFeet.js`.
It is incomplete and needs to be fixed!

### Acceptance Criteria:
1. Running `yarn test <methodName>` results in tests passing.
2. You have written a skeleton method for someone else to work on.
3. You have written tests surrounding your skeleton method.
4. Running `yarn lint` does not print any errors to the console!
5. Optional: write one or two more tests surrounding the method you are solving to account for potential edge cases.

### Please include the skeleton of a new method + an accompanying test for someone else to work on at the time of creating a pull request! A pull request will most likely be denied if it does not contain a skeleton method for someone else to work on! For more information, please read the [Contributing Guide](https://github.com/BlakeGuilloud/ganon/blob/master/CONTRIBUTING.md).

Thank you so much for your contribution!

**Comment by devninja89** [comment]
@BlakeGuilloud I'll take this

**Comment by devninja89** [comment]
hey guys, can you extend this for 24 hours? ran into some overtime at work and havent had time to come back

**Comment by BlakeGuilloud** [comment]
Opening this back up. @devninja89 if you still want to work on it, ping me and i'll mark in progress again. Thanks!

**Comment by jaymcgrath** [comment]
I'm grabbing this one

**Comment by BlakeGuilloud** [comment]
you got it @jaymcgrath !
