### ISSUE TITLE
fix isPangram

### ISSUE THREAD

**Issue by devninja89** [BlakeGuilloud/ganon#426]
There is currently a method called `isPangram` that lives in `/lib/isPangram.js`.
It is incomplete and needs to be fixed!

A pangram is a sentence that contains every letter of the alphabet at least once.  This method returns true if the input string is a pangram. Else, it returns false.

### Acceptance Criteria:
1. Running `yarn test isPangram` results in tests passing.
2. You have written a skeleton method for someone else to work on.
3. You have written tests surrounding your skeleton method.
4. Running `yarn lint` does not print any errors to the console!
5. Optional: write one or two more tests surrounding the method you are solving to account for potential edge cases.

### Please include the skeleton of a new method + an accompanying test for someone else to work on at the time of creating a pull request! A pull request will most likely be denied if it does not contain a skeleton method for someone else to work on! For more information, please read the [Contributing Guide](https://github.com/BlakeGuilloud/ganon/blob/master/CONTRIBUTING.md).

Thank you so much for your contribution!

**Comment by damjanh** [comment]
@BlakeGuilloud I would like to work on this.

**Comment by ktilcu** [comment]
@damjanh We will lock this one down for 24 hours while you work. Have Fun!
