### ISSUE TITLE
Fix xorEncryption method

### ISSUE THREAD

**Issue by rgehan** [BlakeGuilloud/ganon#433]
There is currently a method called `xorEncryption` that lives in `/lib/xorEncryption.js`.
It is incomplete and needs to be fixed!

This method performs a XOR encryption with a repeating key.
The method prototype is `xorEncryption(data, key, outputAsString = false)`.
`data` and `key` can be a `string` or an `array` of integers ranging from 0 to 255. You have to handle both cases.
If `outputAsString` is set to `true`, you have to convert the result of your encryption as a string

### Acceptance Criteria:
1. Running `yarn test xorEncryption` results in tests passing.
2. You have written a skeleton method for someone else to work on.
3. You have written tests surrounding your skeleton method.
4. Running `yarn lint` does not print any errors to the console!
5. Optional: write one or two more tests surrounding the method you are solving to account for potential edge cases.

### Please include the skeleton of a new method + an accompanying test for someone else to work on at the time of creating a pull request! A pull request will most likely be denied if it does not contain a skeleton method for someone else to work on! For more information, please read the [Contributing Guide](https://github.com/BlakeGuilloud/ganon/blob/master/CONTRIBUTING.md).

Thank you so much for your contribution!

**Comment by rgehan** [comment]
Please wait that #430 be merged before attempting this one; the method won't be available before

**Comment by BlakeGuilloud** [comment]
Merged. Thanks @rgehan !

**Comment by vikene** [comment]
@BlakeGuilloud I would like to work on this 👍

**Comment by BlakeGuilloud** [comment]
Sounds good @vikene !

**Comment by vikene** [comment]
@BlakeGuilloud I find two files with same name, https://github.com/BlakeGuilloud/ganon/blob/master/test/convertPoundToKilograms.test.js
https://github.com/BlakeGuilloud/ganon/blob/master/test/convertPoundtoKilograms.test.js

I guess one should be deleted.
