### ISSUE TITLE
fix findAll method

### ISSUE THREAD

**Issue by zuzanatoldyova** [BlakeGuilloud/ganon#438]
There is currently a method called `findAll` that lives in `/lib/findAll.js`.
It is incomplete and needs to be fixed!

Method excepts two arguments, an array and an element, it is supposed to return an array of indices of all the element positions in a given array.

### Acceptance Criteria:
1. Running `yarn test findAll` results in tests passing.
2. You have written a skeleton method for someone else to work on.
3. You have written tests surrounding your skeleton method.
4. Running `yarn lint` does not print any errors to the console!
5. Optional: write one or two more tests surrounding the method you are solving to account for potential edge cases.

### Please include the skeleton of a new method + an accompanying test for someone else to work on at the time of creating a pull request! A pull request will most likely be denied if it does not contain a skeleton method for someone else to work on! For more information, please read the [Contributing Guide](https://github.com/BlakeGuilloud/ganon/blob/master/CONTRIBUTING.md).

Thank you so much for your contribution!

**Comment by saiftase** [comment]
I'm on it!

**Comment by darthgera123** [comment]
Ill work on it as well

**Comment by ktilcu** [comment]
@darthgera123 sorry. We only want one person at a time. @saiftase I see your PR and I will take a peek at it.

**Comment by darthgera123** [comment]
Ill work on it as well
