### ISSUE TITLE
Fix gcd method

### ISSUE THREAD

**Issue by mmartinsky** [BlakeGuilloud/ganon#44]
There is currently a method called `gcd` that lives in `/lib/gcd.js`.
It is incomplete and needs to be fixed!

### Acceptance Criteria:
1. Running `yarn test gcd` results in tests passing.

#### Please include the skeleton of a new method + an accompanying test for someone else to work on at the time of creating a pull request!

**Comment by shinning91** [comment]
Taking a look at this now

**Comment by aimananees** [comment]
I get this error, when i run yarn test gcd 
TypeError: gcd is not a function
      at Object.<anonymous>.test (test/gcd.test.js:4:10)
      at process._tickCallback (internal/process/next_tick.js:103:7)
Only fifth test-case is passing

**Comment by mmartinsky** [comment]
Add it as a require in the index file?

**Comment by aimananees** [comment]
Made changes to index.js file. Please review my pull request.

**Comment by BlakeGuilloud** [comment]
@aimananees You are going to need to pull down the latest master, resolve the merge conflicts, and push it back up. I'm going to remove your other Pull Requests and keep this one #65  open until the conflicts are resolved. Thanks!

**Comment by aimananees** [comment]
33a7eb8 Merged with latest master 👍

**Comment by aimananees** [comment]
5372533 Merged with latest master

**Comment by aimananees** [comment]
53b3545 Merged with latest master

**Comment by andreasgruenh** [comment]
This has been fixed.
