### ISSUE TITLE
fix decrement function

### ISSUE THREAD

**Issue by BlakeGuilloud** [BlakeGuilloud/ganon#45]
There is currently a method called `decrement` that lives in `/lib/decrement.js`.
It is incomplete and needs to be fixed!

### Acceptance Criteria:
1. Running `yarn test decrement` results in tests passing.

#### Please include the skeleton of a new method + an accompanying test for someone else to work on at the time of creating a pull request!

**Comment by UmenR** [comment]
Hi the tests for decrement are wrong they have the increment function. do you mind if i change it?

**Comment by BlakeGuilloud** [comment]
Not at all! Go for it

**Comment by Dnguye92** [comment]
First-time Hacktoberfest-er here. Is this only available to one person to take a crack at these or can anyone make a pull request and give it a shot? @BlakeGuilloud

**Comment by andreasgruenh** [comment]
Hey @Dnguye92 we will wait 24 hours after the first person called dips on the issue, after that, we will merge the first PR that can be merged without conflicts.
