### ISSUE TITLE
Fix convertKelvinToRankine method

### ISSUE THREAD

**Issue by xxnatc** [BlakeGuilloud/ganon#450]
There is currently a method called `convertKelvinToRankine ` that lives in `/lib/convertKelvinToRankine.js`.
It is incomplete and needs to be fixed!

### Description:
The [Rankine](https://en.wikipedia.org/wiki/Rankine_scale) and [Kelvin](https://en.wikipedia.org/wiki/Kelvin) scales are both absolute scales used to measure temperature. This method takes an input of Kelvin and converts it into Rankine. 

### Acceptance Criteria:
1. Running `yarn test convertKelvinToRankine` results in tests passing.
2. You have written a skeleton method for someone else to work on.
3. You have written tests surrounding your skeleton method.
4. Running `yarn lint` does not print any errors to the console!
5. Optional: write one or two more tests surrounding the method you are solving to account for potential edge cases.

### Please include the skeleton of a new method + an accompanying test for someone else to work on at the time of creating a pull request! A pull request will most likely be denied if it does not contain a skeleton method for someone else to work on! For more information, please read the [Contributing Guide](https://github.com/BlakeGuilloud/ganon/blob/master/CONTRIBUTING.md).

Thank you so much for your contribution!

**Comment by EvilEpicCoder** [comment]
I would like to take this #434

**Comment by EvilEpicCoder** [comment]
I will take this #450

**Comment by BlakeGuilloud** [comment]
Thanks @EvilEpicCoder !
