### ISSUE TITLE
Fix findPair method.

### ISSUE THREAD

**Issue by saiftase** [BlakeGuilloud/ganon#452]
There is currently a method called `findPair` that lives in `/lib/findPair.js`.
It is incomplete and needs to be fixed!

Given a desired sum and an array of integers, findPair returns the first set of two array elements that, if added together, would result in the desired sum.

For example findPair(7, [1, 4, 5, 3, 6]) would be expected to return [4, 3]

### Acceptance Criteria:
1. Running `yarn test findPair` results in tests passing.
2. You have written a skeleton method for someone else to work on.
3. You have written tests surrounding your skeleton method.
4. Running `yarn lint` does not print any errors to the console!
5. Optional: write one or two more tests surrounding the method you are solving to account for potential edge cases.

### Please include the skeleton of a new method + an accompanying test for someone else to work on at the time of creating a pull request! A pull request will most likely be denied if it does not contain a skeleton method for someone else to work on! For more information, please read the [Contributing Guide](https://github.com/BlakeGuilloud/ganon/blob/master/CONTRIBUTING.md).

Thank you so much for your contribution!

**Comment by josephbhunt** [comment]
I'm working on this one.

**Comment by BlakeGuilloud** [comment]
Thanks @josephbhunt

**Comment by BlakeGuilloud** [comment]
I'm going to open this back up 💃

**Comment by damon-myers** [comment]
@BlakeGuilloud, I'll take care of this!

**Comment by BlakeGuilloud** [comment]
Hey @damon-myers ! Make a quick change request in your PR. Resolve the  linting error and we can get this in! Thanks!
