### ISSUE TITLE
Fix convertPoundToKilograms Methods

### ISSUE THREAD

**Issue by freebird1195** [BlakeGuilloud/ganon#454]
There is currently a method called `<convertPoundToKilograms>` that lives in `/lib/<convertPoundToKilograms>.js`.
It is incomplete and needs to be fixed!

The method converts pounds to Kilograms where 1 pound is equal to 0.45 kilograms.

### Acceptance Criteria:
1. Running `yarn test <convertPoundToKilograms>` results in tests passing.
2. You have written a skeleton method for someone else to work on.
3. You have written tests surrounding your skeleton method.
4. Running `yarn lint` does not print any errors to the console!
5. Optional: write one or two more tests surrounding the method you are solving to account for potential edge cases.

### Please include the skeleton of a new method + an accompanying test for someone else to work on at the time of creating a pull request! A pull request will most likely be denied if it does not contain a skeleton method for someone else to work on! For more information, please read the [Contributing Guide](https://github.com/BlakeGuilloud/ganon/blob/master/CONTRIBUTING.md).

Thank you so much for your contribution!

**Comment by darthgera123** [comment]
ill work on this issue

**Comment by darthgera123** [comment]
There is no such method file in the directory, so do i create one?

**Comment by freebird1195** [comment]
@darthgera123 I've made a pull request. It's yet to be merged, then you'll see the file.
