### ISSUE TITLE
convertMinutesToSeconds

### ISSUE THREAD

**Issue by darthgera123** [BlakeGuilloud/ganon#461]
There is currently a method called `<convertMinutesToSeconds>` that lives in `/lib/<convertMinutesToSeconds>.js`.
It is incomplete and needs to be fixed!

This method converts minutes to seconds. 1 minute amounts to 60 seconds. May the force be with you.
### Acceptance Criteria:
1. Running `yarn test <convertMinutesToSeconds>` results in tests passing.
2. You have written a skeleton method for someone else to work on.
3. You have written tests surrounding your skeleton method.
4. Running `yarn lint` does not print any errors to the console!
5. Optional: write one or two more tests surrounding the method you are solving to account for potential edge cases.

### Please include the skeleton of a new method + an accompanying test for someone else to work on at the time of creating a pull request! A pull request will most likely be denied if it does not contain a skeleton method for someone else to work on! For more information, please read the [Contributing Guide](https://github.com/BlakeGuilloud/ganon/blob/master/CONTRIBUTING.md).

Thank you so much for your contribution!

**If you are unable to view it in your local repo then it is yet to be merged please wait**

**Comment by jturinetti** [comment]
@BlakeGuilloud I can take this one.

**Comment by BlakeGuilloud** [comment]
Hey guys. Sorry- this hasn't been merged in yet. I"m going to apply the appropriate label.

**Comment by jturinetti** [comment]
Whoops, didn't see the earlier comment.  I'll hold off.

**Comment by BlakeGuilloud** [comment]
Either of you want this- it's available.

**Comment by Michelle12188** [comment]
@BlakeGuilloud I can take this if no one else is going to take it? :)

**Comment by BlakeGuilloud** [comment]
Yeah absolutely @Michelle12188 ! Thanks
