### ISSUE TITLE
Fix hsv2rgb function

### ISSUE THREAD

**Issue by smehta11** [BlakeGuilloud/ganon#469]
There is currently a method called `hsv2rgb` that lives in `/lib/hsv2rgb.js`.
It is incomplete and needs to be fixed!

This function takes an array of HSV values and returns the RGB equivalent.

### Acceptance Criteria:
1. Running `yarn test <methodName>` results in tests passing.
2. You have written a skeleton method for someone else to work on.
3. You have written tests surrounding your skeleton method.
4. Running `yarn lint` does not print any errors to the console!
5. Optional: write one or two more tests surrounding the method you are solving to account for potential edge cases.

### Please include the skeleton of a new method + an accompanying test for someone else to work on at the time of creating a pull request! A pull request will most likely be denied if it does not contain a skeleton method for someone else to work on! For more information, please read the [Contributing Guide](https://github.com/BlakeGuilloud/ganon/blob/master/CONTRIBUTING.md).

Thank you so much for your contribution!

**Comment by joshuafbarker** [comment]
I can take this one.

**Comment by BlakeGuilloud** [comment]
Thanks!

**Comment by joshuafbarker** [comment]
@smehta11  The tests seem to be off on the conversions.

According to [https://codebeautify.org/hsv-to-rgb-converter](https://codebeautify.org/hsv-to-rgb-converter), [120, 1, 1] converts to [255, 0 , 0] , not [0, 255, 0], which is what the test is asking for.

**Comment by smehta11** [comment]
@joshuafbarker Hue is typically given in degrees. However, that converter requires hue to be mapped to [0, 1] if saturation and value are also on that range (which is the norm). Instead of 120 degrees, try 0.333 for the hue (for that specific converter).

**Comment by joshuafbarker** [comment]
Ah... I see now. Thanks for the clarification.
