### ISSUE TITLE
Fix caesarsCipher function

### ISSUE THREAD

**Issue by davidkwan95** [BlakeGuilloud/ganon#474]
There is currently a method called `caesarsCipher` that lives in `/lib/caesarCipher.js`.
It is incomplete and needs to be fixed!

`caesarsCipher` takes in a string and "encrypts" it by shifting the letters by a predefined amount. This function will implement a ROT13 cipher, meaning each letter will shift 13 places in the alphabet.

### Acceptance Criteria:
1. Running `yarn test <methodName>` results in tests passing.
2. You have written a skeleton method for someone else to work on.
3. You have written tests surrounding your skeleton method.
4. Running `yarn lint` does not print any errors to the console!
5. Optional: write one or two more tests surrounding the method you are solving to account for potential edge cases.

### Please include the skeleton of a new method + an accompanying test for someone else to work on at the time of creating a pull request! A pull request will most likely be denied if it does not contain a skeleton method for someone else to work on! For more information, please read the [Contributing Guide](https://github.com/BlakeGuilloud/ganon/blob/master/CONTRIBUTING.md).

Thank you so much for your contribution!

**Comment by davidkwan95** [comment]
@BlakeGuilloud I would like to work on this one

**Comment by ktilcu** [comment]
@davidkwan95 You know the drill ;P
