### ISSUE TITLE
Fix isDivisibleBy function

### ISSUE THREAD

**Issue by gballesteros10** [BlakeGuilloud/ganon#478]
There is currently a method called `isDivisibleBy` that lives in `/lib/isDivisibleBy.js`.
It is incomplete and needs to be fixed!

`isDivisibleBy` is a function that checks if a number is divisible by a set of divisors

### Acceptance Criteria:
1. Running `yarn test <methodName>` results in tests passing.
2. You have written a skeleton method for someone else to work on.
3. You have written tests surrounding your skeleton method.
4. Running `yarn lint` does not print any errors to the console!
5. Optional: write one or two more tests surrounding the method you are solving to account for potential edge cases.

### Please include the skeleton of a new method + an accompanying test for someone else to work on at the time of creating a pull request! A pull request will most likely be denied if it does not contain a skeleton method for someone else to work on! For more information, please read the [Contributing Guide](https://github.com/BlakeGuilloud/ganon/blob/master/CONTRIBUTING.md).

Thank you so much for your contribution!

**Comment by JJEEGG2211** [comment]
@BlakeGuilloud 
Mine please

**Comment by ktilcu** [comment]
@JJEEGG2211 you know the drill!

**Comment by JJEEGG2211** [comment]
Alright! Created the PR for this. Thanks @ktilcu 
Hope I didn't make a mistake doing the PR. 😃
