### ISSUE TITLE
Fix isConsonant function

### ISSUE THREAD

**Issue by polo123qwe** [BlakeGuilloud/ganon#480]
There is currently a method called `isConsonant` that lives in `/lib/isConsonant.js`.
It is incomplete and needs to be fixed!

This method will return true if the parameter passed is a consonant, if its not it will return false.

### Acceptance Criteria:
1. Running `yarn test isConsonant` results in tests passing.
2. You have written a skeleton method for someone else to work on.
3. You have written tests surrounding your skeleton method.
4. Running `yarn lint` does not print any errors to the console!
5. Optional: write one or two more tests surrounding the method you are solving to account for potential edge cases.

### Please include the skeleton of a new method + an accompanying test for someone else to work on at the time of creating a pull request! A pull request will most likely be denied if it does not contain a skeleton method for someone else to work on! For more information, please read the [Contributing Guide](https://github.com/BlakeGuilloud/ganon/blob/master/CONTRIBUTING.md).

Thank you so much for your contribution!

**Comment by vincealdrin** [comment]
@BlakeGuilloud I'll take this

**Comment by ktilcu** [comment]
@vincealdrin I'll lock this down for 24 hours while you work on it. Enjoy!
