### ISSUE TITLE
Fix method "convertLitersPer100KilometerToMilesPerGallon"

### ISSUE THREAD

**Issue by LSBOSS** [BlakeGuilloud/ganon#487]
There is currently a method called `convertLitersPer100KilometerToMilesPerGallon` that lives in `/lib/convertLitersPer100KilometerToMilesPerGallon.js`.
It is incomplete and needs to be fixed!

This functions converts fuel consumption specifications given in liter per 100km in miles per gallon. 
See Wikipedia page for more details: [Link](https://en.wikipedia.org/wiki/Fuel_economy_in_automobiles#Conversion_from_km.2FL_and_L.2F100.C2.A0km)

Also have a look at `convertMilesPerGallonToLitersPer100Kilometer.js` which is already implemented and try to use pre-existing functions `convertKilometerToMile` and `convertLiterToGallon`. 

Happy Hacktoberfest everyone 🎃

### Acceptance Criteria:
1. Running `yarn test convertLitersPer100KilometerToMilesPerGallon` results in tests passing.
2. You have written a skeleton method for someone else to work on.
3. You have written tests surrounding your skeleton method.
4. Running `yarn lint` does not print any errors to the console!
5. Optional: write one or two more tests surrounding the method you are solving to account for potential edge cases.

### Please include the skeleton of a new method + an accompanying test for someone else to work on at the time of creating a pull request! A pull request will most likely be denied if it does not contain a skeleton method for someone else to work on! For more information, please read the [Contributing Guide](https://github.com/BlakeGuilloud/ganon/blob/master/CONTRIBUTING.md).

Thank you so much for your contribution!

**Comment by jtiala** [comment]
@BlakeGuilloud I would like to work on this

**Comment by BlakeGuilloud** [comment]
You got it!
