### ISSUE TITLE
Determine whether node in a directed graph isReachable().

### ISSUE THREAD

**Issue by saiftase** [BlakeGuilloud/ganon#488]
There is currently a method called `isReachable` that lives in `/lib/isReachable.js`.
It is incomplete and needs to be fixed!

A directed graph is represented as an array of 'edges'. Each 'edge' is composed of a start and end node.

For example:
[{from: 'A', to: 'C'},
    {from: 'B', to: 'D'},
    {from: 'C', to: 'E'},
    {from: 'D', to: 'A'},
    {from: 'E', to: 'F'}]

Given a directed graph, a character representing a start node, and a character representing a destination, determine whether it is possible to reach that destination by beginning at the start and traversing the graph.

### Acceptance Criteria:
1. Running `yarn test isReachable` results in tests passing.
2. You have written a skeleton method for someone else to work on.
3. You have written tests surrounding your skeleton method.
4. Running `yarn lint` does not print any errors to the console!
5. Optional: write one or two more tests surrounding the method you are solving to account for potential edge cases.

### Please include the skeleton of a new method + an accompanying test for someone else to work on at the time of creating a pull request! A pull request will most likely be denied if it does not contain a skeleton method for someone else to work on! For more information, please read the [Contributing Guide](https://github.com/BlakeGuilloud/ganon/blob/master/CONTRIBUTING.md).

Thank you so much for your contribution!

**Comment by N0V0S** [comment]
i'd like to work on this one :)
