### ISSUE TITLE
fix 'partial' function

### ISSUE THREAD

**Issue by mr-rodgers** [BlakeGuilloud/ganon#489]
There is currently a method called `partial` that lives in `/lib/partial.js`.
It is incomplete and needs to be fixed!

`partial` wraps a function *f* and return a new function *g* that when invoked, will call *f* with the arguments provided to `partial` prepended to the argument list provided to *g*.

### Acceptance Criteria:
1. Running `yarn test partial` results in tests passing.
2. You have written a skeleton method for someone else to work on.
3. You have written tests surrounding your skeleton method.
4. Running `yarn lint` does not print any errors to the console!
5. Optional: write one or two more tests surrounding the method you are solving to account for potential edge cases.

### Please include the skeleton of a new method + an accompanying test for someone else to work on at the time of creating a pull request! A pull request will most likely be denied if it does not contain a skeleton method for someone else to work on! For more information, please read the [Contributing Guide](https://github.com/BlakeGuilloud/ganon/blob/master/CONTRIBUTING.md).

Thank you so much for your contribution!

**Comment by darthgera123** [comment]
ill work on this

**Comment by sebassdc** [comment]
@BlakeGuilloud I would like to work on this.Its already taken?

**Comment by BlakeGuilloud** [comment]
Yeah absolutely! Thanks! @sebassdc

**Comment by sebassdc** [comment]
When you pass a function as an argumentis a reference of the function itself. You cannot expect to create a new instance of the function because thats not posible in a simple an right way on javascript. It would make a mess the codebase.
