### ISSUE TITLE
Fix prime function

### ISSUE THREAD

**Issue by BlakeGuilloud** [BlakeGuilloud/ganon#49]
There is currently a method called `prime` that lives in `/lib/prime.js`.
It is incomplete and needs to be fixed!

### Acceptance Criteria:
1. Running `yarn test prime` results in tests passing.

#### Please include the skeleton of a new method + an accompanying test for someone else to work on at the time of creating a pull request!

**Comment by Phlegz** [comment]
@BlakeGuilloud Hi :) Is there a way that I could add an "in progress" label to any of the open issues so nobody else would work on it at the same time? Thanks.

**Comment by BlakeGuilloud** [comment]
Nice wokr @Phlegz ! Closing this out.
