### ISSUE TITLE
Implement split

### ISSUE THREAD

**Issue by azdavis** [BlakeGuilloud/ganon#498]
There is currently a method called `split` that lives in `/lib/split.js`.
It is incomplete and needs to be fixed!

- `split` should take in an Array and return an Object containing two Arrays.
- If the input array has even length, i.e. length 2n for some non-negative integer n, then the length of each of the two arrays should be n. If the input array has odd length, i.e. length 2n + 1, then the length of the first array should be n + 1 and the length of the second array should be n.
- It should be that concat'ing the first array with the second is the same as the original array.

### Acceptance Criteria:
1. Running `yarn test split` results in tests passing.
2. You have written a skeleton method for someone else to work on.
3. You have written tests surrounding your skeleton method.
4. Running `yarn lint` does not print any errors to the console!
5. Optional: write one or two more tests surrounding the method you are solving to account for potential edge cases.

### Please include the skeleton of a new method + an accompanying test for someone else to work on at the time of creating a pull request! A pull request will most likely be denied if it does not contain a skeleton method for someone else to work on! For more information, please read the [Contributing Guide](https://github.com/BlakeGuilloud/ganon/blob/master/CONTRIBUTING.md).

Thank you so much for your contribution!

**Comment by sebassdc** [comment]
@BlakeGuilloud I would like to work on this :D

**Comment by BlakeGuilloud** [comment]
You got it @sebassdc !
