### ISSUE TITLE
Fix pull method

### ISSUE THREAD

**Issue by vincealdrin** [BlakeGuilloud/ganon#500]
There is currently a method called `pull` that lives in `/lib/pull.js`.
It is incomplete and needs to be fixed!

### Acceptance Criteria:
1. Running `yarn test pull` results in tests passing.
2. You have written a skeleton method for someone else to work on.
3. You have written tests surrounding your skeleton method.
4. Running `yarn lint` does not print any errors to the console!
5. Optional: write one or two more tests surrounding the method you are solving to account for potential edge cases.

### Please include the skeleton of a new method + an accompanying test for someone else to work on at the time of creating a pull request! A pull request will most likely be denied if it does not contain a skeleton method for someone else to work on! For more information, please read the [Contributing Guide](https://github.com/BlakeGuilloud/ganon/blob/master/CONTRIBUTING.md).

Thank you so much for your contribution!

**Comment by sebassdc** [comment]
@BlakeGuilloud I would like to work on this. Im on fire!!! :fire:

**Comment by BlakeGuilloud** [comment]
OK @sebassdc ! Just make sure you write a new skeleton method for someone else for each method you solve.

**Comment by sebassdc** [comment]
Ok i'll do my best :D
