### ISSUE TITLE
Fix getBiconditional function

### ISSUE THREAD

**Issue by amoradi** [BlakeGuilloud/ganon#501]
There is currently a method called `getBiconditional` that lives in `/lib/getBiconditional.js`.
It is incomplete and needs to be fixed!

"Logical equality (also known as biconditional) is an operation on two logical values, typically the values of two propositions, that produces a value of true if and only if both operands are false or both operands are true."
See https://en.wikipedia.org/wiki/Logical_biconditional

### Acceptance Criteria:
1. Running `yarn test getBiconditional` results in tests passing.
2. You have written a skeleton method for someone else to work on.
3. You have written tests surrounding your skeleton method.
4. Running `yarn lint` does not print any errors to the console!
5. Optional: write one or two more tests surrounding the method you are solving to account for potential edge cases.

### Please include the skeleton of a new method + an accompanying test for someone else to work on at the time of creating a pull request! A pull request will most likely be denied if it does not contain a skeleton method for someone else to work on! For more information, please read the [Contributing Guide](https://github.com/BlakeGuilloud/ganon/blob/master/CONTRIBUTING.md).

Thank you so much for your contribution!

**Comment by sebassdc** [comment]
@BlakeGuilloud I would like to work on this

**Comment by BlakeGuilloud** [comment]
It's yours @sebassdc !

**Comment by sebassdc** [comment]
This doesn't have a skeleton

**Comment by amoradi** [comment]
@sebassdc It looks like it is misnamed `getBiconditional.test.js`. Feel free to change it to the correct name! Apologies!

**Comment by sebassdc** [comment]
@amoradi its my fault its already merged i doesn't check correctly. Sorry :/
