### ISSUE TITLE
Fix arrayVariance function

### ISSUE THREAD

**Issue by Michelle12188** [BlakeGuilloud/ganon#503]
There is currently a method called `<arrayVariance>` that lives in `/lib/<arrayVariance>.js`.
It is incomplete and needs to be fixed!

This method takes in a number array e.g. [1, 2, 3, 4] and returns the variance of the array

### Acceptance Criteria:
1. Running `yarn test <arrayVariance>` results in tests passing.
2. You have written a skeleton method for someone else to work on.
3. You have written tests surrounding your skeleton method.
4. Running `yarn lint` does not print any errors to the console!
5. Optional: write one or two more tests surrounding the method you are solving to account for potential edge cases.

### Please include the skeleton of a new method + an accompanying test for someone else to work on at the time of creating a pull request! A pull request will most likely be denied if it does not contain a skeleton method for someone else to work on! For more information, please read the [Contributing Guide](https://github.com/BlakeGuilloud/ganon/blob/master/CONTRIBUTING.md).

Thank you so much for your contribution!

If you are unable to view it in your local repo then it is yet to be merged please wait

**Comment by gballesteros10** [comment]
@BlakeGuilloud I'll take this. But I think the skeleton isn't merged yet.

**Comment by BlakeGuilloud** [comment]
hey @gballesteros10 ! just merged it in. Go for it!
