### ISSUE TITLE
Scientific Notation

### ISSUE THREAD

**Issue by FranceJ** [BlakeGuilloud/ganon#506]
There is currently a method called `scientificNotation` that lives in `/lib/scientificNotation.js`.
It is incomplete and needs to be fixed!

This method should take in a float and output a string that can be used in an HTML document of the form `3.25 x 10<sup>2</sup>. It should also take a second argument which specifies the number of significant digits to include.

### Acceptance Criteria:
1. Running `yarn test scientificNotation` results in tests passing.
2. You have written a skeleton method for someone else to work on.
3. You have written tests surrounding your skeleton method.
4. Running `yarn lint` does not print any errors to the console!
5. Optional: write one or two more tests surrounding the method you are solving to account for potential edge cases.

This method can not be worked on until PR #505 is merged.

### Please include the skeleton of a new method + an accompanying test for someone else to work on at the time of creating a pull request! A pull request will most likely be denied if it does not contain a skeleton method for someone else to work on! For more information, please read the [Contributing Guide](https://github.com/BlakeGuilloud/ganon/blob/master/CONTRIBUTING.md).

Thank you so much for your contribution!

**Comment by showmeyourhits** [comment]
@BlakeGuilloud would love to work on dis

**Comment by BlakeGuilloud** [comment]
Sounds good @showmeyourhits ! Go for it.
