### ISSUE TITLE
Fix sumPrimes method

### ISSUE THREAD

**Issue by adamjq** [BlakeGuilloud/ganon#508]
There is currently a method called `sumPrimes` that lives in `/lib/sumPrimes.js`.
It is incomplete and needs to be fixed!

The method returns the sum of all the prime numbers up to and including the provided number. The provided number will be a positive integer.

For example, sumPrimes(10) will return 17, as 2+3+5+7 = 17.

### Acceptance Criteria:
1. Running `yarn test <methodName>` results in tests passing.
2. You have written a skeleton method for someone else to work on.
3. You have written tests surrounding your skeleton method.
4. Running `yarn lint` does not print any errors to the console!
5. Optional: write one or two more tests surrounding the method you are solving to account for potential edge cases.

### Please include the skeleton of a new method + an accompanying test for someone else to work on at the time of creating a pull request! A pull request will most likely be denied if it does not contain a skeleton method for someone else to work on! For more information, please read the [Contributing Guide](https://github.com/BlakeGuilloud/ganon/blob/master/CONTRIBUTING.md).

Thank you so much for your contribution!

**Comment by roseg43** [comment]
@BlakeGuilloud I'd like to take a stab at this.
