### ISSUE TITLE
fix convertInchesToCentimeters function

### ISSUE THREAD

**Issue by paolomangiadev** [BlakeGuilloud/ganon#518]
There is currently a method called `convertInchesToCentimeters` that lives in `/lib/convertInchesToCentimeters.js`.
It is incomplete and needs to be fixed!

**Description:** 
A number indicating a measurement in inches is passed to the method and the return is the same measurement  converted in centimeters. e.g. 7in => 17.78003556007112cm

### Acceptance Criteria:
1. Running `yarn test convertInchesToCentimeters` results in tests passing.
2. You have written a skeleton method for someone else to work on.
3. You have written tests surrounding your skeleton method.
4. Running `yarn lint` does not print any errors to the console!
5. Optional: 
  - write one or two more tests surrounding the method you are solving to account for potential edge cases.
  - add the option of rounding the resulting measurement (centimeters).

### Please include the skeleton of a new method + an accompanying test for someone else to work on at the time of creating a pull request! A pull request will most likely be denied if it does not contain a skeleton method for someone else to work on! For more information, please read the [Contributing Guide](https://github.com/BlakeGuilloud/ganon/blob/master/CONTRIBUTING.md).

Thank you so much for your contribution!

**Comment by lmauromb** [comment]
I'll take it!

**Comment by roseg43** [comment]
Was just taking a look at this and @paolomangiadev , it looks like the initial tests for this method pass no matter what. 

The expect in "Should return converted inches to centimeters" always evaluates to true. Something to keep in mind @lmauromb

**Comment by BlakeGuilloud** [comment]
Marking as in progress. @lmauromb - take a look at those tests while you're digging around, thanks!!
