### ISSUE TITLE
fix isArrayEqual

### ISSUE THREAD

**Issue by Peradon** [BlakeGuilloud/ganon#523]
There is currently a method called `isArrayEqual` that lives in `/lib/isArrayEqual.js`.
It is incomplete and needs to be fixed!

This method should return whether both of the input arrays are equal or not, ignore the element order in the arrays. e.g isArrayEqual([1,2,3], [3,1,2]) => true

### Acceptance Criteria:
1. Running `yarn test isArrayEqual` results in tests passing.
2. You have written a skeleton method for someone else to work on.
3. You have written tests surrounding your skeleton method.
4. Running `yarn lint` does not print any errors to the console!
5. Optional: write one or two more tests surrounding the method you are solving to account for potential edge cases.

### Please include the skeleton of a new method + an accompanying test for someone else to work on at the time of creating a pull request! A pull request will most likely be denied if it does not contain a skeleton method for someone else to work on! For more information, please read the [Contributing Guide](https://github.com/BlakeGuilloud/ganon/blob/master/CONTRIBUTING.md).

Thank you so much for your contribution!

**Comment by Peradon** [comment]
need to merge #514 first

**Comment by jturinetti** [comment]
@BlakeGuilloud I will take this when it's ready!

**Comment by BlakeGuilloud** [comment]
Hey @jturinetti ! It's been merged in, but I think there is a typo in the test:

the method is called `isArrayEqual` but the test is importing `arrayUnion`. If you fix that, it should work!

Thanks!!
`const { arrayUnion } = require("../lib"); to const { isArrayEqual } = require('../lib');`
