### ISSUE TITLE
Implement reverseArray function

### ISSUE THREAD

**Issue by sebassdc** [BlakeGuilloud/ganon#528]
There is currently a method called `reverseArray` that lives in `/lib/reverseArray.js`.
It is incomplete and needs to be fixed!

This method should not modify the original array. It will take an array an return a new array with the items in the reverse order: 
```javascript
reverseArray([1, 2, 3, 4]) // ------> [4, 3, 2, 1]
reverseArray(["pen", "pineapple", "apple", "pen"]) // --> ["pen", "apple", "pineapple", "pen"]
```
### Acceptance Criteria:
1. Running `yarn test <methodName>` results in tests passing.
2. You have written a skeleton method for someone else to work on.
3. You have written tests surrounding your skeleton method.
4. Running `yarn lint` does not print any errors to the console!
5. Optional: write one or two more tests surrounding the method you are solving to account for potential edge cases.

### Please include the skeleton of a new method + an accompanying test for someone else to work on at the time of creating a pull request! A pull request will most likely be denied if it does not contain a skeleton method for someone else to work on! For more information, please read the [Contributing Guide](https://github.com/BlakeGuilloud/ganon/blob/master/CONTRIBUTING.md).

Thank you so much for your contribution!

**Comment by sebassdc** [comment]
Requires #527 to be merged first

**Comment by kathnakon** [comment]
i want to solve this issue #528

**Comment by amoradi** [comment]
@kathnakon Thanks! It's all yours!
