### ISSUE TITLE
fix method deepCompare

### ISSUE THREAD

**Issue by jturinetti** [BlakeGuilloud/ganon#534]
There is currently a method called `deepCompare` that lives in `/lib/deepCompare.js`.
It is incomplete and needs to be fixed!

Check if all properties on the provided parameters are equal.
This should recurse through all objects in the parameters' object graph.
Equivalence should be asserted on numbers, strings, and arrays in the object graph.

### Acceptance Criteria:
1. Running `yarn test deepCompare` results in tests passing.
2. You have written a skeleton method for someone else to work on.
3. You have written tests surrounding your skeleton method.
4. Running `yarn lint` does not print any errors to the console!
5. Optional: write one or two more tests surrounding the method you are solving to account for potential edge cases.

### Please include the skeleton of a new method + an accompanying test for someone else to work on at the time of creating a pull request! A pull request will most likely be denied if it does not contain a skeleton method for someone else to work on! For more information, please read the [Contributing Guide](https://github.com/BlakeGuilloud/ganon/blob/master/CONTRIBUTING.md).

Thank you so much for your contribution!

**Comment by jturinetti** [comment]
Dependent on PR #533 being merged first.

**Comment by BlakeGuilloud** [comment]
This is ready to go!

**Comment by jbharat** [comment]
@BlakeGuilloud I would like to work on this

**Comment by BlakeGuilloud** [comment]
Cool deal @jbharat !! Thanks
