### ISSUE TITLE
Implement arrayMult function

### ISSUE THREAD

**Issue by sebassdc** [BlakeGuilloud/ganon#551]
There is currently a method called `arrayMult` that lives in `/lib/arrayMult.js`.
It is incomplete and needs to be fixed!

This method should not modify the original array.
It will ignore anything that is not a number. 
It will take an array of numbers an return the result of all the items multiplied.
Ex:
```javascript
arrayMult([1, 2, 3, 4]) // ---> 24
arrayMult([3, "test", 0, 4] // ---> 0
arrayMult([]) // --> 0
arrayMult(["pen", "pineapple", "apple", "pen"]) // --> 0
```
### Acceptance Criteria:
1. Running `yarn test arrayMult` results in tests passing.
2. You have written a skeleton method for someone else to work on.
3. You have written tests surrounding your skeleton method.
4. Running `yarn lint` does not print any errors to the console!
5. Optional: write one or two more tests surrounding the method you are solving to account for potential edge cases.

### Please include the skeleton of a new method + an accompanying test for someone else to work on at the time of creating a pull request! A pull request will most likely be denied if it does not contain a skeleton method for someone else to work on! For more information, please read the [Contributing Guide](https://github.com/BlakeGuilloud/ganon/blob/master/CONTRIBUTING.md).

Thank you so much for your contribution!

**Comment by sebassdc** [comment]
Requires  #550  to be merged first

**Comment by rinkal-rohara** [comment]
#551 @BlakeGuilloud I would like to work on this
