### ISSUE TITLE
Implement isHeterogram function

### ISSUE THREAD

**Issue by sebassdc** [BlakeGuilloud/ganon#553]
There is currently a method called `isHeterogram` that lives in `/lib/isHeterogram.js`.
It is incomplete and needs to be fixed!

This function will only accept strings. 
It should return true if all the letters in the string are unique (ignoring whitespaces)
Ex:

```javascript
isHeterogram("caperingly") // ----> true
isHeterogram("lacqueying") // ----> true
isHeterogram("Mi mama me mima") // ----> false
```

### Acceptance Criteria:
1. Running `yarn test isHeterogram` results in tests passing.
2. You have written a skeleton method for someone else to work on.
3. You have written tests surrounding your skeleton method.
4. Running `yarn lint` does not print any errors to the console!
5. Optional: write one or two more tests surrounding the method you are solving to account for potential edge cases.

### Please include the skeleton of a new method + an accompanying test for someone else to work on at the time of creating a pull request! A pull request will most likely be denied if it does not contain a skeleton method for someone else to work on! For more information, please read the [Contributing Guide](https://github.com/BlakeGuilloud/ganon/blob/master/CONTRIBUTING.md).

Thank you so much for your contribution!

**Comment by sebassdc** [comment]
Requires #552 to be merged first

**Comment by jbharat** [comment]
@BlakeGuilloud I would like to work on this

**Comment by BlakeGuilloud** [comment]
Hey @jbharat ! It has been merged in. Hack away!!
