### ISSUE TITLE
Fix isEmpty function

### ISSUE THREAD

**Issue by davidkwan95** [BlakeGuilloud/ganon#554]
There is currently a method called `isEmpty` that lives in `/lib/isEmpty.js`.
It is incomplete and needs to be fixed!

 isEmpty is a function that receives either an array or object which returns true when it is empty.
An array is empty when it has length === 0, i.e. []
An object is empty when it has no keys, i.e. {}

### Acceptance Criteria:
1. Running `yarn test <methodName>` results in tests passing.
2. You have written a skeleton method for someone else to work on.
3. You have written tests surrounding your skeleton method.
4. Running `yarn lint` does not print any errors to the console!
5. Optional: write one or two more tests surrounding the method you are solving to account for potential edge cases.

### Please include the skeleton of a new method + an accompanying test for someone else to work on at the time of creating a pull request! A pull request will most likely be denied if it does not contain a skeleton method for someone else to work on! For more information, please read the [Contributing Guide](https://github.com/BlakeGuilloud/ganon/blob/master/CONTRIBUTING.md).

Thank you so much for your contribution!

**Comment by bhargodevarya** [comment]
I am taking this

**Comment by janclarin** [comment]
Sorry @bhargodevarya, I should've called this 😓

**Comment by alangak** [comment]
#Hacktoberfest @Infosys
