### ISSUE TITLE
Fix pluck function

### ISSUE THREAD

**Issue by arrizalamin** [BlakeGuilloud/ganon#562]
There is currently a method called `pluck` that lives in `/lib/pluck.js`.
It is incomplete and needs to be fixed!

### Acceptance Criteria:
1. Running `yarn test pluck` results in tests passing.
2. You have written a skeleton method for someone else to work on.
3. You have written tests surrounding your skeleton method.
4. Running `yarn lint` does not print any errors to the console!
5. Optional: write one or two more tests surrounding the method you are solving to account for potential edge cases.

### Please include the skeleton of a new method + an accompanying test for someone else to work on at the time of creating a pull request! A pull request will most likely be denied if it does not contain a skeleton method for someone else to work on! For more information, please read the [Contributing Guide](https://github.com/BlakeGuilloud/ganon/blob/master/CONTRIBUTING.md).

Thank you so much for your contribution!

**Comment by arrizalamin** [comment]
Requires #563 to be merged first

**Comment by Soben** [comment]
I'll give this a shot as well, if you don't mind.

My only thing was that coming up with the Skeleton methods. I have zero ideas right now but I'll create one if need be.

**Comment by Soben** [comment]
Hah, ok, just realized the BOLD TEXT ON THESE. yea... I'll have to fix my other request, too.

**Comment by BlakeGuilloud** [comment]
Hey @Soben ! I'll mark as in progress, but yeah- make sure you come up w/ a new method! It keeps the project going :) Thanks!
