### ISSUE TITLE
Fix takeUntil function

### ISSUE THREAD

**Issue by SamHowie** [BlakeGuilloud/ganon#566]
There is currently a method called `takeUntil` that lives in `/lib/takeUntil.js`.
It is incomplete and needs to be fixed!

The takeUntil function returns a slice of an array from the arrays first element, until a given predicate returns true.

For example:

```javascript
expect(takeUntil([1, 2, 3, 4], (n) => n === 4)).toEqual([1, 2, 3]);
```

### Acceptance Criteria:
1. Running `yarn test <methodName>` results in tests passing.
2. You have written a skeleton method for someone else to work on.
3. You have written tests surrounding your skeleton method.
4. Running `yarn lint` does not print any errors to the console!
5. Optional: write one or two more tests surrounding the method you are solving to account for potential edge cases.

### Please include the skeleton of a new method + an accompanying test for someone else to work on at the time of creating a pull request! A pull request will most likely be denied if it does not contain a skeleton method for someone else to work on! For more information, please read the [Contributing Guide](https://github.com/BlakeGuilloud/ganon/blob/master/CONTRIBUTING.md).

Thank you so much for your contribution!

**Comment by SamHowie** [comment]
Requires #561 to be merged first

**Comment by emilyanndavis** [comment]
This one looks fun. I'll take it, @BlakeGuilloud !

**Comment by BlakeGuilloud** [comment]
You got it @emilyanndavis !
