### ISSUE TITLE
Fix largest function

### ISSUE THREAD

**Issue by SamHowie** [BlakeGuilloud/ganon#568]
There is currently a method called `largest` that lives in `/lib/largest.js`.
It is incomplete and needs to be fixed!

The largest function takes an array and ordering function as parameters, and returns the largest item in the array.

For example:

```javascript
expect(largest([1, 2, 3, 4, 5], (a, b) => a > b)).toBe(5);
```

### Acceptance Criteria:
1. Running `yarn test <methodName>` results in tests passing.
2. You have written a skeleton method for someone else to work on.
3. You have written tests surrounding your skeleton method.
4. Running `yarn lint` does not print any errors to the console!
5. Optional: write one or two more tests surrounding the method you are solving to account for potential edge cases.

### Please include the skeleton of a new method + an accompanying test for someone else to work on at the time of creating a pull request! A pull request will most likely be denied if it does not contain a skeleton method for someone else to work on! For more information, please read the [Contributing Guide](https://github.com/BlakeGuilloud/ganon/blob/master/CONTRIBUTING.md).

Thank you so much for your contribution!

**Comment by SamHowie** [comment]
Requires #567 to be merged first

**Comment by aerohitk** [comment]
@BlakeGuilloud I would like to work on this, if that's alright?

**Comment by BlakeGuilloud** [comment]
Yeah of course @aerohitk !
