### ISSUE TITLE
Fix arrayMean function

### ISSUE THREAD

**Issue by Peradon** [BlakeGuilloud/ganon#589]
There is currently a method called `arrayMean` that lives in `/lib/arrayMean.js`.
It is incomplete and needs to be fixed!

This method will return 2-digit mean value of the numbered array, which can be either int or float, and throw an error if the argument is invalid. e.g. arrayMean([151,3,56,76,4,3]) => 48.43

### Acceptance Criteria:
1. Running `yarn test arrayMean` results in tests passing.
2. You have written a skeleton method for someone else to work on.
3. You have written tests surrounding your skeleton method.
4. Running `yarn lint` does not print any errors to the console!
5. Optional: write one or two more tests surrounding the method you are solving to account for potential edge cases.

### Please include the skeleton of a new method + an accompanying test for someone else to work on at the time of creating a pull request! A pull request will most likely be denied if it does not contain a skeleton method for someone else to work on! For more information, please read the [Contributing Guide](https://github.com/BlakeGuilloud/ganon/blob/master/CONTRIBUTING.md).

Thank you so much for your contribution!

**Comment by yugoccp** [comment]
@BlakeGuilloud I would like to work on this

**Comment by BlakeGuilloud** [comment]
Cool deal @yugoccp !

**Comment by yugoccp** [comment]
Hi @BlakeGuilloud! Maybe i'm missing something... The mean value of [151,3,56,76,4,3] should be 48.83, not 48.43 as described on test. Right?

**Comment by BlakeGuilloud** [comment]
Hey @yugoccp - yes you are correct. Sorry about that. I try my best to test all cases but sometimes they get through. great catch!

**Comment by Peradon** [comment]
Hi @yugoccp and @BlakeGuilloud Sorry about the test, I miss check there.

**Comment by yugoccp** [comment]
All right! =)
