### ISSUE TITLE
Fix volumeOfCone Function

### ISSUE THREAD

**Issue by WilliamSpruyt** [BlakeGuilloud/ganon#591]
There is currently a method called `volumeOfCone` that lives in `/lib/volumeOfCone.js`.
It is incomplete and needs to be fixed!

It takes the radius of the base and the height of a cone and returns the volume. It should throw an error for an invalid type.

### Acceptance Criteria:
1. Running `yarn test volumeOfCone` results in tests passing.
2. You have written a skeleton method for someone else to work on.
3. You have written tests surrounding your skeleton method.
4. Running `yarn lint` does not print any errors to the console!
5. Optional: write one or two more tests surrounding the method you are solving to account for potential edge cases.

### Please include the skeleton of a new method + an accompanying test for someone else to work on at the time of creating a pull request! A pull request will most likely be denied if it does not contain a skeleton method for someone else to work on! For more information, please read the [Contributing Guide](https://github.com/BlakeGuilloud/ganon/blob/master/CONTRIBUTING.md).

Thank you so much for your contribution!

**Comment by viniciuskneves** [comment]
I would like to try this one :smile:

**Comment by davcs86** [comment]
Sorry @viniciuskneves, I just created a pull request for this one, I didn't read your comment before.
