### ISSUE TITLE
Fix reverseMap function

### ISSUE THREAD

**Issue by janclarin** [BlakeGuilloud/ganon#593]
There is currently a method called `reverseMap` that lives in `/lib/reverseMap.js`.
It is incomplete and needs to be fixed!

It reverses the key-value pairings of a Map to be value-key pairings.
```
Original map             | Reversed map
key1 -> value1           | value1 -> key1
Map.get(key1) === value2 | Map.get(value1) === key1
```

### Acceptance Criteria:
1. Running `yarn test reverseMap` results in tests passing.
2. You have written a skeleton method for someone else to work on.
3. You have written tests surrounding your skeleton method.
4. Running `yarn lint` does not print any errors to the console!
5. Optional: write one or two more tests surrounding the method you are solving to account for potential edge cases.

### Please include the skeleton of a new method + an accompanying test for someone else to work on at the time of creating a pull request! A pull request will most likely be denied if it does not contain a skeleton method for someone else to work on! For more information, please read the [Contributing Guide](https://github.com/BlakeGuilloud/ganon/blob/master/CONTRIBUTING.md).

Thank you so much for your contribution!

**Comment by jamesg1** [comment]
Hi @janclarin I would like to take on this issue and complete it.

**Comment by BlakeGuilloud** [comment]
Sounds good @jamesg1 ! Thanks
