### ISSUE TITLE
Fix spellNumber function

### ISSUE THREAD

**Issue by bhargodevarya** [BlakeGuilloud/ganon#594]
There is currently a method called `spellNumber` that lives in `/lib/spellNumber.js`.
It is incomplete and needs to be fixed!

It spells the number that has been passed to it.
In case of a decimal number, it rounds up the number if the precision is about .55 i.e.
123.56 becomes 124 and below it becomes 123, spelled, one hundred twenty four and one hundred twenty four respectively.

### Acceptance Criteria:
1. Running `yarn test spellNumber` results in tests passing.
2. You have written a skeleton method for someone else to work on.
3. You have written tests surrounding your skeleton method.
4. Running `yarn lint` does not print any errors to the console!
5. Optional: write one or two more tests surrounding the method you are solving to account for potential edge cases.

### Please include the skeleton of a new method + an accompanying test for someone else to work on at the time of creating a pull request! A pull request will most likely be denied if it does not contain a skeleton method for someone else to work on! For more information, please read the [Contributing Guide](https://github.com/BlakeGuilloud/ganon/blob/master/CONTRIBUTING.md).

Thank you so much for your contribution!

**Comment by davcs86** [comment]
I'm gonna work on this. Please mark it as in progress.

**Comment by BlakeGuilloud** [comment]
you got it :)

**Comment by davcs86** [comment]
Done :)
