### ISSUE TITLE
Fix isHappyNumber function

### ISSUE THREAD

**Issue by davcs86** [BlakeGuilloud/ganon#596]
There is currently a method called `isHappyNumber` that lives in `/lib/isHappyNumber.js`.
It is incomplete and needs to be fixed!

According to [wikipedia](https://en.wikipedia.org/wiki/Happy_number):

> A **happy number** is a number defined by the following process: Starting with any positive integer, replace the number by the sum of the squares of its digits in base-ten, and repeat the process until the number either equals 1 (where it will stay), or it loops endlessly in a cycle that does not include 1. Those numbers for which this process ends in 1 are happy numbers, while those that do not end in 1 are unhappy numbers (or sad numbers).

### Acceptance Criteria:
1. Running `yarn test isHappyNumber` results in tests passing.
2. You have written a skeleton method for someone else to work on.
3. You have written tests surrounding your skeleton method.
4. Running `yarn lint` does not print any errors to the console!
5. Optional: write one or two more tests surrounding the method you are solving to account for potential edge cases.

### Please include the skeleton of a new method + an accompanying test for someone else to work on at the time of creating a pull request! A pull request will most likely be denied if it does not contain a skeleton method for someone else to work on! For more information, please read the [Contributing Guide](https://github.com/BlakeGuilloud/ganon/blob/master/CONTRIBUTING.md).

Thank you so much for your contribution!

**Comment by Soben** [comment]
I'm taking a look at this. Need to brush up on my math functions.

**Comment by davcs86** [comment]
hehe @Soben, Math is fun! :)

**Comment by BlakeGuilloud** [comment]
You got it @Soben
