### ISSUE TITLE
Fix primeNumbersUpTo function

### ISSUE THREAD

**Issue by ylorenzana** [BlakeGuilloud/ganon#612]
There is currently a method called `primeNumbersUpTo` that lives in `/lib/primeNumbersUpTo.js`.
It is incomplete and needs to be fixed!

primeNumbersUpTo takes a positive integer n and returns a list of all prime numbers up to n.

### Acceptance Criteria:
1. Running `yarn test primeNumbersUpTo` results in tests passing.
2. You have written a skeleton method for someone else to work on.
3. You have written tests surrounding your skeleton method.
4. Running `yarn lint` does not print any errors to the console!
5. Optional: write one or two more tests surrounding the method you are solving to account for potential edge cases.

### Please include the skeleton of a new method + an accompanying test for someone else to work on at the time of creating a pull request! A pull request will most likely be denied if it does not contain a skeleton method for someone else to work on! For more information, please read the [Contributing Guide](https://github.com/BlakeGuilloud/ganon/blob/master/CONTRIBUTING.md).

Thank you so much for your contribution!

**Comment by ylorenzana** [comment]
Requires #611  to be merged first.

**Comment by caffeinewriter** [comment]
Almost done with this :)
