### ISSUE TITLE
Fix debounce function

### ISSUE THREAD

**Issue by kylevv** [BlakeGuilloud/ganon#616]
There is currently a method called `debounce` that lives in `/lib/debounce.js`.
It is incomplete and needs to be fixed!

Debounce takes a callback function and wait time (ms) as arguments and returns a debounced version of the callback function.  A debounced function will only invoke the original callback after the specified amount of time has elapsed without subsequent invocations of the debounced function.  If a debounced function is called again before the first call has completed, the timer is reset.

### Acceptance Criteria:
1. Running `yarn test debounce` results in tests passing.
2. You have written a skeleton method for someone else to work on.
3. You have written tests surrounding your skeleton method.
4. Running `yarn lint` does not print any errors to the console!
5. Optional: write one or two more tests surrounding the method you are solving to account for potential edge cases.

### Please include the skeleton of a new method + an accompanying test for someone else to work on at the time of creating a pull request! A pull request will most likely be denied if it does not contain a skeleton method for someone else to work on! For more information, please read the [Contributing Guide](https://github.com/BlakeGuilloud/ganon/blob/master/CONTRIBUTING.md).

Thank you so much for your contribution!

**Comment by kylevv** [comment]
Requires #615  to be merged first.

**Comment by jbharat** [comment]
@BlakeGuilloud I want to work on this.

**Comment by BlakeGuilloud** [comment]
You got it @jbharat . thanks
