### ISSUE TITLE
Fix escapeRegExp function

### ISSUE THREAD

**Issue by jbharat** [BlakeGuilloud/ganon#621]
There is currently a method called `escapeRegExp` that lives in `/lib/escapeRegExp.js`.
It is incomplete and needs to be fixed!

This function should escape the RegExp special characters "^", "$", "", ".", "*", "+", "?", "(", ")", "[", "]", "{", "}", and "|" in string.

### Acceptance Criteria:
1. Running `yarn test escapeRegExp` results in tests passing.
2. You have written a skeleton method for someone else to work on.
3. You have written tests surrounding your skeleton method.
4. Running `yarn lint` does not print any errors to the console!
5. Optional: write one or two more tests surrounding the method you are solving to account for potential edge cases.

### Please include the skeleton of a new method + an accompanying test for someone else to work on at the time of creating a pull request! A pull request will most likely be denied if it does not contain a skeleton method for someone else to work on! For more information, please read the [Contributing Guide](https://github.com/BlakeGuilloud/ganon/blob/master/CONTRIBUTING.md).

Thank you so much for your contribution!

**Comment by jbharat** [comment]
Requires #620 to be merged

**Comment by jsjain007** [comment]
@BlakeGuilloud  I would like to work on this. Thanks.

**Comment by jsjain007** [comment]
Hi @jbharat the test cases you have for the `escapeRegExp` are wrongly put in parenthesis as in it should be `expect(escapeRegExp("4^2")).toEqual("4\^2");` but instead it is `expect(escapeRegExp("4^2").toEqual("4\^2"));`  Though I will fix it in my PR.
