### ISSUE TITLE
Fix Smallest Function

### ISSUE THREAD

**Issue by jamesg1** [BlakeGuilloud/ganon#624]
There is currently a method called `smallest` that lives in `/lib/smallest.js`.
It is incomplete and needs to be fixed!

The smallest functions takes in an array and an ordering function as parameters, and returns the smallest item in the array.

For example:
``` expect(largest([5, 4, 1, 3, 8], (a, b) => a < b)).toBe(1);```

### Acceptance Criteria:
1. Running `yarn test <methodName>` results in tests passing.
2. You have written a skeleton method for someone else to work on.
3. You have written tests surrounding your skeleton method.
4. Running `yarn lint` does not print any errors to the console!
5. Optional: write one or two more tests surrounding the method you are solving to account for potential edge cases.

### Please include the skeleton of a new method + an accompanying test for someone else to work on at the time of creating a pull request! A pull request will most likely be denied if it does not contain a skeleton method for someone else to work on! For more information, please read the [Contributing Guide](https://github.com/BlakeGuilloud/ganon/blob/master/CONTRIBUTING.md).

Thank you so much for your contribution!

**Comment by JH108** [comment]
I have started on this issue.
