### ISSUE TITLE
Fix weaveArrays method

### ISSUE THREAD

**Issue by emilyanndavis** [BlakeGuilloud/ganon#626]
There is currently a method called `weaveArrays` that lives in `/lib/weaveArrays.js`.
It is incomplete and needs to be fixed!

`weaveArrays` takes two arrays and combines them into a new array by alternating values from the first and second arrays. 

The resulting array should begin with the first element from the first array, followed by the first element from the second array, then the second element from the first array, and so on, until the end of either the first or the second array has been reached and the resulting array ends with an element from the second array.

Example: `weaveArrays( [1, 2, 3], [4, 5, 6, 7, 8] ) === [1, 4, 2, 5, 3, 6]`

### Acceptance Criteria:
1. Running `yarn test weaveArrays` results in tests passing.
2. You have written a skeleton method for someone else to work on.
3. You have written tests surrounding your skeleton method.
4. Running `yarn lint` does not print any errors to the console!
5. Optional: write one or two more tests surrounding the method you are solving to account for potential edge cases.

### Please include the skeleton of a new method + an accompanying test for someone else to work on at the time of creating a pull request! A pull request will most likely be denied if it does not contain a skeleton method for someone else to work on! For more information, please read the [Contributing Guide](https://github.com/BlakeGuilloud/ganon/blob/master/CONTRIBUTING.md).

Thank you so much for your contribution!

**Comment by KevBelisle** [comment]
I'll take this one if it's available!

**Comment by BlakeGuilloud** [comment]
You got it @KevBelisle !
