### ISSUE TITLE
Fix convertBytesToKilobytes method

### ISSUE THREAD

**Issue by jamesg1** [BlakeGuilloud/ganon#629]
There is currently a method called `convertBytesToKilobytes` that lives in `/lib/convertBytesToKilobytes.js`.
It is incomplete and needs to be fixed!

The method should take a number in bytes and return the equivalent in Kilobytes. More information about bits and bytes can be found [here](https://web.stanford.edu/class/cs101/bits-gigabytes.html).

### Acceptance Criteria:
1. Running `yarn test convertBytesToKilobytes` results in tests passing.
2. You have written a skeleton method for someone else to work on.
3. You have written tests surrounding your skeleton method.
4. Running `yarn lint` does not print any errors to the console!
5. Optional: write one or two more tests surrounding the method you are solving to account for potential edge cases.

### Please include the skeleton of a new method + an accompanying test for someone else to work on at the time of creating a pull request! A pull request will most likely be denied if it does not contain a skeleton method for someone else to work on! For more information, please read the [Contributing Guide](https://github.com/BlakeGuilloud/ganon/blob/master/CONTRIBUTING.md).

Thank you so much for your contribution!

**Comment by jamesg1** [comment]
Dependent on PR #628 being merged first.

**Comment by newbazz** [comment]
![image](https://user-images.githubusercontent.com/25884863/32141231-0ba70cc2-bca1-11e7-9208-0368239d0bc7.png)y 
can anyone help me out am i facing this error.

**Comment by jamesg1** [comment]
Hey @newbazz you need to update your node version as it is out of date for yarn. You can install node from here https://nodejs.org/en/download/ or use node version manager https://github.com/creationix/nvm so you can switch between node versions easily.

**Comment by MSSR-code** [comment]
I've updated the node as specified about but I'm getting a similar error
![screenshot 28](https://user-images.githubusercontent.com/20289525/32141444-9f0b5d60-bca6-11e7-93ad-7293bbbf9f1d.png)

**Comment by BlakeGuilloud** [comment]
Hey @MSSR-code - it looks like you haven't run `yarn install` in your ganon repo. Jest is a dependency we use for our unit tests, so you must first install it. Try running `yarn` or `yarn install` and then run your tests.

**Comment by jamesg1** [comment]
@MSSR-code Make sure to read the Readme - https://github.com/BlakeGuilloud/ganon/blob/master/README.md
