### ISSUE TITLE
Fix kebabCase function

### ISSUE THREAD

**Issue by jbharat** [BlakeGuilloud/ganon#632]
There is currently a method called `kebabCase` that lives in `/lib/kebabCase.js`.
It is incomplete and needs to be fixed!

This function returns the kebabCase of a string

### Acceptance Criteria:
1. Running `yarn test kebabCase` results in tests passing.
2. You have written a skeleton method for someone else to work on.
3. You have written tests surrounding your skeleton method.
4. Running `yarn lint` does not print any errors to the console!
5. Optional: write one or two more tests surrounding the method you are solving to account for potential edge cases.

### Please include the skeleton of a new method + an accompanying test for someone else to work on at the time of creating a pull request! A pull request will most likely be denied if it does not contain a skeleton method for someone else to work on! For more information, please read the [Contributing Guide](https://github.com/BlakeGuilloud/ganon/blob/master/CONTRIBUTING.md).

Thank you so much for your contribution!

**Comment by jbharat** [comment]
requires #630 to be merged

**Comment by jamesg1** [comment]
Hi I would like to do this one, Thanks

**Comment by BlakeGuilloud** [comment]
You got it @jamesg1
