### ISSUE TITLE
Fix convertPetabytesToGigabytes

### ISSUE THREAD

**Issue by jamesg1** [BlakeGuilloud/ganon#638]
There is currently a method called `convertPetabytesToGigabytes ` that lives in `/lib/convertPetabytesToGigabytes.js`.
It is incomplete and needs to be fixed!

The method should take a number of Petabytes and return the equivalent in Gigabytes. More information about bits and bytes can be found [here](https://web.stanford.edu/class/cs101/bits-gigabytes.html).

### Acceptance Criteria:
1. Running `yarn test convertPetabytesToGigabytes` results in tests passing.
2. You have written a skeleton method for someone else to work on.
3. You have written tests surrounding your skeleton method.
4. Running `yarn lint` does not print any errors to the console!
5. Optional: write one or two more tests surrounding the method you are solving to account for potential edge cases.

### Please include the skeleton of a new method + an accompanying test for someone else to work on at the time of creating a pull request! A pull request will most likely be denied if it does not contain a skeleton method for someone else to work on! For more information, please read the [Contributing Guide](https://github.com/BlakeGuilloud/ganon/blob/master/CONTRIBUTING.md).

Thank you so much for your contribution!

**Comment by jamesg1** [comment]
Requires #618 to be merged first.

**Comment by newbazz** [comment]
I would like to work on this.

**Comment by BlakeGuilloud** [comment]
@newbazz - I commented on some of the PRs you opened. You need to make sure to include a skeleton method for someone else to work on whenever you submit a PR. Please review the Contributing Guide for more details. Thanks!
