### ISSUE TITLE
countCharOccuranceInString

### ISSUE THREAD

**Issue by jamesg1** [BlakeGuilloud/ganon#640]
There is currently a method called `countCharOccuranceInString` that lives in `/lib/countCharOccuranceInString.js`.
It is incomplete and needs to be fixed!

This method takes in a string and value to be found within the string, then it should count and return the number of times it has occurred within the string.

### Acceptance Criteria:
1. Running `yarn test countCharOccuranceInString ` results in tests passing.
2. You have written a skeleton method for someone else to work on.
3. You have written tests surrounding your skeleton method.
4. Running `yarn lint` does not print any errors to the console!
5. Optional: write one or two more tests surrounding the method you are solving to account for potential edge cases.

### Please include the skeleton of a new method + an accompanying test for someone else to work on at the time of creating a pull request! A pull request will most likely be denied if it does not contain a skeleton method for someone else to work on! For more information, please read the [Contributing Guide](https://github.com/BlakeGuilloud/ganon/blob/master/CONTRIBUTING.md).

Thank you so much for your contribution!

**Comment by jamesg1** [comment]
#632 PR should be closed before this one.

**Comment by kylevv** [comment]
@BlakeGuilloud  I'll work on this one!

**Comment by jhdoak** [comment]
I'll take this one.

**Comment by BlakeGuilloud** [comment]
Sounds good @jhdoak !
