### ISSUE TITLE
Fix isEmailAddress

### ISSUE THREAD

**Issue by Soben** [BlakeGuilloud/ganon#645]
There is currently a method called `isEmailAddress` that lives in `/lib/isEmailAddress.js`.
It is incomplete and needs to be fixed!

`isEmailAddress` is a function to return true or false if the email is a valid address. Checks for support for special characters like +

### Acceptance Criteria:
1. Running `yarn test isEmailAddress` results in tests passing.
2. You have written a skeleton method for someone else to work on.
3. You have written tests surrounding your skeleton method.
4. Running `yarn lint` does not print any errors to the console!
5. Optional: write one or two more tests surrounding the method you are solving to account for potential edge cases.

### Please include the skeleton of a new method + an accompanying test for someone else to work on at the time of creating a pull request! A pull request will most likely be denied if it does not contain a skeleton method for someone else to work on! For more information, please read the [Contributing Guide](https://github.com/BlakeGuilloud/ganon/blob/master/CONTRIBUTING.md).

Thank you so much for your contribution!

**Comment by Soben** [comment]
@davcs86 , you told me you wanted to know when this one was available.

**Comment by davcs86** [comment]
Yep, thanks @Soben
