### ISSUE TITLE
fix method findAndRemove

### ISSUE THREAD

**Issue by jsjain007** [BlakeGuilloud/ganon#651]
There is currently a method called `findAndRemove` that lives in `/lib/findAndRemove.js`.
It is incomplete and needs to be fixed!

It finds and removes all occurrences of the given second argument number if present in the array and returns the modified array else returns false if no such element was found in the array.

### Acceptance Criteria:
1. Running `yarn test <methodName>` results in tests passing.
2. You have written a skeleton method for someone else to work on.
3. You have written tests surrounding your skeleton method.
4. Running `yarn lint` does not print any errors to the console!
5. Optional: write one or two more tests surrounding the method you are solving to account for potential edge cases.

### Please include the skeleton of a new method + an accompanying test for someone else to work on at the time of creating a pull request! A pull request will most likely be denied if it does not contain a skeleton method for someone else to work on! For more information, please read the [Contributing Guide](https://github.com/BlakeGuilloud/ganon/blob/master/CONTRIBUTING.md).

Thank you so much for your contribution!

**Comment by jsjain007** [comment]
Assuming request #653 is merged.

**Comment by jhdoak** [comment]
I'd like to try this one, if that's ok.

**Comment by BlakeGuilloud** [comment]
Yeah man. Absolutely
