### ISSUE TITLE
Fix throttle function

### ISSUE THREAD

**Issue by kylevv** [BlakeGuilloud/ganon#652]
There is currently a method called `throttle` that lives in `/lib/throttle.js`.
It is incomplete and needs to be fixed!

Throttle takes a callback function and wait time (ms) and returns a throttled version of the callback.
A throttled function can only invoke the original callback as frequently as is specified by the 'wait' argument.

### Acceptance Criteria:
1. Running `yarn test throttle` results in tests passing.
2. You have written a skeleton method for someone else to work on.
3. You have written tests surrounding your skeleton method.
4. Running `yarn lint` does not print any errors to the console!
5. Optional: write one or two more tests surrounding the method you are solving to account for potential edge cases.

### Please include the skeleton of a new method + an accompanying test for someone else to work on at the time of creating a pull request! A pull request will most likely be denied if it does not contain a skeleton method for someone else to work on! For more information, please read the [Contributing Guide](https://github.com/BlakeGuilloud/ganon/blob/master/CONTRIBUTING.md).

Thank you so much for your contribution!

**Comment by josephmcasey** [comment]
I'll pick this one up!

**Comment by BlakeGuilloud** [comment]
Thanks @josephmcasey !

**Comment by josephmcasey** [comment]
@kylevv , thanks for the throttle function! I submitted a pull request #720 . Looking forward to my review!
