### ISSUE TITLE
Fix Shannon Entropy

### ISSUE THREAD

**Issue by emerali** [BlakeGuilloud/ganon#658]
There is currently a method called `shannonEntropy` that lives in `/lib/shannonEntropy.js`.
It is incomplete and needs to be fixed!

The method computes the Shannon Entropy of a discrete random variable specified by either a list or a map from objects to their respective probabilities.

Entropy is a measure of the average amount of information a random variable
  contains. (Here, we'll limit our attention to discrete random variables)

A good introductory video can be found [here](https://www.youtube.com/watch?v=2s3aJfRr9gE)

Is it computed by the calculating the product of the probability and information content of an outcome of the random variable like so:

```
P(x) * I(x) = P(x) * (- log P(x))
```

and then summing over all values of this product for each possible outcome of the random variable. The logarithm can be taken to any base, yielding different units of entropy. Common units of entropy are bits (also known as shannons) for base 2 logarithms, nats (or natural units) for base e logarithms, and bans (or hartleys) for base 10 logarithms.

As an example, given a uniform random variable (ie. one whose outcomes all have equal probability) called X, which can take on the values [1,2,3] we compute the information entropy as:

```
 H(X) = [P(1) * (- log P(1))] + [P(2) * (- log P(2))] + [P(3) * (- log P(3))]
      = [(1/3) * (- log(1/3))] + [(1/3) * (- log(1/3))] + [(1/3) * (- log(1/3))]
      = - log (1/3)
      = log 3
```

### Acceptance Criteria:
1. Running `yarn test shannonEntropy` results in tests passing.
2. You have written a skeleton method for someone else to work on.
3. You have written tests surrounding your skeleton method.
4. Running `yarn lint` does not print any errors to the console!
5. Optional: write one or two more tests surrounding the method you are solving to account for potential edge cases.

### Please include the skeleton of a new method + an accompanying test for someone else to work on at the time of creating a pull request! A pull request will most likely be denied if it does not contain a skeleton method for someone else to work on! For more information, please read the [Contributing Guide](https://github.com/BlakeGuilloud/ganon/blob/master/CONTRIBUTING.md).

Thank you so much for your contribution!

**Comment by stspasow** [comment]
I would like to work on this.

**Comment by BlakeGuilloud** [comment]
You got it @stspasow ! Thanks
