### ISSUE TITLE
fix toPigLatin

### ISSUE THREAD

**Issue by jturinetti** [BlakeGuilloud/ganon#660]
There is currently a method called `toPigLatin` that lives in `/lib/toPigLatin.js`.
It is incomplete and needs to be fixed!

Convert an input string to Pig Latin.  Pig Latin takes all leading consonants from the beginning of a word, moves them to the end of the word, then appends "ay" to the end of the word.  If the word begins with "qu", those 2 letters should be moved together.

Examples:
pig -> igpay
latin -> atinlay
cheers -> eerschay
smile -> ilesmay
quickly -> icklyquay

### Acceptance Criteria:
1. Running `yarn test toPigLatin` results in tests passing.
2. You have written a skeleton method for someone else to work on.
3. You have written tests surrounding your skeleton method.
4. Running `yarn lint` does not print any errors to the console!
5. Optional: write one or two more tests surrounding the method you are solving to account for potential edge cases.

### Please include the skeleton of a new method + an accompanying test for someone else to work on at the time of creating a pull request! A pull request will most likely be denied if it does not contain a skeleton method for someone else to work on! For more information, please read the [Contributing Guide](https://github.com/BlakeGuilloud/ganon/blob/master/CONTRIBUTING.md).

Thank you so much for your contribution!

**Comment by jturinetti** [comment]
Skeleton method will be available once PR #648 is merged.

**Comment by AndreFCruz** [comment]
I'll work on this issue

**Comment by BlakeGuilloud** [comment]
Sounds good @AndreFCruz !
