### ISSUE TITLE
Fix convertKilowattsToHorsepower function

### ISSUE THREAD

**Issue by TheWillG** [BlakeGuilloud/ganon#668]
There is currently a method called convertKilowattsToHorsepower that lives in /lib/convertKilowattsToHorsepower.js.
It is incomplete and needs to be fixed!

The method should take a number in kilowatts and return the equivalent in horsepower.

Acceptance Criteria:

Running yarn test convertKilowattsToHorsepower results in tests passing.
You have written a skeleton method for someone else to work on.
You have written tests surrounding your skeleton method.
Running yarn lint does not print any errors to the console!
Optional: write one or two more tests surrounding the method you are solving to account for potential edge cases.
Please include the skeleton of a new method + an accompanying test for someone else to work on at the time of creating a pull request! A pull request will most likely be denied if it does not contain a skeleton method for someone else to work on! For more information, please read the Contributing Guide.

**Comment by venividivici440** [comment]
I'll work on this.
