### ISSUE TITLE
Fix isHarshad

### ISSUE THREAD

**Issue by ryr3** [BlakeGuilloud/ganon#670]
There is currently a method called isHarshad that lives in `/lib/isHarshad.js`.
It is incomplete and needs to be fixed!

This method checks if a number is a Harshad number or not. A Harshad number is an integer which is divisible by the sum of its digits.

### Acceptance Criteria:
1. Running `yarn test isHarshad` results in tests passing.
2. You have written a skeleton method for someone else to work on.
3. You have written tests surrounding your skeleton method.
4. Running `yarn lint` does not print any errors to the console!
5. Optional: write one or two more tests surrounding the method you are solving to account for potential edge cases.

### Please include the skeleton of a new method + an accompanying test for someone else to work on at the time of creating a pull request! A pull request will most likely be denied if it does not contain a skeleton method for someone else to work on! For more information, please read the [Contributing Guide](https://github.com/BlakeGuilloud/ganon/blob/master/CONTRIBUTING.md).

Thank you so much for your contribution!

**Comment by guilhermecomum** [comment]
Let me try this ;)

**Comment by TheWillG** [comment]
@guilhermecomum just saw you commented on this.  Give the newly created convertWattsToBTUPerHour a try ;).
