### ISSUE TITLE
Fix without function

### ISSUE THREAD

**Issue by andreasgruenh** [BlakeGuilloud/ganon#68]
There is currently a method called `without` that lives in `/lib/without.js`.
It is incomplete and needs to be fixed!

### Acceptance Criteria:
1. Running `yarn test without` results in tests passing.

#### Please include the skeleton of a new method + an accompanying test for someone else to work on at the time of creating a pull request!

**Comment by DanielSauve** [comment]
I think I'd like to give this a shot!

**Comment by BlakeGuilloud** [comment]
Cool deal @DanielSauve ! I'll mark it as "in progress" until you make a PR. Thanks!
