### ISSUE TITLE
fix deepSearch function

### ISSUE THREAD

**Issue by jbharat** [BlakeGuilloud/ganon#689]
There is currently a method called `deepSearch` that lives in `/lib/deepSearch.js`.
It is incomplete and needs to be fixed!

deepSearch searches through an object/array and return a list of all objects that match the test function

### Acceptance Criteria:
1. Running `yarn test deepSearch` results in tests passing.
2. You have written a skeleton method for someone else to work on.
3. You have written tests surrounding your skeleton method.
4. Running `yarn lint` does not print any errors to the console!
5. Optional: write one or two more tests surrounding the method you are solving to account for potential edge cases.

### Please include the skeleton of a new method + an accompanying test for someone else to work on at the time of creating a pull request! A pull request will most likely be denied if it does not contain a skeleton method for someone else to work on! For more information, please read the [Contributing Guide](https://github.com/BlakeGuilloud/ganon/blob/master/CONTRIBUTING.md).

Thank you so much for your contribution!

**Comment by jbharat** [comment]
#688 should be merged first

**Comment by ktilcu** [comment]
#688 is merged

**Comment by gracemgately** [comment]
@BlakeGuilloud I know Hacktoberfest is coming to a close, but I would like to work on this!

**Comment by BlakeGuilloud** [comment]
you got it @gracemgately ! I will continue to maintain this repo as long as we have contributors. Thanks!
