### ISSUE TITLE
Fix isNull method

### ISSUE THREAD

**Issue by KevBelisle** [BlakeGuilloud/ganon#692]
There is currently a method called `isNull` that lives in `/lib/isNull.js`.
It is incomplete and needs to be fixed!

The method should return `true` if the value passed in is `null`, and false if it receives anything else (including other "falsy" values like 0, undefined, false, etc).

### Acceptance Criteria:
1. Running `yarn test isNull` results in tests passing.
2. You have written a skeleton method for someone else to work on.
3. You have written tests surrounding your skeleton method.
4. Running `yarn lint` does not print any errors to the console!
5. Optional: write one or two more tests surrounding the method you are solving to account for potential edge cases.

### Please include the skeleton of a new method + an accompanying test for someone else to work on at the time of creating a pull request! A pull request will most likely be denied if it does not contain a skeleton method for someone else to work on! For more information, please read the [Contributing Guide](https://github.com/BlakeGuilloud/ganon/blob/master/CONTRIBUTING.md).

Thank you so much for your contribution!

**Comment by mkp13** [comment]
I'll have this one.

**Comment by amoradi** [comment]
Thanks @mkp13. Go for it! 🎃
