### ISSUE TITLE
firstUniqueChar Method

### ISSUE THREAD

**Issue by BlakeGuilloud** [BlakeGuilloud/ganon#70]
There is currently a method called `firstUniqueChar` that lives in `/lib/firstUniqueChar.js`.
It is incomplete and needs to be fixed!

### Acceptance Criteria:
1. Running `yarn test firstUniqueChar` results in tests passing.

#### Please include the skeleton of a new method + an accompanying test for someone else to work on at the time of creating a pull request!

**Comment by epesco** [comment]
hey @BlakeGuilloud ! hoping to grab this issue

**Comment by BlakeGuilloud** [comment]
@epesco ! It's all yours!!

**Comment by erinesco** [comment]
Awesome! thanks for the fast response

**Comment by andreasgruenh** [comment]
We will remove the "in progress" label because this has been stale for 24 hours. This means this issue is now "first come first merge"

**Comment by ltetzlaff** [comment]
can be closed i think #55

**Comment by andreasgruenh** [comment]
Ah, thanks for noticing @ltetzlaff !

**Comment by erinesco** [comment]
Ah, didn't see the 24 hour limit, let me know if there's any other way I can contribute!

**Comment by BlakeGuilloud** [comment]
Hey sorry @erinesco !! We tried to clean up our pull requests lane today and someone snuck that in! Feel free to take a look at other current issues, and if any of them strike your interest, @BlakeGuilloud me and i'll make sure that your work gets in.
