### ISSUE TITLE
Fix abbreviateFirstName Method

### ISSUE THREAD

**Issue by KevinBruland** [BlakeGuilloud/ganon#704]
There is currently a method called `abbreviateFirstName` that lives in `/lib/abbreviateFirstName.js`.
It is incomplete and needs to be fixed!

This method expects a string containing a first and last name in order to convert into an abbreviated format with capitalized names. For example, "john smith" is returned as "J. Smith". You need to make sure it throws an error when it does not receive a string, non-alphabet characters, or more than a first and last name.

### Acceptance Criteria:
1. Running `yarn test <methodName>` results in tests passing.
2. You have written a skeleton method for someone else to work on.
3. You have written tests surrounding your skeleton method.
4. Running `yarn lint` does not print any errors to the console!
5. Optional: write one or two more tests surrounding the method you are solving to account for potential edge cases.

### Please include the skeleton of a new method + an accompanying test for someone else to work on at the time of creating a pull request! A pull request will most likely be denied if it does not contain a skeleton method for someone else to work on! For more information, please read the [Contributing Guide](https://github.com/BlakeGuilloud/ganon/blob/master/CONTRIBUTING.md).

Thank you so much for your contribution!

**Comment by JedraPeake** [comment]
@BlakeGuilloud I would like to work on this

**Comment by BlakeGuilloud** [comment]
You got it @JedraPeake !
