### ISSUE TITLE
Fix countDigits method

### ISSUE THREAD

**Issue by thancock20** [BlakeGuilloud/ganon#705]
There is currently a method called `countDigits` that lives in `/lib/countDigits.js`.
It is incomplete and needs to be fixed!

This method should take a string, and return the number of digits in the string.
e.g. `countDigits("The answer is 42, but 0 people know the question")` should return `3`.

### Acceptance Criteria:
1. Running `yarn test countDigits` results in tests passing.
2. You have written a skeleton method for someone else to work on.
3. You have written tests surrounding your skeleton method.
4. Running `yarn lint` does not print any errors to the console!
5. Optional: write one or two more tests surrounding the method you are solving to account for potential edge cases.

### Please include the skeleton of a new method + an accompanying test for someone else to work on at the time of creating a pull request! A pull request will most likely be denied if it does not contain a skeleton method for someone else to work on! For more information, please read the [Contributing Guide](https://github.com/BlakeGuilloud/ganon/blob/master/CONTRIBUTING.md).

Thank you so much for your contribution!

**Comment by cherealnice** [comment]
Hi, I'd like to work on this!

**Comment by BlakeGuilloud** [comment]
Hey @cherealnice - I made a comment in your PR. Gonna mark this as 'in progress' for now.

**Comment by cherealnice** [comment]
My mistake, I just update the PR :)
