### ISSUE TITLE
Fix Average method

### ISSUE THREAD

**Issue by BlakeGuilloud** [BlakeGuilloud/ganon#71]
There is currently a method called `average` that lives in `/lib/average.js`.
It is incomplete and needs to be fixed!

### Acceptance Criteria:
1. Running `yarn test average` results in tests passing.

#### Please include the skeleton of a new method + an accompanying test for someone else to work on at the time of creating a pull request!

**Comment by brycereynolds** [comment]
Added https://github.com/BlakeGuilloud/ganon/pull/76

**Comment by BlakeGuilloud** [comment]
Thanks @brycereynolds ! I'll take a look now and close out after merging in!
