### ISSUE TITLE
Fix fibonacci method || test

### ISSUE THREAD

**Issue by BlakeGuilloud** [BlakeGuilloud/ganon#72]
There is currently a method called `fibonacci` that lives in `/lib/fibonacci.js`.
Something is wrong and the test is failing! I could use a hand figuring out what's going on- it could be the test itself.

### Acceptance Criteria:
1. Running `yarn test fibonacci` results in tests passing.

#### Please include the skeleton of a new method + an accompanying test for someone else to work on at the time of creating a pull request!

**Comment by edgardmota** [comment]
Hi... can I have this one too? I've already asked for the #73 issue! Thanks! :smile:

**Comment by BlakeGuilloud** [comment]
Hey @edgardmota ! Sure. Just remember to please build out a skeleton for a new problem for each existing one you fix! That way we can keep this chain going!

**Comment by edgardmota** [comment]
The PR #99 also correct this test. I wasn't planning to pull them all together but it seems I'm still lacking some experience on Git/Github

**Comment by BlakeGuilloud** [comment]
No worries. It has been merged into master! thanks
