### ISSUE TITLE
Fix convertTablespoonsToTeaspoons method

### ISSUE THREAD

**Issue by rossdeane** [BlakeGuilloud/ganon#723]
There is currently a method called convertInchesToYards that lives in /lib/convertTablespoonsToTeaspoons.js.
It is incomplete and needs to be fixed!

This method expects a number as input (tablespoons) and should return a number (teaspoons). You need to make sure it throws an error when the input is not a number, or when the number is negative.

Acceptance Criteria:

Running yarn test convertTablespoonsToTeaspoons results in tests passing.
You have written a skeleton method for someone else to work on.
You have written tests surrounding your skeleton method.
Running yarn lint does not print any errors to the console!
Optional: write one or two more tests surrounding the method you are solving to account for potential edge cases.
Please include the skeleton of a new method + an accompanying test for someone else to work on at the time of creating a pull request! A pull request will most likely be denied if it does not contain a skeleton method for someone else to work on! For more information, please read the Contributing Guide.

Thank you so much for your contribution!

**Comment by emilyanndavis** [comment]
I'll take this one @BlakeGuilloud !
