### ISSUE TITLE
Fix floor method

### ISSUE THREAD

**Issue by BlakeGuilloud** [BlakeGuilloud/ganon#73]
There is currently a method called `floor` that lives in `/lib/floor.js`.
It is incomplete and needs to be fixed!

### Acceptance Criteria:
1. Running `yarn test floor` results in tests passing.

#### Please include the skeleton of a new method + an accompanying test for someone else to work on at the time of creating a pull request!

**Comment by edgardmota** [comment]
Hi, @BlakeGuilloud ! Can I have this? Thanks!

**Comment by BlakeGuilloud** [comment]
![image](https://user-images.githubusercontent.com/14660993/31694462-6d978b88-b372-11e7-83c8-c0517d137b45.png)

**Comment by edgardmota** [comment]
Fixed on PR #99

**Comment by BlakeGuilloud** [comment]
Great work man! Thanks for the contrib!
