### ISSUE TITLE
Fix surfaceAreaOfSphere Method

### ISSUE THREAD

**Issue by stspasow** [BlakeGuilloud/ganon#732]
There is currently a method called `surfaceAreaOfSphere` that lives in `/lib/surfaceAreaOfSphere.js`.
It is incomplete and needs to be fixed!

This method expects a the sphere's radius as input. You then need to calculate the surface area using this radius. You need to make sure it throws an error when the radius is negative.

### Acceptance Criteria:
1. Running `yarn test surfaceAreaOfSphere` results in tests passing.
2. You have written a skeleton method for someone else to work on.
3. You have written tests surrounding your skeleton method.
4. Running `yarn lint` does not print any errors to the console!
5. Optional: write one or two more tests surrounding the method you are solving to account for potential edge cases.

### Please include the skeleton of a new method + an accompanying test for someone else to work on at the time of creating a pull request! A pull request will most likely be denied if it does not contain a skeleton method for someone else to work on! For more information, please read the [Contributing Guide](https://github.com/BlakeGuilloud/ganon/blob/master/CONTRIBUTING.md).

Thank you so much for your contribution!

**Comment by stspasow** [comment]
Requires #714  to be merged.

**Comment by J4unty** [comment]
I'd like to do this one.

**Comment by NoahT** [comment]
@BlakeGuilloud I would like to work on this

**Comment by BlakeGuilloud** [comment]
You got it @NoahT !
