### ISSUE TITLE
Discussion: enhancing the monadic `is` method

### ISSUE THREAD

**Issue by josephmcasey** [BlakeGuilloud/ganon#733]
## Context

This repositories largest collection of functions are `is[Something]` functions. I would like to start a discussion on improving the utility of the `is` function and reducing reliance on individual `is` methods. My aim in this discussion is to close the issue once further action on the `is` method has been discussed.

## Format of current is methods

The typical is format in this repository goes as following:

`boolean isSomething throws TypeError (Any : Value)`

I believe if we standardize all methods under the `is` naming convention to follow something like this pattern we can expand the principle usage of a more generic `is` functional method.

## Expanding `is` method functionality 

If this method signature format were standardized on all `is` type methods then we rely on those standards to expand the existing functionality of the `is` method like so 

```
is(["Number","String","PrimeNumber"])  // returns func 
// func(2) returns [true, false, true]
```

## Reusing the principle discussed here

Once a large enough collection of methods using a standard naming convention exist, we could use the format discussed here to help expand the functionality of the other generic functions like `convert` or the non-existent `array`.

**Comment by BlakeGuilloud** [comment]
Hey @josephmcasey - I think you bring up a great point here. There is a TON of duplicated code that could be cleaned up to follow better patterns like you are mentioning. As the initial scope of this project was to get everyone involved, I have been extremely lenient oh what I let into the project. However, as Hacktoberfest comes to an end, I would love to start beefing up the library, enhancing methods like the above mentioned `is` function, and putting a few more rules on what we allow into the project.

I think the `is` method is a perfect place to start. Would you mind if I tagged you in future pull requests that may fall into this category?

**Comment by josephmcasey** [comment]
Congratulations on being one of the top Hacktoberfest projects! @BlakeGuilloud you've done an excellent job in creating, managing and leading this project!

I would definitely be up for getting tagged in future pull requests that may fall into this category!

**Comment by BlakeGuilloud** [comment]
Thanks man!! It's been really fun. I started with `sum`, `difference`, `product`, and `quotient` and the community did the rest of the work.
