### ISSUE TITLE
Fix Median method

### ISSUE THREAD

**Issue by BlakeGuilloud** [BlakeGuilloud/ganon#74]
There is currently a method called `median` that lives in `/lib/median.js`.
It is incomplete and needs to be fixed!

### Acceptance Criteria:
1. Running `yarn test median` results in tests passing.

#### Please include the skeleton of a new method + an accompanying test for someone else to work on at the time of creating a pull request!

**Comment by LSBOSS** [comment]
@BlakeGuilloud I would like to tackle this problem :)

**Comment by BlakeGuilloud** [comment]
Go for it @LSBOSS !
