### ISSUE TITLE
Fix signedAngle

### ISSUE THREAD

**Issue by ltetzlaff** [BlakeGuilloud/ganon#757]
There is currently a method called `signedAngle` that lives in `/lib/signedAngle.js`.
It is incomplete and needs to be fixed!

Return the angle in degrees with the smallest possible absolute value

### Acceptance Criteria:
1. Running `yarn test <methodName>` results in tests passing.
2. You have written a skeleton method for someone else to work on.
3. You have written tests surrounding your skeleton method.
4. Running `yarn lint` does not print any errors to the console!
5. Optional: write one or two more tests surrounding the method you are solving to account for potential edge cases.

### Please include the skeleton of a new method + an accompanying test for someone else to work on at the time of creating a pull request! A pull request will most likely be denied if it does not contain a skeleton method for someone else to work on! For more information, please read the [Contributing Guide](https://github.com/BlakeGuilloud/ganon/blob/master/CONTRIBUTING.md).

Thank you so much for your contribution!

**Comment by Vikas350** [comment]
Hi @ltetzlaff, I want to contribute to this, can you please assign it to me?

**Comment by Vikas350** [comment]
Hi @ktilcu and @ltetzlaff, I have created a PR and linked it to that issue, please review it & let me know if it is good.
