### ISSUE TITLE
Fix Ceiling Method

### ISSUE THREAD

**Issue by DanielSauve** [BlakeGuilloud/ganon#78]
There is currently a method called `ceiling` that lives in `/lib/ceiling.js`.
It is incomplete and needs to be fixed!

### Acceptance Criteria:
1. Running `yarn test ceiling` results in tests passing.

#### Please include the skeleton of a new method + an accompanying test for someone else to work on at the time of creating a pull request!

**Comment by victorsch** [comment]
Hey, I'd like to take on this issue.

**Comment by BlakeGuilloud** [comment]
Go for it @victorsch !

**Comment by ktilcu** [comment]
I'm on it.
