### ISSUE TITLE
Fix clamp method

### ISSUE THREAD

**Issue by LSBOSS** [BlakeGuilloud/ganon#79]
There is currently a method called `clamp` that lives in `/lib/clamp.js`.
It is incomplete and needs to be fixed!

### Acceptance Criteria:
1. Running `yarn test clamp` results in tests passing.

#### Please include the skeleton of a new method + an accompanying test for someone else to work on at the time of creating a pull request!

**Comment by Wulingoh** [comment]
Hi there, 
I am happy to take a look at it. 

Cheers,
wulingoh

**Comment by BlakeGuilloud** [comment]
Cool deal. I'll mark as in progress! Thanks!
