### ISSUE TITLE
Setup a precommit-hook for linting

### ISSUE THREAD

**Issue by BlakeGuilloud** [BlakeGuilloud/ganon#80]
We need to prevent people from committing code that doesn't follow our linting rules, as we already have 34 eslint errors! We should implement a hook that runs when a user attempts to commit code to make sure they have followed all of our rules.

I do not know much about precommit hooks, but from my understanding there are plenty of packages out there to solve this issue- this is the first one I found:
[precommit-hook-eslint](https://www.npmjs.com/package/precommit-hook-eslint)

Acceptance Criteria
1. When a user runs `git commit -m 'message here'`, the command `yarn lint` runs.
2. If the linter passes, the user's commit goes through.
3. If the linter fails, the user's commit does not go through.

Unfortunately setting up this task properly requires the contributor to also resolve all of the existing linter errors, but should prevent this from happening in the future!

**Comment by luisvillalba** [comment]
I can do that, happy to help

**Comment by BlakeGuilloud** [comment]
Awesome @luisvillalba ! Feel free to take it in any direction you want. Like I mentioned, I'm pretty unfamiliar with the process. Thanks!!
