### ISSUE TITLE
Remove .DS_Store files and gitignore them

### ISSUE THREAD

**Issue by luisvillalba** [BlakeGuilloud/ganon#83]
Remove .DS_Store files since it doesn't make sense to have it in the repo, it should be ignored as well

### Acceptance Criteria:
None .DS_Store should be in the repo

**Comment by luisvillalba** [comment]
I'm doing this

**Comment by luisvillalba** [comment]
Can you tag this as a hacktoberfest issue?

**Comment by BlakeGuilloud** [comment]
Shore.
