### ISSUE TITLE
Fix the Square method

### ISSUE THREAD

**Issue by BlakeGuilloud** [BlakeGuilloud/ganon#9]
There is currently a method called `square` that lives in `/lib/square.js`.
It is incomplete and needs to be fixed!

### Acceptance Criteria:
1. Running `yarn test square` results in tests passing.

#### Please include the skeleton of a new method + an accompanying test for someone else to work on at the time of creating a pull request!

**Comment by hugoduraes** [comment]
I'll pick it up! :)

**Comment by BlakeGuilloud** [comment]
Sounds good @hugoduraes !
