### ISSUE TITLE
Fix Nor function.

### ISSUE THREAD

**Issue by BlakeGuilloud** [BlakeGuilloud/ganon#97]
There is currently a method called `nor` that lives in `/lib/nor.js`.
It is incomplete and needs to be fixed!

### Acceptance Criteria:
1. Running `yarn test nor` results in tests passing.

#### Please include the skeleton of a new method + an accompanying test for someone else to work on at the time of creating a pull request!

**Comment by BlakeGuilloud** [comment]
Hey @melissa3000 - I saw that you tried to ping me somewhere in the codebase. I can't find exactly where your comment is, but I assume it hast to do with this function? I'll put the in progress label on this, but if you could confirm that this is the issue you want to work on! Thanks!!

**Comment by melissa3000** [comment]
Thanks! I ended up switching to the min.js function, so you can remove the inprogress on this one. I'm still trying to add a new skeleton issue for the next person and am new to contributing so if it doesn't work correctly please let me know.

**Comment by BlakeGuilloud** [comment]
Great! Thanks, lets move this conversation to your PR https://github.com/BlakeGuilloud/ganon/pull/101 - I mentioned a skeleton method in there. Thanks!

**Comment by melissa3000** [comment]
Thanks! I added tests for isEven.test.js. 

Thanks so much for creating a beginner-friendly project! Please let me know if I missed anything else.

**Comment by BlakeGuilloud** [comment]
Hey @melissa3000 ! Judging by your pull requests I see that you may have tackled this issue; however, I'm seeing some weirdness in regards to there being multiple branches opened up with multiple pull requests. I am going to close them all out, and if you don't mind working on getting all everything you have done (fixing this issue + creating a skeleton method) into a single PR, I would be happy to merge it in! Thanks so much for you contribution!! Feel free to reach out to me if you have any issues with what I have requested.

Looking more into the PRs you have, it may have been caused by the master branch changing while you were submitting pull requests, so make sure you `git pull upstream master`, resolve any conflicts that may have arisen, push back up to your fork, and open a single pull request with your work in it. I'm going to apply the in progress tag to this while we figure out what's going on. Thanks!

**Comment by BlakeGuilloud** [comment]
This guy is back open!
