### ISSUE TITLE
Fix RemoveLast function

### ISSUE THREAD

**Issue by BlakeGuilloud** [BlakeGuilloud/ganon#98]
There is currently a method called `removeLast` that lives in `/lib/removeLast.js`.
It is incomplete and needs to be fixed!

### Acceptance Criteria:
1. Running `yarn test removeLast` results in tests passing.

#### Please include the skeleton of a new method + an accompanying test for someone else to work on at the time of creating a pull request!

**Comment by alcar** [comment]
Hello! I'd like to take this one!

**Comment by BlakeGuilloud** [comment]
Awesome @alcar !! Go for it. Just be sure to include a skeleton method for someone else to work on. I'm going to apply the 'in progress' label to it. This reserves the Issue for 24 hours. Thank you!
